import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const TEAM=["瑞子","普子","航子","辉子"],GUEST="访客",TRIP="chuanxi2026",enc=new TextEncoder();
const DAYS:any={
 "2026-10-02":{km:190,driveMin:225,points:[["天府国际机场",30.312,104.441],["服务区",30.16,103.65],["雅安",29.98,103.0]]},
 "2026-10-03":{km:280,driveMin:435,points:[["雅安",29.98,103.0],["泸定",29.92,102.23],["康定",30.05,101.96],["折多山",30.06,101.8],["新都桥",30.04,101.49]]},
 "2026-10-04":{km:160,driveMin:270,points:[["新都桥",30.04,101.49],["塔公",30.32,101.54],["八美",30.55,101.5],["丹巴",30.88,101.89],["中路藏寨",30.89,101.92]]},
 "2026-10-05":{km:120,driveMin:210,points:[["丹巴",30.88,101.89],["小金",30.99,102.36],["双桥沟",31.09,102.84],["四姑娘山镇",31.1,102.89]]},
 "2026-10-06":{km:285,driveMin:540,points:[["四姑娘山镇",31.1,102.89],["卧龙",31.04,103.18],["映秀",31.06,103.48],["都江堰",31.0,103.62],["天府国际机场",30.312,104.441]]},
 "2026-10-07":{km:12,driveMin:30,points:[["机场酒店",30.3,104.44],["还车点",30.31,104.43],["天府国际机场",30.312,104.441]]}
};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const b64=(bytes:Uint8Array)=>{let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")};
async function tokenHash(token:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(token));return b64(new Uint8Array(d))}
async function validSession(db:any,trip:string,person:string,token:string){if(![...TEAM,GUEST].includes(person)||!token||token.length<20)return false;const q=await db.from("person_sessions").select("expires_at").eq("trip_slug",trip).eq("person",person).eq("token_hash",await tokenHash(token)).maybeSingle();if(q.error)throw q.error;if(!q.data||new Date(q.data.expires_at).getTime()<=Date.now())return false;return true}
function hav(a:any,b:any){const R=6371,p=Math.PI/180,d1=(Number(b.lat)-Number(a.lat))*p,d2=(Number(b.lon)-Number(a.lon))*p,x=Math.sin(d1/2)**2+Math.cos(Number(a.lat)*p)*Math.cos(Number(b.lat)*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(Math.max(0,Math.min(1,x))))}
function dayRange(date:string){const start=new Date(`${date}T00:00:00+08:00`);return{start,end:new Date(start.getTime()+86400000)}}
function canonical(rows:any[]){const buckets=new Map<number,any>();for(const r of rows){const t=Date.parse(r.recorded_at);if(!Number.isFinite(t)||!Number.isFinite(Number(r.lat))||!Number.isFinite(Number(r.lon)))continue;const key=Math.floor(t/30000),old=buckets.get(key),acc=Number.isFinite(Number(r.accuracy))?Number(r.accuracy):9999,oldAcc=old&&Number.isFinite(Number(old.accuracy))?Number(old.accuracy):9999;if(!old||acc<oldAcc)buckets.set(key,r)}return [...buckets.values()].sort((a,b)=>Date.parse(a.recorded_at)-Date.parse(b.recorded_at))}
function sumDriverMinutes(rows:any[],start:Date,end:Date){let ms=0;for(const r of rows){const a=Math.max(start.getTime(),Date.parse(r.started_at||"")),b=Math.min(end.getTime(),r.ended_at?Date.parse(r.ended_at):Date.now());if(Number.isFinite(a)&&Number.isFinite(b)&&b>a)ms+=b-a}return Math.round(ms/60000)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST only"},405);try{const body=await req.json(),trip=String(body.trip_slug||TRIP),action=String(body.action||""),p=body.payload||{},person=String(p.person||""),token=String(p.token||"");if(action!=="state")return json({error:"read only",code:"read_only"},403);const date=String(p.date||"").slice(0,10);if(!/^2026-10-0[2-7]$/.test(date))return json({error:"日期不在本次行程内"},400);const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});if(!await validSession(db,trip,person,token))return json({error:"登录已失效，请重新进入",code:"session_invalid"},401);const {start,end}=dayRange(date);const [hist,progress,drivers]=await Promise.all([db.from("trip_position_history").select("person,lat,lon,accuracy,speed,heading,altitude,recorded_at").eq("trip_slug",trip).gte("recorded_at",start.toISOString()).lt("recorded_at",end.toISOString()).order("recorded_at",{ascending:true}),db.from("trip_progress").select("stop_index,stop_name,arrived_at,departed_at,lat,lon").eq("trip_slug",trip).eq("day_date",date).order("stop_index"),db.from("trip_driver_sessions").select("person,started_at,ended_at").eq("trip_slug",trip).lt("started_at",end.toISOString()).order("started_at",{ascending:true})]);for(const q of [hist,progress,drivers])if(q.error)return json({error:q.error.message},500);const driverRows=(drivers.data||[]).filter((r:any)=>!r.ended_at||Date.parse(r.ended_at)>start.getTime()),track=canonical(hist.data||[]),plan=DAYS[date],arrived=(progress.data||[]).filter((x:any)=>x.arrived_at),maxIdx=arrived.length?Math.max(...arrived.map((x:any)=>Number(x.stop_index)||0)):-1,ratio=plan.points.length>1&&maxIdx>=0?Math.min(1,Math.max(0,maxIdx/(plan.points.length-1))):0;let distance=0,movingMs=0,firstMove:any=null,lastMove:any=null,accepted=0;for(let i=1;i<track.length;i++){const a=track[i-1],b=track[i],dt=(Date.parse(b.recorded_at)-Date.parse(a.recorded_at))/1000;if(!(dt>0))continue;const d=hav(a,b),kmh=d/(dt/3600);if(!Number.isFinite(kmh)||kmh>180)continue;if(d>=0.01){distance+=d;accepted++}const sp=Math.max(Number(a.speed)||0,Number(b.speed)||0)*3.6,moving=(dt<=600)&&(kmh>=5||sp>=5);if(moving){movingMs+=Math.min(dt,180)*1000;if(!firstMove)firstMove=a.recorded_at;lastMove=b.recorded_at}}
const gpsGood=track.length>=5&&distance>=1;let source=gpsGood?"GPS轨迹":"节点估算";if(!gpsGood)distance=plan.km*ratio;const driverMin=sumDriverMinutes(driverRows,start,end),inferredMin=Math.round(movingMs/60000);let driveMin=driverMin>0?driverMin:(inferredMin>0?inferredMin:Math.round(plan.driveMin*ratio));const visited=new Set<string>();for(const r of arrived)visited.add(String(r.stop_name||""));if(track.length){for(const pt of plan.points){const [n,lat,lon]=pt;if(track.some((s:any)=>hav(s,{lat,lon})<=5))visited.add(n)}}const places=plan.points.map((x:any)=>x[0]).filter((n:string)=>visited.has(n));const firstSample=track[0]?.recorded_at||null,lastSample=track.at(-1)?.recorded_at||null;return json({ok:true,server_time:new Date().toISOString(),summary:{date,places,distance_km:Math.round(distance*10)/10,drive_minutes:Math.max(0,driveMin),first_move_at:firstMove||firstSample,last_move_at:lastMove||lastSample,gps_samples:track.length,accepted_segments:accepted,source,driver_minutes:driverMin,planned_km:plan.km,planned_drive_minutes:plan.driveMin,progress_ratio:ratio}})}catch(e){return json({error:String((e as any)?.message||e)},500)}});