(()=>{
const CLOUD={url:'https://wpfqcztbxxarsrruuuce.supabase.co',key:'sb_publishable_flsZaOM4nysh6H9hvyX8NA_Gx02wHnJ',fn:'https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync',trip:'chuanxi2026'};
let pin=sessionStorage.getItem('cw-cloud-pin')||'',client=null,channel=null,poll=null,remoteVehicle=null,lastPush=0,cloudMemories=[];
const $=id=>document.getElementById(id);
async function api(action,payload={}){if(!pin)throw new Error('请先输入旅行 PIN');const r=await fetch(CLOUD.fn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin,trip_slug:CLOUD.trip,action,payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error==='invalid_pin'?'PIN 不正确':(j.error||'云同步失败'));return j}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function syncLabel(ok=true){if($('cloudState'))$('cloudState').textContent=pin?(ok?'已同步':'同步异常'):'待解锁';if($('syncTitle'))$('syncTitle').textContent=pin?'四人实时云同步已开启':'云端已就绪 · 输入旅行 PIN';if($('syncDetail'))$('syncDetail').textContent=pin?'费用、还款、车辆位置、行程状态和共享纪念册会在四台手机之间同步。':'点击“云同步设置”输入旅行 PIN 后即可加入四人共享。'}
function showRemote(pt){if(!pt||!pin||typeof map==='undefined'||!map||typeof watchId==='undefined'||watchId!==null)return;try{if(!map.hasLayer(carMarker))carMarker.addTo(map);carMarker.setLatLng([+pt.lat,+pt.lon]);if($('vehicleState'))$('vehicleState').textContent=(pt.updated_by||'同行者')+'共享中';if($('gpsText'))$('gpsText').textContent='云端车辆位置'+(pt.accuracy?' ±'+Math.round(pt.accuracy)+'m':'');if($('overlayTitle'))$('overlayTitle').textContent='🚙 四人共享车辆位置';if($('overlayDetail'))$('overlayDetail').textContent=Number(pt.lat).toFixed(5)+', '+Number(pt.lon).toFixed(5)}catch(e){}}
function renderCloudPhotos(){if(!$('gallery')||!cloudMemories.length)return;const html=cloudMemories.filter(x=>x.url).map(x=>`<div class="photo"><img src="${x.url}"><div>${x.caption||'川西记忆'}</div></div>`).join('');if(html)$('gallery').innerHTML=html}
function applyState(j){try{if(j.expenses){expenses=j.expenses.map(e=>({id:e.id,date:(e.created_at||'').slice(0,10),category:e.category,amount:Number(e.amount),payer:e.payer,participants:e.participants||TEAM,note:e.note||e.category,status:e.status||'paid'}));localStorage.setItem('cw-expenses-v3',JSON.stringify(expenses))}if(j.repayments){settlements=j.repayments.map(x=>({id:x.id,from:x.from_person,to:x.to_person,amount:Number(x.amount),note:x.note||'还款'}));localStorage.setItem('cw-settlements-v3',JSON.stringify(settlements))}if(j.trip_state?.fuel_level!=null){fuel=Number(j.trip_state.fuel_level);localStorage.setItem('cw-fuel',String(fuel));if(typeof updateFuelUI==='function')updateFuelUI()}if(j.vehicle){remoteVehicle=j.vehicle;showRemote(remoteVehicle)}if(j.memories){cloudMemories=j.memories;renderCloudPhotos()}if(typeof renderLedger==='function')renderLedger();if(typeof render==='function')render();syncLabel(true)}catch(e){console.warn(e)}}
async function pull(showError=false){if(!pin)return;try{applyState(await api('get_state'))}catch(e){syncLabel(false);if(showError)alert(e.message)}}
function send(event,payload={}){try{channel?.send({type:'broadcast',event,payload})}catch(e){}}
function loadSupabase(){return new Promise((res,rej)=>{if(window.supabase)return res();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function realtime(){try{await loadSupabase();client=window.supabase.createClient(CLOUD.url,CLOUD.key,{auth:{persistSession:false}});const topic='trip-'+(await hash(pin+'|'+CLOUD.trip)).slice(0,32);channel=client.channel(topic,{config:{broadcast:{self:false}}}).on('broadcast',{event:'vehicle'},({payload})=>showRemote(payload)).on('broadcast',{event:'ledger'},()=>pull()).on('broadcast',{event:'state'},()=>pull()).on('broadcast',{event:'memory'},()=>pull()).subscribe()}catch(e){console.warn('Realtime fallback to polling',e)}}
async function unlockCloud(){const input=$('pinInput');const v=(input?.value||'').trim();if(v.length<4)return alert('请输入旅行 PIN');if($('privacyText'))$('privacyText').textContent='正在验证云端 PIN…';pin=v;try{const st=await api('get_state');sessionStorage.setItem('cw-cloud-pin',pin);sessionStorage.setItem('cw-private','1');privateUnlocked=true;if($('privacyModal'))$('privacyModal').classList.remove('show');if(input)input.value='';if(typeof applyPrivacy==='function')applyPrivacy();applyState(st);await realtime();clearInterval(poll);poll=setInterval(()=>pull(false),10000);if($('privacyText'))$('privacyText').textContent='已启用服务端 PIN 保护与四人实时同步。'}catch(e){pin='';sessionStorage.removeItem('cw-cloud-pin');if($('privacyText'))$('privacyText').textContent='PIN 验证失败，请重试。';alert(e.message)}}
async function expenseSubmit(e){e.preventDefault();e.stopImmediatePropagation();if(!pin){$('privacyModal')?.classList.add('show');return}const amount=Number($('amount')?.value),ps=[...($('participants')?.querySelectorAll('input:checked')||[])].map(x=>x.value);if(!(amount>0)||!ps.length)return alert('请填写金额并至少选择一位参与者');const payload={category:$('category').value,amount,payer:$('payer').value,participants:ps,note:$('expenseNote').value||$('category').value,status:'paid'};try{await api('add_expense',payload);send('ledger',{by:payload.payer});await pull();e.target.reset();if(typeof participantsUI==='function')participantsUI()}catch(err){alert(err.message)}}
async function repaySubmit(e){e.preventDefault();e.stopImmediatePropagation();if(!pin){$('privacyModal')?.classList.add('show');return}const amount=Number($('settleAmount')?.value),from=$('settleFrom')?.value,to=$('settleTo')?.value;if(!(amount>0)||from===to)return;try{await api('add_repayment',{from_person:from,to_person:to,amount,note:$('settleNote').value||'AA还款'});send('ledger',{from,to});await pull();e.target.reset()}catch(err){alert(err.message)}}
function stopLocalGps(){try{if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}}catch(e){}}
function cloudGps(){if(!pin){$('privacyModal')?.classList.add('show');return}if(watchId!==null){stopLocalGps();if($('locateBtn'))$('locateBtn').textContent='⌖ 开始定位';if($('driveLocate'))$('driveLocate').textContent='⌖ 开始定位';if($('vehicleState'))$('vehicleState').textContent='已暂停';return}if(!window.isSecureContext||!navigator.geolocation){if($('gpsText'))$('gpsText').textContent='定位需要 HTTPS 和浏览器授权';return}watchId=navigator.geolocation.watchPosition(p=>{const c=p.coords,pt={lat:c.latitude,lon:c.longitude,time:p.timestamp,acc:c.accuracy,speed:c.speed,heading:c.heading};lastGps=pt;try{const prev=gpsTrack.at(-1);if(!prev||hav(prev.lat,prev.lon,pt.lat,pt.lon)>.03||pt.time-prev.time>15000){gpsTrack.push(pt);if(gpsTrack.length>6000)gpsTrack=gpsTrack.slice(-6000);localStorage.setItem('cw-track-v3',JSON.stringify(gpsTrack));gpsLayer?.setLatLngs(gpsTrack.map(x=>[x.lat,x.lon]))}if(map){if(!map.hasLayer(carMarker))carMarker.addTo(map);carMarker.setLatLng([pt.lat,pt.lon]);map.panTo([pt.lat,pt.lon])}}catch(e){}if(Date.now()-lastPush>4000){lastPush=Date.now();api('update_vehicle',{lat:pt.lat,lon:pt.lon,accuracy:pt.acc,speed:pt.speed,heading:pt.heading,updated_by:'辉子'}).then(()=>send('vehicle',{...pt,updated_by:'辉子',updated_at:new Date().toISOString()})).catch(()=>{})}if($('locateBtn'))$('locateBtn').textContent='■ 暂停定位';if($('driveLocate'))$('driveLocate').textContent='■ 暂停定位';if($('vehicleState'))$('vehicleState').textContent='实时追踪';if($('gpsText'))$('gpsText').textContent=`GPS ±${Math.round(c.accuracy)}m${Number.isFinite(c.speed)?' · '+Math.round(c.speed*3.6)+'km/h':''}`;if(typeof render==='function')render()},e=>{if($('gpsText'))$('gpsText').textContent=e.code===1?'定位权限被拒绝':'GPS 暂时不可用'},{enableHighAccuracy:true,maximumAge:1500,timeout:15000})}
async function cloudPhoto(){if(!pin){$('privacyModal')?.classList.add('show');return}const files=[...($('photoInput')?.files||[])],caption=$('photoCaption')?.value||'';if(!files.length)return;for(const f of files){try{const data=await compressImage(f);await api('upload_photo',{data_url:data,caption,uploaded_by:'瑞子'})}catch(e){alert('照片上传失败：'+e.message);return}}send('memory',{by:'瑞子'});await pull();if($('photoInput'))$('photoInput').value='';if($('photoCaption'))$('photoCaption').value=''}
function hook(){syncLabel();if($('privacyText'))$('privacyText').textContent='精确GPS、AA账本和共享纪念册已启用服务端 PIN 保护。输入旅行 PIN 后才会从云端读取。';if($('unlockPrivacy'))$('unlockPrivacy').onclick=unlockCloud;if($('cloudBtn'))$('cloudBtn').onclick=()=>$('privacyModal')?.classList.add('show');if($('privacyBtn'))$('privacyBtn').onclick=()=>$('privacyModal')?.classList.add('show');$('expenseForm')?.addEventListener('submit',expenseSubmit,true);$('settleForm')?.addEventListener('submit',repaySubmit,true);if($('locateBtn'))$('locateBtn').onclick=cloudGps;if($('driveLocate'))$('driveLocate').onclick=cloudGps;if($('savePhotos'))$('savePhotos').onclick=cloudPhoto;if(pin){privateUnlocked=true;if(typeof applyPrivacy==='function')applyPrivacy();pull(true).then(realtime);poll=setInterval(()=>pull(false),10000)}}
setTimeout(hook,0);
})();