(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const FN='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync',TRIP='chuanxi2026';
const $=s=>document.querySelector(s);let state=null,pos=null,wx=null,watch=null,gateReady=false,gateTimer=null;
const WX={0:'晴',1:'大致晴',2:'多云',3:'阴',45:'雾',48:'雾',51:'毛毛雨',53:'毛毛雨',55:'毛毛雨',61:'小雨',63:'中雨',65:'大雨',71:'小雪',73:'中雪',75:'大雪',80:'阵雨',81:'阵雨',82:'强阵雨',95:'雷暴'};
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function cnDate(){return new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})}
function dayIndex(){const d=cnDate(),dates=['2026-10-02','2026-10-03','2026-10-04','2026-10-05','2026-10-06','2026-10-07'],i=dates.indexOf(d);if(i>=0)return i;if(d<'2026-10-02')return-1;return 6}
function task(){const i=dayIndex(),pre={瑞子:'核对酒店订单、四姑娘山住宿和公共账本。',普子:'复核国庆路况、行程时间和景区预约信息。',航子:'核对往返航班、证件和行李安排。',辉子:'确认租车车型、取还车规则和车辆保障。'},after={瑞子:'整理最终账本和住宿票据。',普子:'整理路线与攻略记录。',航子:'整理航班与交通凭证。',辉子:'核对还车记录和车辆费用。'},T={瑞子:['确认雅安酒店晚到信息。','关注大家状态并确认新都桥入住。','确认中路藏寨停车与入住。','确认四姑娘山住宿最终订单。','返程优先，确认机场酒店。','核对退房和最终账本。'],普子:['盯机场到雅安路况。','复核泸定—康定—折多山路况和天气。','复核塔公—八美—丹巴道路。','确认双桥沟开放和预约。','盯导航拥堵，必要时取消停留。','确认还车点到航站楼动线。'],航子:['确认四个人行李齐全。','提醒补水保暖并关注设备电量。','关注天气、证件和设备。','景区准备水和充电宝。','关注返程航班动态。','确认值机和航班。'],辉子:['取车验车并拍照。','关注油量、胎压并及时加油。','每2小时确认油量胎压和休息。','丹巴/小金及时补油。','05:30准时出发并补油。','按规则还车并留存照片。']};return i<0?pre[ME]:i>5?after[ME]:T[ME][i]}
function api(){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);return fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action:'get_state',payload:{}}),signal:c.signal}).then(async r=>{clearTimeout(t);if(!r.ok)throw new Error('sync');return r.json()}).catch(()=>null)}
function paidExpenses(){return(state?.expenses||[]).filter(e=>e.status!=='budget')}
function plan(){const b=Object.fromEntries(TEAM.map(p=>[p,0]));for(const e of paidExpenses()){const ps=e.participants?.length?e.participants:TEAM,share=Number(e.amount||0)/ps.length;b[e.payer]=(b[e.payer]||0)+Number(e.amount||0);ps.forEach(p=>b[p]=(b[p]||0)-share)}for(const r of state?.repayments||[]){b[r.from_person]=(b[r.from_person]||0)+Number(r.amount||0);b[r.to_person]=(b[r.to_person]||0)-Number(r.amount||0)}const debt=TEAM.filter(p=>b[p]<-.005).map(p=>({p,v:-b[p]})).sort((a,b)=>b.v-a.v),cred=TEAM.filter(p=>b[p]>.005).map(p=>({p,v:b[p]})).sort((a,b)=>b.v-a.v),out=[];let i=0,j=0;while(i<debt.length&&j<cred.length){const a=Math.min(debt[i].v,cred[j].v);out.push({from:debt[i].p,to:cred[j].p,amount:Math.round(a*100)/100});debt[i].v-=a;cred[j].v-=a;if(debt[i].v<.005)i++;if(cred[j].v<.005)j++}return out}
function financeLines(){if(!state)return[];const p=plan(),lines=[];p.filter(x=>x.to===ME).forEach(x=>lines.push(`应收 ${x.from} ${money(x.amount)}`));p.filter(x=>x.from===ME).forEach(x=>lines.push(`应付 ${x.to} ${money(x.amount)}`));return lines}
function place(lat,lon){const dom=$('#nowPlace')?.textContent?.trim();if(dom&&dom!=='等待定位'&&dom!=='实时位置')return dom;if(lat>39.3&&lat<41.2&&lon>115.6&&lon<117.6)return'北京市';if(lat>30.3&&lat<31.3&&lon>103.5&&lon<105.2)return'成都周边';if(lat>29.7&&lat<30.4&&lon>101.4&&lon<102.3)return'康定 / 新都桥一带';if(lat>30.5&&lat<31.2&&lon>101.5&&lon<102.3)return'丹巴一带';if(lat>30.8&&lat<31.3&&lon>102.5&&lon<103.2)return'四姑娘山一带';return'当前位置'}
function dress(w){if(!w)return'天气加载后给出建议';const x=Math.min(w.temperature_2m,w.apparent_temperature);let s=x<=0?'羽绒服 + 保暖层':x<=8?'厚外套/薄羽绒 + 长裤':x<=15?'外套 + 长袖，早晚加一层':x<=22?'长袖或薄外套':'短袖为主，随身带薄外套';if((w.precipitation||0)>0)s+='，带雨具';if((w.wind_speed_10m||0)>=30)s+='，注意防风';return s}
async function weather(lat,lon){const key=`cw-daily-wx-${lat.toFixed(2)}-${lon.toFixed(2)}`;try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Date.now()-c.saved<10*60*1000)return c.data}catch(e){}const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,precipitation,wind_speed_10m&timezone=auto`;const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),8000);try{const r=await fetch(u,{signal:ac.signal});if(!r.ok)throw new Error('wx');const j=await r.json(),d=j.current;localStorage.setItem(key,JSON.stringify({saved:Date.now(),data:d}));return d}finally{clearTimeout(tm)}}
function avatarUrl(){const el=$('#homeAvatar')||$('#profileAvatar');if(!el)return'';const bg=getComputedStyle(el).backgroundImage||el.style.backgroundImage||'',m=bg.match(/url\(["']?(.*?)["']?\)/);return m?m[1]:''}
function profile(){return(state?.profiles||[]).find(x=>x.person===ME)||{nickname:ME,role:''}}
function ensure(){if($('#cwDailyCard'))return;const ov=document.createElement('div');ov.id='cwDailyCard';ov.className='cw-daily-overlay';ov.innerHTML='<div class="cw-daily-glass" role="dialog" aria-modal="true" aria-label="今日提醒"><button class="cw-daily-close" aria-label="关闭" disabled>×</button><div class="cw-daily-person"><div class="cw-daily-avatar" id="cwDailyAvatar"></div><div><span id="cwDailyDate"></span><h2 id="cwDailyName">今日提醒</h2><p id="cwDailyRole"></p></div></div><div id="cwDailyBody" class="cw-daily-body"><div class="cw-daily-loading">正在加载今天的信息…</div></div><button class="cw-daily-ok" disabled>3秒后可关闭</button></div>';document.body.appendChild(ov);const close=()=>{if(!gateReady)return;ov.classList.remove('show');localStorage.setItem(`cw-daily-brief-${ME}-${cnDate()}`,'1');if(watch!=null&&navigator.geolocation){navigator.geolocation.clearWatch?.(watch);watch=null}};ov.querySelector('.cw-daily-close').onclick=close;ov.querySelector('.cw-daily-ok').onclick=close}
function startGate(){ensure();gateReady=false;clearInterval(gateTimer);let left=3;const ov=$('#cwDailyCard'),close=ov.querySelector('.cw-daily-close'),ok=ov.querySelector('.cw-daily-ok');close.disabled=true;ok.disabled=true;ov.classList.add('locked');const paint=()=>{ok.textContent=left>0?`${left}秒后可关闭`:'知道了';if(left<=0){gateReady=true;close.disabled=false;ok.disabled=false;ov.classList.remove('locked');clearInterval(gateTimer);gateTimer=null;return}left--};paint();gateTimer=setInterval(paint,1000)}
function render(){ensure();const body=$('#cwDailyBody'),pr=profile(),u=avatarUrl(),av=$('#cwDailyAvatar');av.style.backgroundImage=u?`url("${u.replace(/"/g,'%22')}")`:'';av.textContent=u?'':ME[0];$('#cwDailyDate').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});$('#cwDailyName').textContent=`${pr.nickname||ME}，今天注意这些`;$('#cwDailyRole').textContent=pr.role||'';const lines=[];for(const f of financeLines())lines.push(`<div class="cw-daily-line money"><i>¥</i><div><span>账本</span><b>${f}</b></div></div>`);if(pos&&wx){lines.push(`<div class="cw-daily-line"><i>☀</i><div><span>${place(pos.lat,pos.lon)} · 实时天气</span><b>${WX[wx.weather_code]||'天气'} ${Math.round(wx.temperature_2m)}℃ · 体感 ${Math.round(wx.apparent_temperature)}℃</b><small>风 ${Math.round(wx.wind_speed_10m||0)}km/h · GPS ±${Math.round(pos.accuracy||0)}m</small></div></div>`);lines.push(`<div class="cw-daily-line"><i>衣</i><div><span>穿衣</span><b>${dress(wx)}</b></div></div>`)}else lines.push('<div class="cw-daily-line"><i>◎</i><div><span>当前位置天气</span><b>正在获取 GPS 和天气…</b></div></div>');lines.push(`<div class="cw-daily-line task"><i>✓</i><div><span>今天的任务</span><b>${task()}</b></div></div>`);body.innerHTML=lines.join('')}
async function load(){ensure();state=await api();render();const use=async p=>{pos={lat:+p.coords.latitude,lon:+p.coords.longitude,accuracy:p.coords.accuracy,time:p.timestamp};render();try{wx=await weather(pos.lat,pos.lon);render()}catch(e){render()}};try{const c=JSON.parse(localStorage.getItem('cw-lastpos-v4')||'null');if(c&&Date.now()-(c.time||0)<2*60*60*1000){pos=c;render();wx=await weather(c.lat,c.lon).catch(()=>null);render()}}catch(e){}if(navigator.geolocation)watch=navigator.geolocation.watchPosition(use,()=>render(),{enableHighAccuracy:true,maximumAge:5000,timeout:12000})}
function open(force=false){if(!force&&localStorage.getItem(`cw-daily-brief-${ME}-${cnDate()}`)==='1')return;ensure();$('#cwDailyCard').classList.add('show');startGate();load()}
function maybe(){if(new URLSearchParams(location.search).get('qa')==='1')return;open(false)}
window.__cwDailyTestOpen=()=>open(true);
window.addEventListener('cw:profiles',()=>{if($('#cwDailyCard')?.classList.contains('show'))render()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(maybe,900),{once:true});else setTimeout(maybe,900);
})();