(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const TRIP='chuanxi2026';
const TRIP_API='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync';
const VOTE_API='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-vote';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const ROUTES=[
{date:'2026-10-02',route:'天府机场 → 雅安',hotel:'雅安空山云宿城市民宿',points:[['天府国际机场',30.312,104.441],['服务区',30.16,103.65],['雅安',29.98,103.00]]},
{date:'2026-10-03',route:'雅安 → 泸定 → 康定 → 折多山 → 新都桥',hotel:'上喜民宿（新都桥店）',points:[['雅安',29.98,103.00],['泸定',29.92,102.23],['康定',30.05,101.96],['折多山',30.06,101.80],['新都桥',30.04,101.49]]},
{date:'2026-10-04',route:'新都桥 → 塔公 → 八美 → 丹巴中路藏寨',hotel:'谷道山居（中路藏寨店）',points:[['新都桥',30.04,101.49],['塔公',30.32,101.54],['八美',30.55,101.50],['丹巴',30.88,101.89],['中路藏寨',30.89,101.92]]},
{date:'2026-10-05',route:'丹巴 → 小金 → 四姑娘山双桥沟',hotel:'四姑娘山景区住宿（待定）',points:[['丹巴',30.88,101.89],['小金',30.99,102.36],['双桥沟',31.09,102.84],['四姑娘山镇',31.10,102.89]]},
{date:'2026-10-06',route:'四姑娘山 → 卧龙 → 映秀 → 都江堰 → 天府机场',hotel:'天府云朵酒店（天府国际机场店）',points:[['四姑娘山镇',31.10,102.89],['卧龙',31.04,103.18],['映秀',31.06,103.48],['都江堰',31.00,103.62],['天府国际机场',30.312,104.441]]},
{date:'2026-10-07',route:'机场酒店 → 还车 → 航站楼',hotel:'返程',points:[['机场酒店',30.30,104.44],['还车点',30.31,104.43],['天府国际机场',30.312,104.441]]}
];
const PHOTO={
'折多山':{tags:['男生','多人','风景','背影'],stay:20,poses:[['自然走路','身体侧45°，不要直视镜头；一只手插口袋，摄影者开启连拍。','2X优先 · 人物距镜头4–6米 · 曝光-0.3'],['背影看山','人物占画面约1/4，把山脊和天空留出来；不要站在车道边。','1X或2X · 人物放三分线 · Live Photo开启'],['靠车抓拍','人不要正对镜头，靠车侧站，视线看远处；先确认停车安全。','2X · 略低机位 · 连拍']]},
'新都桥':{tags:['男生','情侣','多人','氛围感'],stay:35,poses:[['自然走路','沿安全步道或空旷区域走动，身体侧45°，眼睛看前方。','2X · 曝光-0.3 · 连拍'],['路边层次','人物放画面1/3，前景留草木，背景保留山体和道路纵深。','2X · 镜头略低 · 人距镜头5–8米'],['背影','适合不喜欢面对镜头的人，人物不要太大，留更多环境。','1X · 人物占1/4 · 锁定曝光']]},
'塔公':{tags:['男生','多人','风景','人文'],stay:30,poses:[['草原行走','侧身走，不看镜头；人物与地平线错开，避免头顶压山线。','2X · 连拍 · 曝光-0.3'],['远景小人','人放三分线，人物占画面1/5到1/4，强调草原尺度。','1X · 低机位少量 · 保留天空'],['站姿抓拍','双脚自然错开，一手插袋，视线看向侧前方。','2X · 人距镜头4–6米']]},
'中路藏寨':{tags:['男生','建筑','人文','背影'],stay:40,poses:[['巷道行走','沿建筑线条走，身体侧45°，利用墙体做引导线。','2X · 人物放1/3 · 曝光-0.3'],['靠墙','肩部轻靠墙，不要整个人贴墙；摄影者略低机位。','2X · 人距镜头3–5米'],['建筑背影','让人物看向碉楼或村落，人物小一些，背景多一些。','1X · 人物占1/4']]},
'双桥沟':{tags:['男生','风景','背影','多人'],stay:45,poses:[['湖边背影','人物站安全区域，背对镜头看山；不要跨越景区护栏。','1X · 人物占1/5 · 保留倒影'],['走路抓拍','自然走动，不直视镜头，连续拍5–10张选动作。','2X · 连拍 · 曝光-0.3'],['四人合影','四个人不要站一条直线，可前后错半步，留出雪山背景。','1X · 摄影者后退 · 避免超广角边缘']]}
};
const ICON={food:'🍜',photo:'📸',scenic:'🌄',cafe:'☕',toilet:'🚻',fuel:'⛽',parking:'🅿️',hospital:'🏥',repair:'🔧',signal:'🚦'};
const LABEL={food:'吃什么',photo:'拍什么',scenic:'去哪里',cafe:'咖啡',toilet:'厕所',fuel:'加油',parking:'停车',hospital:'医院',repair:'修理厂',signal:'红绿灯'};
let routeGeom=null,routeCum=null,poiCache=[],poiLoadedAt=0,poiLoading=null,wx=null,wxLoadedAt=0,votes=[],remoteState=null,activeCategory='scenic',aheadKm=30,mapPoiLayer=null,mapFilter='all',leafletHooked=false;
function api(url,action,payload={},timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);return fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action,payload}),signal:c.signal}).then(async r=>{clearTimeout(t);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'网络请求失败');return j}).catch(e=>{clearTimeout(t);throw e})}
function toast(msg){const e=$('#toast');if(!e)return alert(msg);e.textContent=msg;e.classList.add('show');clearTimeout(e._d);e._d=setTimeout(()=>e.classList.remove('show'),2600)}
function hav(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function dayIndex(){const d=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),i=ROUTES.findIndex(x=>x.date===d);if(i>=0)return i;return new Date()<new Date('2026-10-02T00:00:00+08:00')?0:5}
function route(){return ROUTES[dayIndex()]}
function getLive(){try{return JSON.parse(localStorage.getItem('cw-lastpos-v4')||'null')}catch(e){return null}}
function ageText(ts){if(!ts)return'暂无更新';const s=Math.max(0,Math.round((Date.now()-ts)/1000));if(s<20)return'刚刚';if(s<60)return`${s}秒前`;const m=Math.round(s/60);if(m<60)return`${m}分钟前`;return`${Math.round(m/60)}小时前`}
function onTripRoute(pos=getLive()){if(!pos)return false;let best=Infinity;for(const r of ROUTES)for(const p of r.points)best=Math.min(best,hav(pos.lat,pos.lon,p[1],p[2]));return best<90}
function wgsToGcj(lat,lon){const PI=Math.PI,a=6378245,ee=.00669342162296594323;if(lon<72.004||lon>137.8347||lat<.8293||lat>55.8271)return[lat,lon];const tf=(x,y)=>-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x))+(20*Math.sin(6*x*PI)+20*Math.sin(2*x*PI))*2/3+(20*Math.sin(y*PI)+40*Math.sin(y/3*PI))*2/3+(160*Math.sin(y/12*PI)+320*Math.sin(y*PI/30))*2/3,tg=(x,y)=>300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x))+(20*Math.sin(6*x*PI)+20*Math.sin(2*x*PI))*2/3+(20*Math.sin(x*PI)+40*Math.sin(x/3*PI))*2/3+(150*Math.sin(x/12*PI)+300*Math.sin(x/30*PI))*2/3;let dLat=tf(lon-105,lat-35),dLon=tg(lon-105,lat-35),r=lat/180*PI,m=1-ee*Math.sin(r)**2,s=Math.sqrt(m);dLat=dLat*180/((a*(1-ee))/(m*s)*PI);dLon=dLon*180/(a/s*Math.cos(r)*PI);return[lat+dLat,lon+dLon]}
function amapNav(c){const[a,b]=wgsToGcj(c.lat,c.lon);return`https://uri.amap.com/navigation?to=${b.toFixed(6)},${a.toFixed(6)},${encodeURIComponent(c.name)}&mode=car&policy=1&src=chuanxi2026&coordinate=gaode&callnative=1`}
function amapSearch(q){const p=getLive();if(!p)return`https://uri.amap.com/search?keyword=${encodeURIComponent(q)}&callnative=1`;const[a,b]=wgsToGcj(p.lat,p.lon);return`https://uri.amap.com/search?keyword=${encodeURIComponent(q)}&center=${b.toFixed(6)},${a.toFixed(6)}&callnative=1`}
async function loadRouteGeom(){if(routeGeom)return routeGeom;const r=route();try{const j=await fetch('./road-routes.json',{cache:'force-cache'}).then(x=>x.json()),raw=j?.[String(dayIndex())]?.coordinates;if(raw?.length)routeGeom=raw.map(x=>[x[1],x[0]])}catch(e){}if(!routeGeom)routeGeom=r.points.map(p=>[p[1],p[2]]);routeCum=[0];for(let i=1;i<routeGeom.length;i++)routeCum[i]=routeCum[i-1]+hav(routeGeom[i-1][0],routeGeom[i-1][1],routeGeom[i][0],routeGeom[i][1]);return routeGeom}
function nearestIndex(lat,lon,geom=routeGeom){let bi=0,bd=Infinity;if(!geom)return{index:0,dist:Infinity};for(let i=0;i<geom.length;i++){const d=hav(lat,lon,geom[i][0],geom[i][1]);if(d<bd){bd=d;bi=i}}return{index:bi,dist:bd}}
function avgSpeed(){const d=dayIndex();return d===4?38:d===1?42:d===5?35:45}
async function routeMetrics(c){await loadRouteGeom();const p=getLive(),stay=Number(c.stay||20);if(!p)return{direct:0,dev:0,along:0,detour:0,detourMin:0,etaMin:0,routeScore:70,onRoute:false,ahead:true,total:stay};const cur=nearestIndex(p.lat,p.lon),poi=nearestIndex(c.lat,c.lon),direct=hav(p.lat,p.lon,c.lat,c.lon),onRoute=cur.dist<20,ahead=poi.index>=cur.index-3,along=onRoute?routeCum[poi.index]-routeCum[cur.index]:direct,dev=poi.dist,speed=avgSpeed();let detour=onRoute?dev*2:direct,back=onRoute&&!ahead?Math.abs(along)*2:0;detour+=back;const detourMin=detour/speed*60,etaMin=(onRoute&&ahead?Math.max(0,along):direct)/speed*60+dev/speed*60,routeScore=onRoute?clamp(100-detourMin*1.15-dev*3-(ahead?0:35),10,100):clamp(92-direct*4,20,92);return{direct,dev,along:Math.max(0,along),detour,detourMin,etaMin,routeScore,onRoute,ahead,total:detourMin+stay}}
async function weatherNow(){const p=getLive();if(!p)return null;if(wx&&Date.now()-wxLoadedAt<15*60000)return wx;const key=`cw-decision-wx-${p.lat.toFixed(2)}-${p.lon.toFixed(2)}`;try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&current=temperature_2m,apparent_temperature,weather_code,cloud_cover,precipitation&hourly=precipitation_probability,cloud_cover,weather_code&daily=sunrise,sunset&timezone=Asia%2FShanghai&forecast_days=2`,c=new AbortController(),t=setTimeout(()=>c.abort(),6500),j=await fetch(u,{signal:c.signal}).then(r=>r.json());clearTimeout(t);wx=j;wxLoadedAt=Date.now();localStorage.setItem(key,JSON.stringify({t:wxLoadedAt,j}));return wx}catch(e){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x?.j){wx=x.j;wxLoadedAt=x.t;return wx}}catch(_){}return null}}
function sunsetDate(){const s=wx?.daily?.sunset?.[0];return s?new Date(s):null}
function countdownSunset(){const s=sunsetDate();if(!s)return'等待天气数据';const m=Math.round((s-Date.now())/60000);if(m>=60)return`${Math.floor(m/60)}小时${m%60}分`;if(m>=0)return`${m}分钟`;return`已日落 ${Math.abs(m)}分钟`}
function lightScore(c){const s=sunsetDate();if(!s)return 70;const eta=Date.now()+(c.metrics?.etaMin||0)*60000,d=(s-eta)/60000;if(c.category==='photo'||c.category==='scenic'){if(d>=20&&d<=100)return 96;if(d>100&&d<=180)return 84;if(d>=-15&&d<20)return 76;if(d< -15)return 35;return 68}return d<-90?65:82}
function weatherScore(c){if(!wx?.current)return 72;const code=Number(wx.current.weather_code),cloud=Number(wx.current.cloud_cover||0),bad=[65,75,82,95].includes(code);if(bad)return 35;if(c.category==='photo'||c.category==='scenic'){if(cloud>=20&&cloud<=70)return 92;if(cloud<20)return 82;return 68}return 82}
function costScore(c){const t=c.metrics?.total||c.stay||20;return clamp(100-t*.9,25,95)}
function interestScore(c){return 75}
function parkingScore(c){if(c.category==='parking')return 98;if(c.tags?.parking==='yes'||c.tags?.parking==='surface')return 86;return c.parkingScore||58}
function scenicScore(c){return c.value||((c.category==='photo'||c.category==='scenic')?82:68)}
function crowdScore(c){return c.crowd||68}
function worth(c){if(['toilet','fuel','hospital','repair','parking'].includes(c.category)){const near=clamp(100-(c.metrics?.direct||0)*8,20,100);return Math.round(.58*(c.metrics?.routeScore||70)+.30*near+.12*75)}return Math.round(.25*(c.metrics?.routeScore||70)+.15*weatherScore(c)+.15*lightScore(c)+.15*scenicScore(c)+.10*parkingScore(c)+.10*interestScore(c)+.05*costScore(c)+.05*crowdScore(c))}
function internalCandidates(){const r=route(),out=[];for(let i=1;i<r.points.length-1;i++){const p=r.points[i],g=PHOTO[p[0]];out.push({id:`route-${dayIndex()}-${i}`,name:p[0],lat:p[1],lon:p[2],category:g?'photo':'scenic',stay:g?.stay||25,value:g?90:78,parkingScore:58,source:'今日真实路线',photoGuide:g||null})}return out}
function genericName(cat,tags={}){return tags['name:zh']||tags.name||tags.brand||({food:'沿途餐厅',cafe:'沿途咖啡',toilet:'公共厕所',fuel:'加油站',parking:'停车点',hospital:'医院',repair:'汽车维修',scenic:'观景点',signal:'红绿灯'}[cat]||'沿途地点')}
function catFrom(tags={}){if(tags.highway==='traffic_signals')return'signal';if(tags.amenity==='restaurant'||tags.amenity==='fast_food')return'food';if(tags.amenity==='cafe')return'cafe';if(tags.amenity==='toilets')return'toilet';if(tags.amenity==='fuel')return'fuel';if(tags.amenity==='parking')return'parking';if(tags.amenity==='hospital'||tags.amenity==='clinic')return'hospital';if(tags.shop==='car_repair'||tags.amenity==='car_repair')return'repair';if(tags.tourism==='viewpoint'||tags.tourism==='attraction')return'scenic';return null}
async function loadPois(force=false){const p=getLive();if(!p)return[];if(!force&&poiCache.length&&Date.now()-poiLoadedAt<30*60000)return poiCache;if(poiLoading)return poiLoading;poiLoading=(async()=>{const radius=onTripRoute(p)?35000:7000,key=`cw-poi-${p.lat.toFixed(2)}-${p.lon.toFixed(2)}-${radius}`;const q=`[out:json][timeout:10];(nwr(around:${radius},${p.lat},${p.lon})["amenity"~"restaurant|fast_food|cafe|toilets|fuel|hospital|clinic|parking"];nwr(around:${radius},${p.lat},${p.lon})["shop"="car_repair"];nwr(around:${radius},${p.lat},${p.lon})["tourism"~"viewpoint|attraction"];node(around:${Math.min(radius,12000)},${p.lat},${p.lon})["highway"="traffic_signals"];);out center tags 160;`;const endpoints=['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter'];for(const ep of endpoints){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),9000),body=new URLSearchParams({data:q}),j=await fetch(ep,{method:'POST',body,signal:c.signal}).then(r=>r.json());clearTimeout(t);const arr=[];for(const e of j.elements||[]){const tags=e.tags||{},cat=catFrom(tags);if(!cat)continue;const lat=Number(e.lat??e.center?.lat),lon=Number(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;arr.push({id:`osm-${e.type}-${e.id}`,name:genericName(cat,tags),lat,lon,category:cat,stay:{food:60,cafe:30,toilet:8,fuel:12,parking:5,hospital:20,repair:30,scenic:25,signal:0}[cat]||20,value:cat==='scenic'?80:65,tags,source:'公开地图POI'})}poiCache=arr;poiLoadedAt=Date.now();localStorage.setItem(key,JSON.stringify({t:poiLoadedAt,items:arr}));return arr}catch(e){}}
try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x?.items?.length){poiCache=x.items;poiLoadedAt=x.t||0;return poiCache}}catch(e){}return[]})().finally(()=>{poiLoading=null});return poiLoading}
async function enrichCandidates(list){await Promise.all(list.map(async c=>{c.metrics=await routeMetrics(c);c.score=worth(c);c.eta=new Date(Date.now()+c.metrics.etaMin*60000)}));return list}
function reasonFor(c){const a=[];if(c.metrics?.onRoute){if(c.metrics.routeScore>=90)a.push('✅ 基本顺路');else if(c.metrics.routeScore>=70)a.push('✅ 绕路成本可控');else a.push('⚠️ 绕路较明显')}else a.push('ℹ️ 当前尚未进入今日川西路线');if((c.category==='photo'||c.category==='scenic')&&sunsetDate()){const mins=Math.round((sunsetDate()-c.eta)/60000);if(mins>25)a.push(`✅ 预计抵达后距日落约${mins}分钟`);else if(mins>=0)a.push(`⚠️ 抵达后距日落仅约${mins}分钟`);else a.push('❌ 预计抵达时已日落')}if(wx?.current){const rain=Number(wx.current.precipitation||0);a.push(rain>0?'⚠️ 当前有降水':'✅ 当前无明显降水')}if(c.category==='fuel')a.push(remoteState?.trip_state?.fuel_level==null?'ℹ️ 未录入车辆油量，不虚构续航':'✅ 已结合当前油量');if(c.category==='food')a.push(c.tags?.opening_hours?'ℹ️ 有营业时间标签，仍建议到店前确认':'ℹ️ 未拿到可靠营业状态，需导航前确认');return a.slice(0,4)}
function metaHtml(c){const m=c.metrics||{};return`<div class="best-meta"><span>${m.direct.toFixed(1)}km</span>${m.onRoute?`<span class="${m.dev<=1.5?'good':m.dev>5?'bad':''}">偏离路线 ${m.dev.toFixed(1)}km</span><span class="${m.detourMin<=10?'good':m.detourMin>30?'bad':''}">估算绕路 +${Math.round(m.detourMin)}分钟</span>`:'<span>未进入今日路线</span>'}<span>建议停留 ${c.stay||20}分钟</span><span>顺路指数 ${Math.round(m.routeScore||0)}%</span></div>`}
function cardHtml(c,compact=false){return`<div class="best-card" data-cid="${esc(c.id)}"><div class="best-top"><div class="best-name"><b>${ICON[c.category]||'📍'} ${esc(c.name)}</b><p>${esc(c.source||'系统建议')} · 预计${c.eta?c.eta.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—'}到</p></div><div class="worth"><span>现在值得去</span><b>${c.score||'—'}</b></div></div>${metaHtml(c)}${compact?'':`<div class="reason-list">${reasonFor(c).map(x=>`<div>${esc(x)}</div>`).join('')}</div><div class="card-actions"><a class="primary" href="${amapNav(c)}" target="_blank">导航</a><button data-set-next="${esc(c.id)}">设为下一站</button><button data-vote-place="${esc(c.id)}">四人投票</button>${c.category==='photo'||c.photoGuide?`<button data-photo-guide="${esc(c.id)}">拍照攻略</button>`:''}</div>`}</div>`}
function findCandidate(id){return window.__cwCandidates?.find(x=>x.id===id)||null}
async function candidatesFor(cat){let base=internalCandidates();if(['food','cafe','toilet','fuel','parking','hospital','repair','scenic'].includes(cat)){const ps=await loadPois();base=cat==='scenic'?[...base.filter(x=>x.category==='scenic'||x.category==='photo'),...ps.filter(x=>x.category==='scenic')]:ps.filter(x=>x.category===cat)}else if(cat==='photo')base=base.filter(x=>x.category==='photo'||x.category==='scenic');const out=await enrichCandidates(base.slice(0,80));out.sort((a,b)=>b.score-a.score);window.__cwCandidates=[...(window.__cwCandidates||[]).filter(x=>!out.some(y=>y.id===x.id)),...out];return out}
async function bestNow(){const base=internalCandidates();const p=getLive();if(onTripRoute(p)){const e=await enrichCandidates(base);return e.filter(x=>x.metrics.ahead).sort((a,b)=>b.score-a.score).slice(0,3)}const ps=poiCache.length?poiCache.filter(x=>['food','cafe','scenic'].includes(x.category)).slice(0,15):[];if(ps.length){const e=await enrichCandidates(ps);return e.sort((a,b)=>b.score-a.score).slice(0,3)}return[]}
async function routeSummary(){await loadRouteGeom();const p=getLive(),r=route(),s={route:r.route,next:'等待GPS',dist:null,eta:null,hotelEta:null,night:null};if(!p)return s;const cur=nearestIndex(p.lat,p.lon),on=cur.dist<20;if(!on){s.next='尚未进入今日路线';return s}let nextPoint=null,nextIndex=null;for(let i=0;i<r.points.length;i++){const q=nearestIndex(r.points[i][1],r.points[i][2]);if(q.index>cur.index+2){nextPoint=r.points[i];nextIndex=q.index;break}}if(!nextPoint){nextPoint=r.points.at(-1);nextIndex=routeGeom.length-1}const dist=Math.max(0,routeCum[nextIndex]-routeCum[cur.index]),remain=Math.max(0,routeCum.at(-1)-routeCum[cur.index]),speed=avgSpeed();s.next=nextPoint[0];s.dist=dist;s.eta=new Date(Date.now()+dist/speed*3600000);s.hotelEta=new Date(Date.now()+remain/speed*3600000);const sunset=sunsetDate();if(sunset&&s.hotelEta>sunset)s.night=Math.round((s.hotelEta-sunset)/60000);return s}
async function renderHub(){const hub=$('#decisionHub');if(!hub)return;const p=getLive(),sum=await routeSummary(),best=await bestNow(),s=sunsetDate(),gpsAge=p?.time?ageText(p.time):'暂无',wxAge=wxLoadedAt?ageText(wxLoadedAt):'暂无';$('#decisionPlace').textContent=p?($('#nowPlace')?.textContent||'实时位置'):'等待GPS';$('#decisionTime').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});$('#sunsetText').textContent=s?`距日落 ${countdownSunset()}`:'日落数据加载中';$('#decRoute').textContent=sum.route;$('#decNext').textContent=sum.next+(sum.dist!=null?` · ${sum.dist.toFixed(0)}km`:'');$('#decEta').textContent=sum.eta?sum.eta.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—';$('#decHotel').textContent=sum.hotelEta?sum.hotelEta.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—';$('#decHotelBox').classList.toggle('warn',!!sum.night);$('#decHotelBox').title=sum.night?`预计有约${sum.night}分钟日落后山路`:'按路线距离估算';$('#bestNow').innerHTML=best.length?best.map(x=>cardHtml(x)).join(''):`<div class="empty">${p&&!onTripRoute(p)?'当前不在川西路线附近；附近餐饮、咖啡、厕所等会按当前GPS查询。':'正在等待实时位置与路线数据。'}</div>`;$('#decisionFresh').textContent=`GPS：${gpsAge} · 天气：${wxAge}${poiLoadedAt?` · 附近设施：${ageText(poiLoadedAt)}`:''}。ETA和绕路时间为道路几何+山路平均速度估算，真正导航以高德为准。`;$('#decisionFresh').classList.toggle('stale',p?.time&&Date.now()-p.time>180000);renderVoteBox();renderAhead()}
async function renderAhead(){const el=$('#aheadList');if(!el)return;if(!onTripRoute()){el.innerHTML='<div class="empty">进入川西今日路线后自动计算“前方10/30/50km”。</div>';return}await loadRouteGeom();let all=[...internalCandidates(),...poiCache.filter(x=>['fuel','toilet','food','cafe','parking','hospital','repair','scenic'].includes(x.category))];all=await enrichCandidates(all.slice(0,100));const rows=all.filter(x=>x.metrics.onRoute&&x.metrics.ahead&&x.metrics.along<=aheadKm&&x.metrics.dev<=5).sort((a,b)=>a.metrics.along-b.metrics.along).slice(0,6);window.__cwCandidates=[...(window.__cwCandidates||[]),...rows];el.innerHTML=rows.length?rows.map(c=>`<div class="ahead-row"><div class="ahead-ico">${ICON[c.category]||'📍'}</div><div><b>前方 ${Math.max(0,c.metrics.along).toFixed(0)}km · ${esc(c.name)}</b><p>偏离道路约${c.metrics.dev.toFixed(1)}km · 估算多花${Math.round(c.metrics.detourMin)}分钟</p></div><button data-open-candidate="${esc(c.id)}">查看</button></div>`).join(''):'<div class="empty">这个范围内暂时没有拿到可靠沿途设施；可点上方“厕所/加油/吃什么”直接查询。</div>'}
function installHub(){const v=$('#view-now'),anchor=v?.querySelector('.now-card');if(!v||!anchor||$('#decisionHub'))return;const s=document.createElement('section');s.id='decisionHub';s.className='card decision-card';s.innerHTML=`<div class="decision-loc"><div><span class="eyebrow">当前位置 · 附近灵感</span><h2 id="decisionPlace">等待GPS</h2><p id="sunsetText">日落数据加载中</p></div><div class="decision-clock"><b id="decisionTime">--:--</b><span>北京时间</span></div></div><div class="decision-summary"><div><span>今日路线</span><b id="decRoute">—</b></div><div><span>下一站</span><b id="decNext">—</b></div><div><span>下一站 ETA</span><b id="decEta">—</b></div><div id="decHotelBox"><span>酒店 ETA</span><b id="decHotel">—</b></div></div><div class="quick-actions">${[['food','🍜','吃什么'],['photo','📸','拍什么'],['scenic','🌄','去哪里'],['cafe','☕','咖啡'],['toilet','🚻','厕所'],['fuel','⛽','加油']].map(x=>`<button class="quick-action" data-dec-cat="${x[0]}"><i>${x[1]}</i>${x[2]}</button>`).join('')}</div><button class="decide-now" id="helpDecide">⚡ 帮我们决定</button><div class="decision-section"><div class="decision-title"><h3>现在最值得</h3><span>只给1–3个答案</span></div><div id="bestNow" class="best-list"><div class="empty">正在结合路线与GPS…</div></div></div><div class="decision-section"><div class="decision-title"><h3>前方有什么</h3><span>按今日真实路线</span></div><div class="ahead-tabs"><button class="on" data-ahead="10">10km</button><button data-ahead="30">30km</button><button data-ahead="50">50km</button></div><div id="aheadList" class="ahead-list"></div></div><div id="voteHolder"></div><div id="decisionFresh" class="freshness"></div>`;anchor.insertAdjacentElement('afterend',s);const ov=document.createElement('div');ov.id='decisionOverlay';ov.className='decision-overlay';ov.innerHTML='<div class="decision-sheet"><div class="sheet-head"><div><h2 id="sheetTitle">现在去哪</h2><p id="sheetSub">根据当前位置、路线、天气与日落计算</p></div><button data-close-decision>×</button></div><div id="sheetFilters" class="sheet-filter"></div><div id="sheetBody" class="best-list"></div></div>';document.body.appendChild(ov)}
async function openDecision(cat){activeCategory=cat;const ov=$('#decisionOverlay');ov.classList.add('show');$('#sheetTitle').textContent=`${ICON[cat]||'⚡'} ${LABEL[cat]||'现在去哪'}`;$('#sheetSub').textContent='正在计算距离、偏离路线、绕路时间和“现在值得去指数”';$('#sheetBody').innerHTML='<div class="empty">正在读取当前位置与沿途数据…</div>';$('#sheetFilters').innerHTML=['food','photo','scenic','cafe','toilet','fuel'].map(x=>`<button class="${x===cat?'on':''}" data-sheet-cat="${x}">${ICON[x]} ${LABEL[x]}</button>`).join('');await weatherNow();let list=await candidatesFor(cat);if(cat==='toilet')list=list.slice(0,12);if(cat==='fuel')list=list.slice(0,12);window.__cwCandidates=[...(window.__cwCandidates||[]),...list];if(!list.length){const q={food:'餐厅',cafe:'咖啡',toilet:'公共厕所',fuel:'加油站',scenic:'景点',photo:'拍照打卡点'}[cat]||'附近';$('#sheetBody').innerHTML=`<div class="best-card"><div class="best-name"><b>暂时没有拿到可靠的附近数据</b><p>不会编造店铺、厕所或加油站。你可以直接用高德继续查。</p></div><div class="card-actions"><a class="primary" target="_blank" href="${amapSearch(q)}">打开高德搜索${esc(q)}</a></div></div>`;return}if(cat==='toilet')return renderToilet(list);if(cat==='fuel')return renderFuel(list);$('#sheetBody').innerHTML=list.slice(0,5).map(x=>cardHtml(x)).join('')}
function renderToilet(list){const p=getLive(),nearest=[...list].sort((a,b)=>a.metrics.direct-b.metrics.direct)[0],routeBest=[...list].sort((a,b)=>b.metrics.routeScore-a.metrics.routeScore)[0],forward=list.filter(x=>x.metrics.ahead).sort((a,b)=>a.metrics.along-b.metrics.along)[0],uniq=[nearest,routeBest,forward].filter((x,i,a)=>x&&a.findIndex(y=>y?.id===x.id)===i);$('#sheetBody').innerHTML=`<div class="best-card"><div class="best-name"><b>厕所雷达</b><p>优先给最近、最顺路、前方最近三个答案；公开地图数据可能不完整。</p></div></div>${uniq.map((x,i)=>`<div class="best-card"><div class="best-top"><div class="best-name"><b>${['最近','最顺路','前方最近'][i]||'推荐'} · ${esc(x.name)}</b><p>${x.metrics.direct.toFixed(1)}km · 偏离路线${x.metrics.dev.toFixed(1)}km</p></div><div class="worth"><span>顺路</span><b>${Math.round(x.metrics.routeScore)}</b></div></div><div class="card-actions"><a class="primary" href="${amapNav(x)}" target="_blank">直接导航</a></div></div>`).join('')}`}
function renderFuel(list){const fuel=remoteState?.trip_state?.fuel_level??localStorage.getItem('cw-fuel-manual'),best=[...list].sort((a,b)=>b.metrics.routeScore-a.metrics.routeScore)[0];$('#sheetBody').innerHTML=`<div class="best-card"><div class="best-name"><b>当前油量：${fuel==null?'未填写':esc(fuel)+'%'}</b><p>${fuel==null?'没有车辆平均续航数据，因此不虚构“还能跑多少公里”。先填油量，系统只做保守补给建议。':Number(fuel)<50?'油量低于50%，优先考虑前方顺路加油点。':'油量暂不紧张，仍建议山区保持半箱以上。'}</p></div><div class="card-actions"><button class="primary" id="setFuel">更新油量</button></div></div>${best?cardHtml(best):`<div class="best-card"><div class="best-name"><b>暂未获取到可靠加油站POI</b><p>不会编造站点位置。</p></div><div class="card-actions"><a class="primary" href="${amapSearch('加油站')}" target="_blank">高德查加油站</a></div></div>`}`;setTimeout(()=>$('#setFuel')?.addEventListener('click',updateFuel),0)}
async function updateFuel(){const old=remoteState?.trip_state?.fuel_level??localStorage.getItem('cw-fuel-manual')??'',v=prompt('输入当前油量百分比（0-100）',old);if(v==null)return;const n=Number(v);if(!Number.isFinite(n)||n<0||n>100)return toast('请输入0-100之间的数字');localStorage.setItem('cw-fuel-manual',String(Math.round(n)));try{await api(VOTE_API,'update_fuel',{person:ME,fuel_level:Math.round(n)});await loadRemoteState();toast('油量已同步')}catch(e){toast('油量已保存在本机，云端稍后再同步')}openDecision('fuel')}
function photoGuide(c){const g=c.photoGuide||{tags:['男生','风景','背影'],poses:[['自然走路','身体侧45度，不直视镜头，一只手插口袋，开启连拍。','2X · 曝光-0.3 · Live Photo开启'],['靠墙/栏杆','人物放画面1/3，手机略低机位，身体不要完全正对镜头。','2X · 人物距镜头4–6米'],['背影','人物占画面1/4，背景留更多环境，适合不喜欢面对镜头的人。','1X · 锁定曝光']]};const s=sunsetDate(),mins=s&&c.eta?Math.round((s-c.eta)/60000):null;$('#sheetTitle').textContent=`📸 ${c.name} · 怎么拍`;$('#sheetSub').textContent=`预计${c.eta?c.eta.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—'}到 · ${mins==null?'日落数据待加载':mins>=0?`距日落约${mins}分钟`:'预计日落后到达'}`;$('#sheetFilters').innerHTML=(g.tags||[]).map(x=>`<button class="on">${esc(x)}</button>`).join('');$('#sheetBody').innerHTML=`<div class="best-card"><div class="best-name"><b>到达与机位建议</b><p>绕路估算 +${Math.round(c.metrics?.detourMin||0)}分钟 · 建议停留${c.stay||30}分钟 · 停车条件请以现场合法停车区域为准。</p></div><div class="reason-list"><div>📱 iPhone：优先2X，人物离镜头4–6米，曝光可从-0.3开始微调。</div><div>🌅 ${mins!=null&&mins>=15&&mins<=100?'当前ETA处于较好的日落前拍摄窗口。':'请结合现场光线，系统不假设一定有金色日落。'}</div><div>🚗 任何拍摄都不要在弯道、主车道或禁停区域停车。</div></div></div><div class="photo-guide">${g.poses.map((x,i)=>`<article class="pose-card"><em>0${i+1}</em><h4>${esc(x[0])}</h4><p>${esc(x[1])}</p><p><b>设置：</b>${esc(x[2])}</p></article>`).join('')}</div>`}
async function setNext(c){if(!confirm(`把「${c.name}」设为下一站？\n确认后才会写入四人共享行程。`))return;try{await api(VOTE_API,'set_next_stop',{person:ME,name:c.name,lat:c.lat,lon:c.lon,source:'现在去哪'});toast('已设为四人共享下一站');await loadRemoteState();renderHub()}catch(e){toast('设置失败：'+e.message)}}
async function votePlace(c){try{const j=await api(VOTE_API,'create_vote',{person:ME,question:`现在去「${c.name}」吗？`,options:[{id:'yes',label:'去'},{id:'no',label:'不去'}],initial_option:'yes',context:{kind:'place',place:{id:c.id,name:c.name,lat:c.lat,lon:c.lon,category:c.category}}});votes=[j.row,...votes.filter(x=>x.id!==j.row.id)];renderVoteBox();toast('已发起投票，你已投“去”')}catch(e){toast(e.message)}}
async function castVote(id,opt){try{const j=await api(VOTE_API,'cast_vote',{person:ME,vote_id:id,option_id:opt});votes=votes.map(x=>x.id===id?j.row:x);renderVoteBox()}catch(e){toast(e.message)}}
function renderVoteBox(){const h=$('#voteHolder');if(!h)return;const v=votes.find(x=>x.status==='open');if(!v){h.innerHTML='';return}const ballots=v.ballots||{},opts=Array.isArray(v.options)?v.options:[],counts=Object.fromEntries(opts.map(o=>[o.id,0]));Object.values(ballots).forEach(x=>{if(counts[x]!=null)counts[x]++});const best=[...opts].sort((a,b)=>(counts[b.id]||0)-(counts[a.id]||0))[0],place=v.context?.place;h.innerHTML=`<div class="vote-box"><h4>🗳 ${esc(v.question)}</h4><div class="vote-options">${opts.map(o=>`<div class="vote-option"><div><b>${esc(o.label)}</b><span> · ${counts[o.id]||0}票 ${TEAM.filter(p=>ballots[p]===o.id).join(' / ')}</span></div><button data-cast-vote="${v.id}" data-opt="${esc(o.id)}">${ballots[ME]===o.id?'已投':'投票'}</button></div>`).join('')}</div><div class="vote-rec">${counts[best?.id]>=3?`已有${counts[best.id]}票，团队倾向：${esc(best.label)}`:'还没有形成3票多数'}</div>${place&&counts.yes>=3?`<div class="card-actions"><button class="primary" data-majority-next="1">确认设为下一站</button></div>`:''}</div>`;if(place)window.__cwVotePlace=place}
async function loadVotes(){try{const j=await api(VOTE_API,'list_votes',{});votes=j.votes||[];renderVoteBox()}catch(e){}}
async function loadRemoteState(){try{remoteState=await api(TRIP_API,'get_state',{},8500);return remoteState}catch(e){return remoteState}}
function installDecisionEvents(){document.addEventListener('click',e=>{const q=e.target.closest('[data-dec-cat]');if(q)openDecision(q.dataset.decCat);const sf=e.target.closest('[data-sheet-cat]');if(sf)openDecision(sf.dataset.sheetCat);if(e.target.closest('[data-close-decision]')||e.target===$('#decisionOverlay'))$('#decisionOverlay')?.classList.remove('show');const a=e.target.closest('[data-ahead]');if(a){aheadKm=Number(a.dataset.ahead);$$('[data-ahead]').forEach(x=>x.classList.toggle('on',x===a));renderAhead()}const oc=e.target.closest('[data-open-candidate]');if(oc){const c=findCandidate(oc.dataset.openCandidate);if(c){$('#decisionOverlay').classList.add('show');$('#sheetTitle').textContent='前方推荐';$('#sheetFilters').innerHTML='';$('#sheetBody').innerHTML=cardHtml(c)}}const n=e.target.closest('[data-set-next]');if(n){const c=findCandidate(n.dataset.setNext);if(c)setNext(c)}const v=e.target.closest('[data-vote-place]');if(v){const c=findCandidate(v.dataset.votePlace);if(c)votePlace(c)}const pg=e.target.closest('[data-photo-guide]');if(pg){const c=findCandidate(pg.dataset.photoGuide);if(c)photoGuide(c)}const cv=e.target.closest('[data-cast-vote]');if(cv)castVote(cv.dataset.castVote,cv.dataset.opt);if(e.target.closest('[data-majority-next]')&&window.__cwVotePlace)setNext(window.__cwVotePlace)});$('#helpDecide')?.addEventListener('click',async()=>{await weatherNow();let best=await bestNow();if(best[0]){window.__cwCandidates=[...(window.__cwCandidates||[]),...best];$('#decisionOverlay').classList.add('show');$('#sheetTitle').textContent='⚡ 帮我们决定';$('#sheetSub').textContent='只给最推荐和一个备选，减少继续研究的时间';$('#sheetFilters').innerHTML='';$('#sheetBody').innerHTML=`${cardHtml(best[0])}${best[1]?cardHtml(best[1]):''}`}else openDecision('food')})}
function installUnread(){const meView=$('#view-me'),ledger=$('#ledgerList');if(!meView||!ledger)return;let ctl=$('#unreadControl');if(!ctl){ctl=document.createElement('div');ctl.id='unreadControl';ctl.className='unread-control';ctl.innerHTML='<div><strong id="unreadStrong">有未读共同支出</strong><span id="unreadSub">点一下直接到第一条未读</span></div><div class="buttons"><button id="jumpUnread">查看未读</button><button class="readall" id="readAll">一键已读</button></div>';ledger.parentNode.insertBefore(ctl,ledger)}let syncing=false;const sync=()=>{if(syncing)return;syncing=true;requestAnimationFrame(()=>{const items=$$('#ledgerList .ledger-item'),unread=items.filter(x=>x.querySelector('[data-ledger="ack"]'));items.forEach(x=>x.classList.toggle('is-unread',unread.includes(x)));const n=unread.length;ctl.classList.toggle('show',n>0);$('#unreadStrong').textContent=n?`${n}条与我有关的未读`:'已全部读完';const pb=$('#pendingBadge');if(pb){pb.classList.toggle('hot',n>0);pb.textContent=n?`${n}笔未读 · 点我查看`:'0笔待确认'}const nb=$('#navBadge');if(nb){nb.textContent=n>99?'99+':String(n);nb.classList.toggle('show',n>0)}const tab=$('[data-ledgerview="mine"]');if(tab){tab.innerHTML=`与我有关${n?` <span class="unread-dot">${n}</span>`:''}`}syncing=false})};const jump=()=>{const meBtn=$('#bottomNav [data-view="me"]');if(meBtn&&!$('#view-me').classList.contains('on'))meBtn.click();setTimeout(()=>{sync();const first=$('#ledgerList .ledger-item.is-unread');if(first)first.scrollIntoView({behavior:'smooth',block:'center'});else toast('目前没有未读账单')},120)};$('#jumpUnread').onclick=jump;$('#pendingBadge')?.addEventListener('click',jump);$('#navBadge')?.addEventListener('click',()=>setTimeout(jump,80));$('#readAll').onclick=async()=>{const ids=$$('#ledgerList [data-ledger="ack"]').map(x=>x.dataset.id).filter(Boolean);if(!ids.length)return toast('已经全部读完');if(!confirm(`将 ${ids.length} 笔共同支出全部标记为已知晓？`))return;$('#readAll').disabled=true;try{for(const id of ids)await api(TRIP_API,'acknowledge_expense',{expense_id:id,person:ME});toast('已一键标记全部已读');document.dispatchEvent(new Event('visibilitychange'));setTimeout(sync,800)}catch(e){toast('一键已读失败：'+e.message)}finally{$('#readAll').disabled=false}};new MutationObserver(sync).observe(ledger,{childList:true,subtree:true});setInterval(sync,5000);sync()}
function hookLeaflet(){if(leafletHooked)return;leafletHooked=true;const wrap=L=>{if(!L||L.__cwDecisionWrapped)return L;const orig=L.map;L.map=function(...args){const m=orig.apply(this,args);if(args[0]==='fullMap'){window.__cwFullMap=m;setTimeout(enhanceMap,120)}return m};L.__cwDecisionWrapped=true;return L};if(window.L){wrap(window.L);return}try{let stash;Object.defineProperty(window,'L',{configurable:true,get(){return stash},set(v){stash=wrap(v);Object.defineProperty(window,'L',{value:stash,writable:true,configurable:true})}})}catch(e){}}
function installMapToolbar(){const shell=$('.map-shell');if(!shell||$('.map-rich-toolbar'))return;const bar=document.createElement('div');bar.className='map-rich-toolbar';bar.innerHTML=`${[['all','全部'],['fuel','⛽加油'],['toilet','🚻厕所'],['food','🍜餐饮'],['cafe','☕咖啡'],['parking','🅿️停车'],['hospital','🏥医院'],['repair','🔧修理'],['signal','🚦红绿灯']].map(x=>`<button class="${x[0]==='all'?'on':''}" data-map-filter="${x[0]}">${x[1]}</button>`).join('')}`;shell.appendChild(bar);const note=document.createElement('div');note.className='map-source-note';note.id='mapSourceNote';note.textContent='高德中文道路底图 · 附近设施按需加载；红绿灯/POI来自公开地图数据，可能不完整，实时路况以高德导航为准。';shell.appendChild(note);bar.onclick=e=>{const b=e.target.closest('[data-map-filter]');if(!b)return;mapFilter=b.dataset.mapFilter;$$('[data-map-filter]').forEach(x=>x.classList.toggle('on',x===b));loadPois().then(drawMapPois)} }
async function enhanceMap(){const m=window.__cwFullMap,L=window.L;if(!m||!L)return;installMapToolbar();if(!m.__cwControls){try{L.control.zoom({position:'bottomright'}).addTo(m);L.control.scale({imperial:false,position:'bottomleft'}).addTo(m)}catch(e){}m.__cwControls=1}await loadPois();drawMapPois()}
function drawMapPois(){const m=window.__cwFullMap,L=window.L;if(!m||!L)return;if(mapPoiLayer){try{mapPoiLayer.clearLayers()}catch(e){}}else mapPoiLayer=L.layerGroup().addTo(m);const p=getLive(),arr=poiCache.filter(x=>mapFilter==='all'||x.category===mapFilter).sort((a,b)=>p?hav(p.lat,p.lon,a.lat,a.lon)-hav(p.lat,p.lon,b.lat,b.lon):0).slice(0,80);for(const x of arr){const ll=wgsToGcj(x.lat,x.lon),html=`<div class="poi-map-icon ${x.category==='signal'?'signal':''}">${ICON[x.category]||'•'}</div>`,mk=L.marker(ll,{icon:L.divIcon({className:'',html,iconSize:[28,28],iconAnchor:[14,14]})});mk.bindPopup(`<b>${esc(x.name)}</b><br><span style="font-size:11px">${esc(LABEL[x.category]||'附近设施')} · ${x.source==='公开地图POI'?'公开地图数据':''}</span><br><a href="${amapNav(x)}" target="_blank">高德导航</a>`);mk.addTo(mapPoiLayer)}const note=$('#mapSourceNote');if(note)note.textContent=`高德中文道路底图 · 附近设施${poiLoadedAt?' '+ageText(poiLoadedAt)+'更新':''} · 当前显示${arr.length}个${mapFilter==='all'?'设施/路口':LABEL[mapFilter]}。POI与红绿灯数据可能不完整，实时路况以高德导航为准。`}
function observeMap(){const ov=$('#mapOverlay');if(!ov)return;new MutationObserver(()=>{if(ov.classList.contains('show'))setTimeout(enhanceMap,500)}).observe(ov,{attributes:true,attributeFilter:['class']})}
async function bootstrap(){installHub();installDecisionEvents();installUnread();hookLeaflet();observeMap();await Promise.all([weatherNow(),loadRemoteState(),loadVotes()]);renderHub();const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,2500));idle(()=>loadPois().then(()=>{renderHub();if(window.__cwFullMap)enhanceMap()}));setInterval(()=>{if(document.hidden)return;weatherNow().then(renderHub);loadVotes();loadRemoteState()},45000);setInterval(()=>{if(!document.hidden)renderHub()},12000)}
setTimeout(bootstrap,300);
})();