(()=>{
'use strict';
const TRIP='chuanxi2026',VOTE_API='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-vote';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const ICON={food:'🍜',photo:'📸',scenic:'🌄',cafe:'☕',toilet:'🚻',fuel:'⛽',service:'🛣️'};
const LABEL={food:'吃什么',photo:'拍什么',scenic:'去哪里',cafe:'咖啡',toilet:'厕所',fuel:'加油',service:'服务区'};
const ROUTES=[
{date:'2026-10-02',route:'天府机场 → 雅安',pts:[[30.312,104.441],[30.16,103.65],[29.98,103.00]]},
{date:'2026-10-03',route:'雅安 → 泸定 → 康定 → 折多山 → 新都桥',pts:[[29.98,103.00],[29.92,102.23],[30.05,101.96],[30.06,101.80],[30.04,101.49]]},
{date:'2026-10-04',route:'新都桥 → 塔公 → 八美 → 丹巴中路藏寨',pts:[[30.04,101.49],[30.32,101.54],[30.55,101.50],[30.88,101.89],[30.89,101.92]]},
{date:'2026-10-05',route:'丹巴 → 小金 → 四姑娘山双桥沟',pts:[[30.88,101.89],[30.99,102.36],[31.09,102.84],[31.10,102.89]]},
{date:'2026-10-06',route:'四姑娘山 → 卧龙 → 映秀 → 都江堰 → 天府机场',pts:[[31.10,102.89],[31.04,103.18],[31.06,103.48],[31.00,103.62],[30.312,104.441]]},
{date:'2026-10-07',route:'机场酒店 → 还车 → 航站楼',pts:[[30.30,104.44],[30.31,104.43],[30.312,104.441]]}
];
const state={cat:null,mode:'local',poi:[],pos:null,lastPosKey:'',loading:false,wx:null,wxAt:0};
function toast(msg){const e=$('#toast');if(!e)return; e.textContent=msg;e.classList.add('show');clearTimeout(e._d);e._d=setTimeout(()=>e.classList.remove('show'),2400)}
function hav(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,p1=r(a),p2=r(c),dp=r(c-a),dl=r(d-b),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function getPos(){try{const p=JSON.parse(localStorage.getItem('cw-lastpos-v4')||'null');if(!p||!Number.isFinite(+p.lat)||!Number.isFinite(+p.lon))return null;return {...p,lat:+p.lat,lon:+p.lon}}catch(e){return null}}
function fresh(p){return p&&Date.now()-(p.time||0)<15*60*1000}
function shDate(){return new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})}
function tripRoute(){return ROUTES.find(x=>x.date===shDate())||null}
function nearestTripKm(p,r=tripRoute()){if(!p||!r)return Infinity;return Math.min(...r.pts.map(x=>hav(p.lat,p.lon,x[0],x[1])))}
function modeFor(p){const r=tripRoute();return r&&nearestTripKm(p,r)<45?'trip':'local'}
function nowCat(){const h=+new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',hour12:false,timeZone:'Asia/Shanghai'}).format(new Date());if((h>=7&&h<=9)||(h>=11&&h<=13)||(h>=17&&h<=21))return'food';if(h>=9&&h<17)return'photo';return'food'}
function placeLabel(){return $('#nowPlace')?.textContent?.trim()||'当前位置'}
function ageText(p){if(!p?.time)return'暂无定位';const s=Math.max(0,Math.round((Date.now()-p.time)/1000));if(s<20)return'刚刚';if(s<60)return`${s}秒前`;return`${Math.round(s/60)}分钟前`}
function amapSearch(q){const p=getPos();if(!p)return`https://uri.amap.com/search?keyword=${encodeURIComponent(q)}&callnative=1`;return`https://uri.amap.com/search?keyword=${encodeURIComponent(q)}&center=${p.lon.toFixed(6)},${p.lat.toFixed(6)}&callnative=1`}
function amapNav(p){return`https://uri.amap.com/navigation?to=${p.lon.toFixed(6)},${p.lat.toFixed(6)},${encodeURIComponent(p.name)}&mode=car&policy=1&src=chuanxi2026&callnative=1`}
function overpassSpec(cat){const c=cat==='photo'?'scenic':cat;const m={
food:['6000','["amenity"~"restaurant|fast_food|food_court"]'],cafe:['6000','["amenity"="cafe"]'],toilet:['5000','["amenity"="toilets"]'],fuel:['12000','["amenity"="fuel"]'],service:['30000','["highway"~"services|rest_area"]'],scenic:['7000','["tourism"~"attraction|viewpoint"]|["leisure"="park"]|["historic"]']};return m[c]||m.scenic}
function overpassQuery(cat,p){const [rad,sel]=overpassSpec(cat);if(sel.includes('|')){const parts=sel.split('|');return`[out:json][timeout:7];(${parts.map(s=>`nwr(around:${rad},${p.lat},${p.lon})${s};`).join('')});out center tags 45;`}return`[out:json][timeout:7];(nwr(around:${rad},${p.lat},${p.lon})${sel};);out center tags 45;`}
function cacheKey(cat,p){return`cw-nearby-v2-${cat}-${p.lat.toFixed(2)}-${p.lon.toFixed(2)}`}
function parsePoi(j,cat,p){const seen=new Set(),rows=[];for(const x of j?.elements||[]){const lat=Number(x.lat??x.center?.lat),lon=Number(x.lon??x.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const t=x.tags||{},raw=t['name:zh']||t.name||'';let name=String(raw).trim();if(!name){if(cat==='toilet')name='公共厕所';else if(cat==='fuel')name='加油站';else if(cat==='service')name='服务区 / 休息区';else continue}const k=`${name}|${lat.toFixed(4)}|${lon.toFixed(4)}`;if(seen.has(k))continue;seen.add(k);rows.push({id:String(x.id),name,lat,lon,tags:t,d: hav(p.lat,p.lon,lat,lon)});}return rows.sort((a,b)=>a.d-b.d).slice(0,18)}
async function fetchPoi(cat,p){const key=cacheKey(cat,p);try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Date.now()-c.t<20*60*1000)return{rows:c.rows,cached:true,at:c.t}}catch(e){}
const q=overpassQuery(cat,p),eps=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const ep of eps){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),5200);try{const r=await fetch(ep,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q),signal:ac.signal});clearTimeout(tm);if(!r.ok)continue;const j=await r.json(),rows=parsePoi(j,cat,p);localStorage.setItem(key,JSON.stringify({t:Date.now(),rows}));return{rows,cached:false,at:Date.now()}}catch(e){clearTimeout(tm)}}try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c?.rows)return{rows:c.rows,cached:true,at:c.t}}catch(e){}return{rows:[],cached:false,at:0}}
async function weather(p){if(state.wx&&Date.now()-state.wxAt<20*60*1000)return state.wx;const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),4500);try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&current=temperature_2m,weather_code,cloud_cover,precipitation&daily=sunset&timezone=Asia%2FShanghai&forecast_days=1`,j=await fetch(u,{signal:ac.signal}).then(r=>r.json());clearTimeout(tm);state.wx=j;state.wxAt=Date.now();return j}catch(e){clearTimeout(tm);return null}}
function timeFit(cat){const h=+new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',hour12:false,timeZone:'Asia/Shanghai'}).format(new Date());if(cat==='food')return((h>=11&&h<=13)||(h>=17&&h<=21))?100:72;if(cat==='cafe')return h>=9&&h<=18?95:55;if(cat==='photo'||cat==='scenic')return h>=7&&h<=18?92:45;return 88}
function localRank(x,cat,w){const km=x.d,drive=Math.max(3,Math.round(km/28*60)),prox=clamp(100-km*11,30,100),tf=timeFit(cat);let weatherScore=90,reason=[];if(cat==='photo'||cat==='scenic'){const rain=Number(w?.current?.precipitation||0),cloud=Number(w?.current?.cloud_cover||0);if(rain>0)weatherScore=55;else if(cloud>=20&&cloud<=80)weatherScore=96;reason.push(rain>0?'当前有降水，拍摄条件一般':cloud>=20&&cloud<=80?'当前云量对拍照较友好':'当前天气可用')}const score=Math.round(prox*.55+tf*.25+weatherScore*.20);reason.unshift(km<1?'离你很近':`距你约 ${km.toFixed(1)}km`);if(cat==='food'&&tf>90)reason.push('当前正值饭点');if(cat==='toilet'||cat==='fuel'||cat==='service')reason.push('优先按距离排序');return{...x,score,drive,reason}}
function tripRank(x,cat,w){const r=tripRoute(),p=state.pos,nearCur=Math.min(...r.pts.map(q=>hav(p.lat,p.lon,q[0],q[1]))),nearPoi=Math.min(...r.pts.map(q=>hav(x.lat,x.lon,q[0],q[1]))),drive=Math.max(3,Math.round(x.d/38*60)),detour=Math.round(nearPoi/35*60*2),routeScore=clamp(100-nearPoi*12,25,100),score=Math.round(routeScore*.55+timeFit(cat)*.25+90*.20),reason=[nearPoi<1?'基本顺路':`偏离今日路线约 ${nearPoi.toFixed(1)}km`,detour<8?'绕路成本低':`预计额外约 ${detour} 分钟（估算）`];return{...x,score,drive,detour,nearPoi,reason}}
function sourceLine(meta){if(!meta)return'';return meta.cached?`缓存数据 · ${new Date(meta.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`:'附近数据刚刚更新'}
function resultCard(x,cat,i){const trip=state.mode==='trip';const meta=trip?`距你 ${x.d.toFixed(1)}km · ${x.nearPoi<1?'基本顺路':'偏离'+x.nearPoi.toFixed(1)+'km'} · 约${x.drive}分钟到`:`距你 ${x.d<1?Math.round(x.d*1000)+'m':x.d.toFixed(1)+'km'} · 约${x.drive}分钟车程`;return`<div class="decision-result"><div class="decision-rank"><strong>${i===0?'🥇 ':i===1?'🥈 ':''}${esc(x.name)}</strong><span class="decision-score">值得去 ${x.score}</span></div><div class="decision-meta"><span>${meta}</span>${x.tags?.opening_hours?`<span>营业信息：${esc(x.tags.opening_hours)}</span>`:''}</div><p class="decision-reason">${x.reason.map(r=>'✓ '+esc(r)).join('　')}</p><div class="decision-actions"><a class="primary" href="${amapNav(x)}">高德导航</a><button data-set-next="${i}">设为下一站</button><button data-vote="${i}">四人投票</button></div></div>`}
function emptyCard(cat){return`<div class="decision-empty">暂时没有拿到可靠的附近数据，不会给你推荐几百公里外的地点。<div class="decision-actions" style="justify-content:center"><a class="primary" href="${amapSearch(LABEL[cat]||'附近')}">用高德查看附近${esc(LABEL[cat]||'地点')}</a></div></div>`}
function setHeader(){const p=state.pos,mode=state.mode,loc=placeLabel(),tm=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});$('#decisionPlace').textContent=`${loc} · ${tm}`;$('#decisionMode').textContent=mode==='trip'?'川西行程模式':'当前位置模式';$('#decisionMode').className='decision-mode '+(mode==='local'?'local':'');$('#decisionModeNote').textContent=mode==='trip'?'推荐会结合今日路线；绕路时间为估算，不冒充实时路况。':`你现在不在当天川西路线附近，只推荐当前位置周边，不再拿川西景点参与排名。${p?' GPS '+ageText(p):''}`}
async function choose(cat,openOverlay=false){state.cat=cat;$$('#decisionHub [data-dec-cat]').forEach(b=>b.classList.toggle('on',b.dataset.decCat===cat));const p=getPos();state.pos=p;state.mode=modeFor(p);setHeader();const box=$('#decisionResults');if(!fresh(p)){box.innerHTML=`<div class="decision-empty">正在等待手机精确定位。获得新位置后才会给“现在去哪”排序，避免使用旧位置误导你。<div class="decision-actions" style="justify-content:center"><a href="${amapSearch(LABEL[cat])}">先用高德搜索</a></div></div>`;return}box.innerHTML='<div class="decision-empty">正在看你当前位置周边…</div>';const [meta,w]=await Promise.all([fetchPoi(cat,p),weather(p)]);let rows=meta.rows.map(x=>state.mode==='trip'?tripRank(x,cat,w):localRank(x,cat,w)).sort((a,b)=>b.score-a.score||a.d-b.d).slice(0,3);state.poi=rows;$('#decisionFresh').textContent=sourceLine(meta)||'暂无可靠数据';box.innerHTML=rows.length?rows.map((x,i)=>resultCard(x,cat,i)).join(''):emptyCard(cat);if(openOverlay&&cat==='photo')openPhoto(rows[0]||null,w);}
function openDecision(title,html){let ov=$('#decisionOverlay');if(!ov){ov=document.createElement('div');ov.id='decisionOverlay';ov.className='overlay';ov.setAttribute('aria-hidden','true');ov.innerHTML='<div class="modal"><div class="modal-head"><div><span class="eyebrow">即时建议</span><h2 id="decisionOverlayTitle"></h2></div><button data-close-decision>×</button></div><div id="decisionOverlayBody" class="decision-overlay-body"></div></div>';document.body.appendChild(ov)}$('#decisionOverlayTitle').textContent=title;$('#decisionOverlayBody').innerHTML=html;ov.classList.add('show');ov.setAttribute('aria-hidden','false')}
function openPhoto(x,w){const p=x||{name:placeLabel(),d:0,drive:0};const rain=Number(w?.current?.precipitation||0),cloud=Number(w?.current?.cloud_cover||0),tips=rain>0?'当前有降水，优先找有遮挡的位置，注意镜头防水。':cloud>20&&cloud<80?'当前云层有层次，适合人像和环境照。':'先看现场光线，避免让人物正对强光。';openDecision(`怎么拍 · ${p.name}`,`<div class="photo-guide"><h3>${esc(p.name)}</h3><p>${esc(tips)}${p.d?` 距你约 ${p.d.toFixed(1)}km。`:''}</p><div class="pose-grid"><div class="pose-card"><b>01 自然走路</b><p>身体侧45°，不要一直看镜头；一只手插口袋，连续走3–5步。</p><small>iPhone：2X · 曝光 -0.3 · Live Photo/连拍</small></div><div class="pose-card"><b>02 背影环境照</b><p>人物只占画面约1/4，把建筑、道路或风景留出来。</p><small>1X 或 2X · 人物放三分线 · 不要站在机动车道</small></div><div class="pose-card"><b>03 四人合影</b><p>不要排成一条直线，前后错半步；摄影者退远一点再用2X。</p><small>避免超广角把边缘人物拉变形</small></div></div>${x?`<div class="decision-actions"><a class="primary" href="${amapNav(x)}">导航到这里</a></div>`:''}</div>`)}
async function voteFor(x){if(!x)return;try{const payload={person:ME,question:`现在去「${x.name}」吗？`,options:[{id:'yes',label:'去'},{id:'no',label:'不去'}],initial_option:'yes',context:{name:x.name,lat:x.lat,lon:x.lon,source:'现在去哪'}};await fetch(VOTE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action:'create_vote',payload})}).then(r=>r.json());toast('已发起四人投票')}catch(e){toast('投票暂时没有同步成功')}}
async function setNext(x){if(!x)return;try{await fetch(VOTE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action:'set_next_stop',payload:{person:ME,name:x.name,lat:x.lat,lon:x.lon,source:'现在去哪'}})}).then(r=>r.json());toast('已设为共享下一站')}catch(e){toast('下一站暂时没有同步成功')}}
function build(){if($('#decisionHub'))return;const now=$('#view-now .now-card');if(!now)return;const sec=document.createElement('section');sec.id='decisionHub';sec.className='card decision-hub';sec.innerHTML=`<div class="decision-head"><div><span class="eyebrow">当前位置 · 附近灵感</span><h2 id="decisionPlace">正在获取位置</h2><p id="decisionModeNote">只按当前真实位置推荐，不会把远处川西景点硬塞进来。</p></div><span id="decisionMode" class="decision-mode local">当前位置模式</span></div><div class="decision-quick">${['food','photo','scenic','cafe','toilet','fuel'].map(c=>`<button data-dec-cat="${c}"><i>${ICON[c]}</i>${LABEL[c]}</button>`).join('')}</div><div class="decision-summary"><div class="decision-summary-head"><b>现在最值得</b><span id="decisionFresh">等待定位</span></div><div id="decisionResults"></div><div class="decision-more"><button data-extra-cat="service">🛣️ 附近服务区</button><button data-extra-search="停车场">🅿️ 附近停车</button><button data-extra-search="医院">🏥 附近医院</button><button data-extra-search="汽车维修">🔧 附近修理厂</button></div></div>`;now.insertAdjacentElement('afterend',sec);const first=nowCat();state.cat=first;setTimeout(()=>choose(first),250)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-dec-cat]');if(b){e.preventDefault();const c=b.dataset.decCat;if(c==='photo')choose(c,true);else choose(c);return}const ex=e.target.closest('[data-extra-cat]');if(ex){e.preventDefault();choose(ex.dataset.extraCat);return}const sr=e.target.closest('[data-extra-search]');if(sr){e.preventDefault();window.open(amapSearch(sr.dataset.extraSearch),'_blank');return}const n=e.target.closest('[data-set-next]');if(n){setNext(state.poi[+n.dataset.setNext]);return}const v=e.target.closest('[data-vote]');if(v){voteFor(state.poi[+v.dataset.vote]);return}if(e.target.closest('[data-close-decision]')||e.target.id==='decisionOverlay'){$('#decisionOverlay')?.classList.remove('show')}});
function watchPos(){let last='';setInterval(()=>{const p=getPos(),k=p?`${p.lat.toFixed(4)},${p.lon.toFixed(4)},${Math.floor((p.time||0)/60000)}`:'';if(k&&k!==last){last=k;state.pos=p;state.mode=modeFor(p);setHeader();if(state.cat)choose(state.cat)}},4000)}
function init(){build();watchPos();window.__CW_DECISION_V2={choose,state,modeFor}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();