(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
if(!TEAM.includes(ME))return;
const ENDPOINT='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-social',TRIP='chuanxi2026',QA=window.CWSession?.qa===true;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let scheduled=0,captionTimer=0,lastCaption='';
function token(){return sessionStorage.getItem(`cw-auth-${ME}`)||(QA?'qa-token-abcdefghijklmnopqrstuvwxyz':'')}
async function api(action,payload={}){const tk=token();if(!tk)throw new Error('登录已失效');const c=new AbortController(),tm=setTimeout(()=>c.abort(),9000);try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action,payload:{...payload,person:ME,token:tk}}),signal:c.signal});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'同步失败');return j}finally{clearTimeout(tm)}}
function cache(){try{return JSON.parse(localStorage.getItem(`cw-social-cache-${ME}`)||'null')?.data||{}}catch{return {}}}
function profile(data,p){return (data.profiles||[]).find(x=>x.person===p)||{person:p,nickname:p,avatar_url:''}}
function pname(data,p){return profile(data,p).nickname||p}
function pimg(data,p){return profile(data,p).avatar_url||''}
function toast(msg){const e=$('#toast');if(e){e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}else console.log(msg)}
function duration(sec){sec=Math.max(0,Math.round(sec||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h}h${m?m+'m':''}`:`${m||0}m`}
function shParts(t){const out={};new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(t)).forEach(x=>{if(x.type!=='literal')out[x.type]=x.value});return out}
function dayLabel(t){const p=shParts(t);return `${Number(p.month)}月${Number(p.day)}日`}
function hm(t){const p=shParts(t);return `${p.hour}:${p.minute}`}
function localInput(t){if(!t)return'';const p=shParts(t);return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`}
function inputIso(v){if(!v)return null;const d=new Date(`${v}:00+08:00`);return Number.isFinite(d.getTime())?d.toISOString():null}
function totals(data){const out=Object.fromEntries(TEAM.map(p=>[p,0]));for(const x of data.driver_sessions||[]){const a=new Date(x.started_at).getTime(),b=x.ended_at?new Date(x.ended_at).getTime():Date.now();if(Number.isFinite(a)&&Number.isFinite(b)&&b>a)out[x.person]=(out[x.person]||0)+(b-a)/1000}return out}
function captionFor(data,p){return (data.avatar_messages||[]).find(x=>x.person===p)?.message||''}
function renderCaptions(){const data=cache(),row=$('#cwMemberRow');if(!row)return;let any=false;for(const p of TEAM){const member=row.querySelector(`[data-social-person="${p}"]`),face=member?.querySelector('.cw-member-face');if(!face)continue;const msg=captionFor(data,p),old=face.querySelector('.cw-avatar-caption');if(msg){any=true;if(!old||old.textContent!==msg){old?.remove();face.insertAdjacentHTML('afterbegin',`<i class="cw-avatar-caption" title="${esc(msg)}">${esc(msg)}</i>`)}}else old?.remove()}row.classList.toggle('has-avatar-caption',any)}
function rankMeta(i){return [
  ['🥇','黄金车神','gold'],
  ['🥈','白银老司机','silver'],
  ['🥉','青铜方向盘','bronze'],
  ['🔩','废铁车手','iron']
][i]||['•','未上榜','']}
function canEdit(x){return ME==='瑞子'||x.person===ME}
function renderDriverFun(){const box=$('#cwDriverBox');if(!box)return;const data=cache(),sessions=(data.driver_sessions||[]).slice().sort((a,b)=>new Date(b.started_at)-new Date(a.started_at)),tot=totals(data),rank=TEAM.map(p=>({p,sec:tot[p]||0})).sort((a,b)=>b.sec-a.sec||TEAM.indexOf(a.p)-TEAM.indexOf(b.p));let host=$('#cwDriverFun');if(!host){host=document.createElement('div');host.id='cwDriverFun';host.className='cw-driver-fun';box.appendChild(host)}
const sig=JSON.stringify({s:sessions.map(x=>[x.id,x.person,x.started_at,x.ended_at]),a:(data.avatar_messages||[]).map(x=>[x.person,x.message,x.updated_at]),n:(data.profiles||[]).map(x=>[x.person,x.nickname,x.avatar_url]),tick:sessions.some(x=>!x.ended_at)?Math.floor(Date.now()/60000):0});if(host.dataset.sig===sig)return;host.dataset.sig=sig;
const ranks=rank.map((r,i)=>{const [medal,title,cls]=rankMeta(i);return `<div class="cw-rank-item ${cls}"><span class="cw-rank-medal">${medal}</span><div class="cw-rank-main"><b>${esc(pname(data,r.p))}</b><span>${title}</span></div><span class="cw-rank-time">${duration(r.sec)}</span></div>`}).join('');
const rows=sessions.length?sessions.map((x,i)=>{const start=dayLabel(x.started_at),range=x.ended_at?(dayLabel(x.ended_at)===start?`${start} ${hm(x.started_at)}–${hm(x.ended_at)}`:`${start} ${hm(x.started_at)} → ${dayLabel(x.ended_at)} ${hm(x.ended_at)}`):`${start} ${hm(x.started_at)}–现在`,img=pimg(data,x.person),sec=((x.ended_at?new Date(x.ended_at).getTime():Date.now())-new Date(x.started_at).getTime())/1000;return `<div class="cw-drive-row ${x.ended_at?'':'live'} ${i>=5?'is-extra':''}" data-drive-id="${esc(x.id)}"><span class="cw-drive-avatar">${img?`<img src="${esc(img)}" alt="">`:esc(x.person?.[0]||'驾')}</span><div class="cw-drive-main"><b>${esc(pname(data,x.person))}${x.ended_at?'':' · 正在开'}</b><span>${esc(range)}</span></div><div class="cw-drive-side"><strong>${duration(sec)}</strong>${canEdit(x)?`<div class="cw-drive-actions"><button type="button" data-drive-edit="${esc(x.id)}">更正</button><button type="button" class="danger" data-drive-delete="${esc(x.id)}">删除</button></div>`:''}</div></div>`}).join(''):'<div class="cw-driver-history-empty">还没有驾驶记录</div>';
host.innerHTML=`<div class="cw-driver-rank-head"><b>🏁 开车时长排名</b><span>按累计驾驶时长 · 纯属娱乐</span></div><div class="cw-driver-rank">${ranks}</div><div class="cw-driver-log"><div class="cw-driver-log-head"><b>驾驶记录</b><span>可更正自己的记录 · 瑞子可管理全部</span></div><div class="cw-driver-log-list">${rows}</div>${sessions.length>5?`<button type="button" class="cw-drive-more" data-drive-more>查看全部驾驶记录（${sessions.length}）</button>`:''}</div>`}
function ensureDialog(){let ov=$('#cwFunDialog');if(ov)return ov;ov=document.createElement('div');ov.id='cwFunDialog';ov.className='cw-fun-dialog';document.body.appendChild(ov);return ov}
function closeDialog(){const ov=$('#cwFunDialog');if(ov){ov.classList.remove('show');ov.innerHTML=''}}
function confirmDelete(id){const data=cache(),x=(data.driver_sessions||[]).find(r=>String(r.id)===String(id));if(!x)return;const ov=ensureDialog();ov.innerHTML=`<div class="cw-fun-dialog-card"><h3>删除驾驶记录？</h3><p>${esc(pname(data,x.person))} · ${esc(dayLabel(x.started_at))} ${esc(hm(x.started_at))}${x.ended_at?'–'+esc(hm(x.ended_at)):'–现在'}。删除后排名也会重新计算。</p><div class="cw-fun-dialog-actions"><button type="button" data-fun-cancel>取消</button><button type="button" class="danger" data-fun-delete-confirm="${esc(id)}">确认删除</button></div></div>`;ov.classList.add('show')}
function editDialog(id){const data=cache(),x=(data.driver_sessions||[]).find(r=>String(r.id)===String(id));if(!x)return;const ov=ensureDialog(),driverSelect=ME==='瑞子'?`<label>驾驶员<select id="cwEditDriver">${TEAM.map(p=>`<option value="${p}" ${p===x.person?'selected':''}>${esc(pname(data,p))}</option>`).join('')}</select></label>`:`<input id="cwEditDriver" type="hidden" value="${esc(x.person)}">`;ov.innerHTML=`<div class="cw-fun-dialog-card"><h3>更正驾驶记录</h3><p>只有点击“确认更正”才会保存；取消不会修改任何数据。</p><div class="cw-fun-form">${driverSelect}<label>开始时间<input id="cwEditStart" type="datetime-local" value="${localInput(x.started_at)}"></label><label>结束时间<input id="cwEditEnd" type="datetime-local" value="${x.ended_at?localInput(x.ended_at):''}"><small>${x.ended_at?'':'留空代表仍在驾驶'}</small></label></div><div class="cw-fun-dialog-actions"><button type="button" data-fun-cancel>取消</button><button type="button" class="primary" data-fun-save="${esc(id)}">确认更正</button></div></div>`;ov.classList.add('show')}
async function fresh(){try{const j=await api('state');localStorage.setItem(`cw-social-cache-${ME}`,JSON.stringify({saved:Date.now(),data:j}));document.querySelector('#cwRefreshSocial')?.click();setTimeout(renderAll,120)}catch(e){toast(e.message)}}
function injectCaptionEditor(){const body=$('#cwSocialSheetBody');if(!body||!body.querySelector('h3')?.textContent.includes('我的临时状态')||body.querySelector('#cwAvatarMessageInput'))return;const data=cache(),msg=captionFor(data,ME),wrap=document.createElement('div');wrap.className='cw-avatar-note-edit';wrap.innerHTML=`<label>头像上面说一句</label><div class="cw-avatar-note-line"><input id="cwAvatarMessageInput" maxlength="24" value="${esc(msg)}" placeholder="例如：今天我掌舵"><button type="button" data-avatar-message-clear>清空</button></div><small>停止输入约 0.8 秒后自动同步，四个人都会看到。</small>`;const p=body.querySelector('p');(p||body.querySelector('h3')).insertAdjacentElement('afterend',wrap);lastCaption=msg}
async function syncCaption(value){value=String(value||'').trim().slice(0,24);if(value===lastCaption)return;try{await api('set_avatar_message',{message:value});lastCaption=value;await fresh();toast(value?'头像文字已同步':'头像文字已清空')}catch(e){toast(e.message)}}
function renderAll(){renderCaptions();renderDriverFun();injectCaptionEditor()}
function schedule(){clearTimeout(scheduled);scheduled=setTimeout(renderAll,35)}
document.addEventListener('click',async e=>{const more=e.target.closest('[data-drive-more]');if(more){const h=$('#cwDriverFun');const on=h?.classList.toggle('expanded');more.textContent=on?'收起驾驶记录':`查看全部驾驶记录（${h?.querySelectorAll('.cw-drive-row').length||0}）`;return}const edit=e.target.closest('[data-drive-edit]');if(edit)return editDialog(edit.dataset.driveEdit);const del=e.target.closest('[data-drive-delete]');if(del)return confirmDelete(del.dataset.driveDelete);if(e.target.closest('[data-fun-cancel]'))return closeDialog();const dc=e.target.closest('[data-fun-delete-confirm]');if(dc){dc.disabled=true;try{await api('delete_driver_session',{session_id:dc.dataset.funDeleteConfirm});closeDialog();await fresh();toast('驾驶记录已删除')}catch(x){dc.disabled=false;toast(x.message)}return}const sv=e.target.closest('[data-fun-save]');if(sv){const start=inputIso($('#cwEditStart')?.value),endRaw=$('#cwEditEnd')?.value||'',end=endRaw?inputIso(endRaw):null,driver=$('#cwEditDriver')?.value;if(!start)return toast('开始时间不正确');if(endRaw&&!end)return toast('结束时间不正确');if(end&&new Date(end)<=new Date(start))return toast('结束时间必须晚于开始时间');sv.disabled=true;try{await api('update_driver_session',{session_id:sv.dataset.funSave,driver_person:driver,started_at:start,ended_at:end});closeDialog();await fresh();toast('驾驶记录已更正')}catch(x){sv.disabled=false;toast(x.message)}return}if(e.target.closest('[data-avatar-message-clear]')){const inp=$('#cwAvatarMessageInput');if(inp)inp.value='';clearTimeout(captionTimer);syncCaption('');return}setTimeout(injectCaptionEditor,30)},true);
document.addEventListener('input',e=>{if(e.target?.id!=='cwAvatarMessageInput')return;clearTimeout(captionTimer);const v=e.target.value;const mine=$(`#cwMemberRow [data-social-person="${ME}"] .cw-member-face`);if(mine){const old=mine.querySelector('.cw-avatar-caption'),msg=v.trim().slice(0,24);if(msg){if(!old||old.textContent!==msg){old?.remove();mine.insertAdjacentHTML('afterbegin',`<i class="cw-avatar-caption">${esc(msg)}</i>`)}}else old?.remove();$('#cwMemberRow')?.classList.toggle('has-avatar-caption',!!$('#cwMemberRow .cw-avatar-caption'))}captionTimer=setTimeout(()=>syncCaption(v),800)});
const start=()=>{if(!$('#cwSocialCard'))return setTimeout(start,100);new MutationObserver(schedule).observe($('#cwSocialCard'),{childList:true,subtree:true});new MutationObserver(schedule).observe(document.body,{childList:true,subtree:false});renderAll();setInterval(()=>{if(!document.hidden)renderAll()},5000);document.documentElement.classList.add('cw-driver-fun-ready')};
start();
})();