(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
if(!TEAM.includes(ME))return;
const FN='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync',TRIP='chuanxi2026',MAX_AMOUNT=9999999.99;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let S=null,renderTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const cents=n=>Math.round(Number(n||0)*100);
const validAmount=n=>Number.isFinite(Number(n))&&Number(n)>0&&Number(n)<=MAX_AMOUNT&&Math.abs(Number(n)*100-Math.round(Number(n)*100))<1e-6;
function normalizeParts(arr){const seen=new Set();return (Array.isArray(arr)?arr:TEAM).filter(p=>TEAM.includes(p)&&!seen.has(p)&&seen.add(p))}
function addDebt(m,from,to,ct){if(from===to||!ct)return;m[from]??={};m[from][to]=(m[from][to]||0)+ct}
function pairwisePlan(state=S){const debt=Object.fromEntries(TEAM.map(p=>[p,{}]));for(const e of state?.expenses||[]){if(e.status==='budget')continue;const amt=cents(e.amount),payer=String(e.payer||''),ps=normalizeParts(e.participants);if(!TEAM.includes(payer)||amt<=0||!ps.length)continue;const base=Math.floor(amt/ps.length),rem=amt%ps.length;ps.forEach((p,i)=>{const share=base+(i<rem?1:0);if(p!==payer)addDebt(debt,p,payer,share)})}for(const r of state?.repayments||[]){const from=String(r.from_person||''),to=String(r.to_person||''),ct=cents(r.amount);if(!TEAM.includes(from)||!TEAM.includes(to)||from===to||ct<=0)continue;addDebt(debt,from,to,-ct)}const out=[];for(let i=0;i<TEAM.length;i++)for(let j=i+1;j<TEAM.length;j++){const a=TEAM[i],b=TEAM[j],net=(debt[a]?.[b]||0)-(debt[b]?.[a]||0);if(net>0)out.push({from:a,to:b,amount:net/100});else if(net<0)out.push({from:b,to:a,amount:-net/100})}return out}
function cashSummary(p,state=S){const ex=(state?.expenses||[]).filter(e=>e.status!=='budget'),paid=ex.filter(e=>e.payer===p).reduce((s,e)=>s+Number(e.amount||0),0),shareCt=ex.reduce((s,e)=>{const ps=normalizeParts(e.participants);if(!ps.includes(p)||!ps.length)return s;const amt=cents(e.amount),base=Math.floor(amt/ps.length),rem=amt%ps.length,idx=ps.indexOf(p);return s+base+(idx>=0&&idx<rem?1:0)},0),sent=(state?.repayments||[]).filter(r=>r.from_person===p).reduce((s,r)=>s+Number(r.amount||0),0),recv=(state?.repayments||[]).filter(r=>r.to_person===p).reduce((s,r)=>s+Number(r.amount||0),0),pl=pairwisePlan(state),gets=pl.filter(x=>x.to===p),owes=pl.filter(x=>x.from===p);return{paid,share:shareCt/100,outflow:paid+sent-recv,gets,owes,getTotal:gets.reduce((s,x)=>s+x.amount,0),oweTotal:owes.reduce((s,x)=>s+x.amount,0)}}
function setHtml(el,html){if(!el||el.dataset.cwLedgerHtml===html)return;el.dataset.cwLedgerHtml=html;el.innerHTML=html}
function renderMoney(el,p){if(!el||!S)return;const m=cashSummary(p),html=`<div data-ledger-kind="outflow" data-ledger-person="${esc(p)}" role="button" tabindex="0"><span>我已垫付</span><b>${money(m.paid)}</b></div><div data-ledger-kind="share" data-ledger-person="${esc(p)}" role="button" tabindex="0"><span>我的消费</span><b>${money(m.share)}</b></div><div class="recv" data-ledger-kind="get" data-ledger-person="${esc(p)}" role="button" tabindex="0"><span>我该收</span><b>${money(m.getTotal)}</b></div><div class="pay" data-ledger-kind="owe" data-ledger-person="${esc(p)}" role="button" tabindex="0"><span>我该付</span><b>${money(m.oweTotal)}</b></div>`;setHtml(el,html)}
function renderSettlement(){if(!S)return;renderMoney($('#meMoney'),ME);renderMoney($('#homeMoney'),ME);const box=$('#settlementLines');if(box){const m=cashSummary(ME),rows=[...m.gets.map(x=>`<div class="settle-line" data-ledger-pair="${esc(x.from)}|${esc(x.to)}" role="button" tabindex="0"><span>${esc(x.from)} 应付给我</span><b>${money(x.amount)}</b></div>`),...m.owes.map(x=>`<div class="settle-line" data-ledger-pair="${esc(x.from)}|${esc(x.to)}" role="button" tabindex="0"><span>我应付给 ${esc(x.to)}</span><b>${money(x.amount)}</b></div>` )],html=rows.join('')||'<div class="settle-line"><span>当前无需结算</span><b>✓</b></div>';setHtml(box,html)}patchDailyFinance()}
function expensePreview(){const form=$('#expenseForm');if(!form)return;let p=$('#cwExpensePreview');if(!p){p=document.createElement('div');p.id='cwExpensePreview';p.className='cw-expense-preview';const submit=form.querySelector('[type=submit]');submit?.insertAdjacentElement('beforebegin',p)}const amt=Number($('#expAmount')?.value||0),payer=$('#expPayer')?.value||ME,ps=$$('#expParticipants input:checked').map(x=>x.value).filter(x=>TEAM.includes(x));const who=payer===ME?'你本人':payer;let html;if(!validAmount(amt)||!ps.length)html=`<b>谁实际付款，钱就算欠谁</b><span>当前记账身份：${esc(ME)}。请选择“实际付款人”和参与分摊的人。</span>`;else{const share=amt/ps.length,other=ps.filter(x=>x!==payer).length;html=`<b>${esc(who)}实际付款 ${money(amt)}</b><span>${ps.length}人分摊 · 每人约 ${money(share)}${other?` · 其他参与人应结算给 ${esc(payer)}`:''}${payer!==ME?` · 由${esc(ME)}代记账，不改变收款人`:''}</span>`}setHtml(p,html)}
function decorateForm(){const amt=$('#expAmount'),payer=$('#expPayer');if(amt){amt.max=String(MAX_AMOUNT);amt.setAttribute('aria-describedby','cwExpensePreview')}if(payer){payer.setAttribute('aria-label','实际付款人');payer.title='实际付款人决定这笔钱最终应该还给谁'}let note=$('#cwPayerRule');if(!note&&payer){note=document.createElement('div');note.id='cwPayerRule';note.className='cw-payer-rule';note.innerHTML='<b>实际付款人 ≠ 记账人</b><span>例如用瑞子账号记录辉子支付的租车费，请把“付款人”选成辉子，系统会算作其他参与人欠辉子。</span>';payer.insertAdjacentElement('afterend',note)}expensePreview()}
function warn(msg){const t=$('#toast');if(t){t.textContent=msg;t.classList.add('show');clearTimeout(t._ledger);t._ledger=setTimeout(()=>t.classList.remove('show'),2600)}else alert(msg)}
function validateField(input){const n=Number(input?.value);if(validAmount(n))return true;warn(`金额需在 ¥0.01–¥${MAX_AMOUNT.toLocaleString('zh-CN')} 之间，最多两位小数`);input?.focus();return false}
function patchEditLimits(){for(const id of ['#eeAmt','#erAmt']){const e=$(id);if(e)e.max=String(MAX_AMOUNT)}}
function patchDailyFinance(){const body=$('#cwDailyBody');if(!body||!S)return;body.querySelectorAll(':scope > .cw-daily-line.money').forEach(x=>x.remove());let host=$('#cwLedgerDailyLines');if(!host){host=document.createElement('div');host.id='cwLedgerDailyLines';body.prepend(host)}const m=cashSummary(ME),lines=[...m.gets.map(x=>`<div class="cw-daily-line money"><i>¥</i><div><span>账本</span><b>应收 ${esc(x.from)} ${money(x.amount)}</b></div></div>`),...m.owes.map(x=>`<div class="cw-daily-line money"><i>¥</i><div><span>账本</span><b>应付 ${esc(x.to)} ${money(x.amount)}</b></div></div>`)],html=lines.join('');setHtml(host,html)}
async function load(){const before=S;try{const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action:'get_state',payload:{}})});if(!r.ok)return;const next=await r.json();if(S&&S!==before)return;S=next;renderSettlement()}catch{}}
function schedule(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>{decorateForm();patchEditLimits();renderSettlement()},40)}
window.addEventListener('cw:state',e=>{if(e.detail?.state)S=e.detail.state;schedule()});
document.addEventListener('input',e=>{if(e.target.closest?.('#expenseForm'))expensePreview()});
document.addEventListener('change',e=>{if(e.target.closest?.('#expenseForm'))expensePreview()});
document.addEventListener('click',e=>{const q=e.target.closest?.('[data-exp-cat]');if(q){const before=$('#expPayer')?.value;setTimeout(()=>{if(before&&$('#expPayer'))$('#expPayer').value=before;expensePreview()},0)}},true);
document.addEventListener('submit',e=>{if(e.target?.id!=='expenseForm')return;if(!validateField($('#expAmount'))){e.preventDefault();e.stopImmediatePropagation()}},true);
document.addEventListener('click',e=>{if(e.target.closest?.('#eeSave')&&!validateField($('#eeAmt'))){e.preventDefault();e.stopImmediatePropagation()}if(e.target.closest?.('#erSave')&&!validateField($('#erAmt'))){e.preventDefault();e.stopImmediatePropagation()}},true);
new MutationObserver(muts=>{if(muts.some(m=>[...m.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('#expenseForm,#editOverlay,#cwDailyCard,#meMoney,#settlementLines')||n.querySelector?.('#expenseForm,#eeAmt,#erAmt,#cwDailyCard,#meMoney,#settlementLines')))))schedule()}).observe(document.documentElement,{childList:true,subtree:true});
const wait=()=>{if($('#expenseForm')){decorateForm();load();document.documentElement.classList.add('cw-ledger-v2-ready')}else setTimeout(wait,100)};wait();
window.CWLedgerV2={pairwisePlan:()=>pairwisePlan(S),summary:p=>cashSummary(p,S),maxAmount:MAX_AMOUNT};
})();