(()=>{
'use strict';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'';
const QA=new URLSearchParams(location.search).get('qa')==='1';
const ENDPOINT='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-ledger',TRIP='chuanxi2026';
const $=s=>document.querySelector(s);
let busy=false;
function count(){const m=String($('#pendingBadge')?.textContent||'').match(/(\d+)/);return m?Number(m[1]):0}
function style(){if($('#cwAckAllStyle'))return;const s=document.createElement('style');s.id='cwAckAllStyle';s.textContent='.cw-ack-all{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:0 0 12px;padding:12px 13px;border:1px solid #f1d8cf;background:#fff7f3;border-radius:14px}.cw-ack-all[hidden]{display:none}.cw-ack-all span{font-size:13px;color:#8b4e3b;font-weight:800}.cw-ack-all button{min-height:40px;padding:0 14px;border:0;border-radius:12px;background:#d9534f;color:#fff;font-weight:900;font-size:13px}.cw-ack-all button:disabled{opacity:.55}#pendingBadge.cw-clickable{cursor:pointer;box-shadow:0 0 0 3px #fce7e2}';document.head.appendChild(s)}
function ensure(){style();const list=$('#ledgerList');if(!list)return null;let box=$('#cwAckAll');if(!box){box=document.createElement('div');box.id='cwAckAll';box.className='cw-ack-all';box.innerHTML='<span id="cwAckAllText">有未读账单</span><button type="button" id="cwAckAllBtn">一键已读</button>';list.parentElement?.insertBefore(box,list);$('#cwAckAllBtn').onclick=ackAll;const badge=$('#pendingBadge');if(badge){badge.classList.add('cw-clickable');badge.addEventListener('click',()=>{document.querySelector('#bottomNav button[data-view="me"]')?.click();setTimeout(()=>box.scrollIntoView({behavior:'smooth',block:'center'}),120)})}}return box}
function paint(){const box=ensure();if(!box)return;const n=count();box.hidden=n<=0;$('#cwAckAllText').textContent=n>0?`与我有关 · ${n}笔未读`:'没有未读账单';$('#cwAckAllBtn').textContent=n>0?`一键已读 ${n}笔`:'已全部读完'}
async function ackAll(){if(busy)return;const n=count();if(!n)return;busy=true;const b=$('#cwAckAllBtn');b.disabled=true;b.textContent='正在确认…';const token=QA?'qa-token':sessionStorage.getItem(`cw-auth-${ME}`)||'';try{const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action:'ack_all',payload:{person:ME,token}}),signal:c.signal});clearTimeout(t);const j=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401){sessionStorage.removeItem(`cw-auth-${ME}`);location.replace(`./?person=${encodeURIComponent(ME)}`);return}throw new Error(j.error||'操作失败')}const badge=$('#pendingBadge');if(badge)badge.textContent='0笔待确认';const nav=$('#navBadge');if(nav){nav.textContent='';nav.classList.remove('show')}document.querySelectorAll('#ledgerList [data-ledger="ack"]').forEach(x=>x.remove());paint();document.dispatchEvent(new Event('visibilitychange'));const toast=$('#toast');if(toast){toast.textContent=`已确认 ${j.count??n} 笔`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}}catch(e){b.textContent='重试一键已读';const toast=$('#toast');if(toast){toast.textContent=e.message||'一键已读失败';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}}finally{busy=false;b.disabled=false;setTimeout(paint,200)}}
function init(){paint();const badge=$('#pendingBadge'),list=$('#ledgerList');if('MutationObserver'in window){if(badge)new MutationObserver(paint).observe(badge,{childList:true,subtree:true,characterData:true});if(list)new MutationObserver(()=>setTimeout(paint,0)).observe(list,{childList:true})}setInterval(()=>{if(!document.hidden)paint()},4000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,180),{once:true});else setTimeout(init,180)
})();