(()=>{
'use strict';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const TEAM=['瑞子','普子','航子','辉子'];
const FN='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync',TRIP='chuanxi2026';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let S=null,view='related',lastPending=-1,renderTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const when=t=>t?new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
async function api(action,payload={}){const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action,payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'操作失败');return j}
function profile(p){return(S?.profiles||[]).find(x=>x.person===p)||{person:p,nickname:p}}
function name(p){return profile(p).nickname||p}
function acksFor(id){return new Set((S?.ledger_acks||[]).filter(x=>x.item_type==='expense'&&x.item_id===id).map(x=>x.person))}
function needsAck(e,p=ME){return e.status!=='budget'&&e.payer!==p&&(e.participants||[]).includes(p)&&!acksFor(e.id).has(p)}
function pending(){return(S?.expenses||[]).filter(e=>needsAck(e))}
function relatedExpense(e){return e.payer===ME||(e.participants||[]).includes(ME)}
function relatedRepay(r){return r.from_person===ME||r.to_person===ME}
function css(){const s=document.createElement('style');s.textContent=`
.ledger-manage{margin-top:12px}.lm-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.lm-tabs{display:flex;gap:6px;flex-wrap:wrap}.lm-tab{border:1px solid #d8e6e8;background:#fff;color:#456b78;border-radius:999px;padding:7px 10px;font-size:9px;font-weight:900}.lm-tab.on{background:#0b6078;color:#fff;border-color:#0b6078}.lm-alert{margin-top:10px;border:1px solid #f1d8a3;background:#fff8e8;color:#795e27;border-radius:13px;padding:10px 11px;font-size:10px;line-height:1.55}.lm-section{margin-top:14px}.lm-section h4{margin:0 0 7px;font-size:12px}.lm-list{display:grid;gap:8px}.lm-item{border:1px solid #dfeaec;border-radius:13px;background:#fff;padding:11px}.lm-item.pending{border-color:#e7c36f;background:#fffdf7}.lm-row{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.lm-row b{font-size:12px}.lm-amt{font-size:15px!important;color:#0b6078}.lm-meta{font-size:9px;color:#69838d;line-height:1.55;margin-top:4px}.lm-chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.lm-chip{border-radius:999px;padding:4px 7px;font-size:8px;background:#edf4f4;color:#58737c}.lm-chip.ok{background:#e5f6ee;color:#26735c}.lm-chip.wait{background:#fff0d2;color:#8c6422}.lm-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.lm-btn{border:1px solid #d5e4e7;background:#fff;color:#16495c;border-radius:9px;padding:7px 9px;font-size:9px;font-weight:900}.lm-btn.primary{background:#0b6078;border-color:#0b6078;color:#fff}.lm-btn.danger{color:#a33e35;border-color:#eccbc6;background:#fff7f5}.lm-empty{font-size:10px;color:#78909a;padding:12px 0}.lm-modal{position:fixed;z-index:12000;inset:0;background:#062f45d9;display:none;place-items:center;padding:14px;backdrop-filter:blur(8px)}.lm-modal.show{display:grid}.lm-box{width:min(520px,100%);max-height:92vh;overflow:auto;background:#f7fbfb;border-radius:22px;padding:17px;box-shadow:0 30px 80px #001b2980}.lm-box h3{margin:0 0 10px}.lm-form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.lm-form label{font-size:9px;color:#66818e;display:grid;gap:4px}.lm-form input,.lm-form select{width:100%;border:1px solid #d5e5e8;border-radius:10px;padding:10px;background:#fff;color:#123f52}.lm-form .wide{grid-column:1/-1}.lm-part{display:flex;gap:7px;flex-wrap:wrap}.lm-part label{display:flex;align-items:center;gap:4px;border:1px solid #d9e7e8;border-radius:999px;padding:7px 9px;background:#fff;color:#345b68}.lm-foot{display:flex;gap:8px;margin-top:12px}.lm-foot button{flex:1;border:0;border-radius:11px;padding:11px;font-weight:900}.lm-cancel{background:#e9f0f1;color:#16495c}.lm-save{background:#0b6078;color:#fff}.lm-badge{display:none;position:absolute;right:8px;top:3px;min-width:17px;height:17px;border-radius:999px;background:#d14d42;color:#fff;font-size:9px;font-weight:900;align-items:center;justify-content:center;padding:0 4px}.cw-nav button[data-k="trip"]{position:relative}.lm-badge.show{display:flex}.lm-daily{border-color:#f1d8a3!important;background:#fff8e8!important}
`;document.head.appendChild(s)}
function toast(t){let e=$('.cw-toast');if(!e){e=document.createElement('div');e.className='cw-toast';document.body.appendChild(e)}e.textContent=t;clearTimeout(e._t);e._t=setTimeout(()=>e.remove(),3500)}
function ackChips(e){if(e.status==='budget')return'<span class="lm-chip">预算项，无需确认</span>';const a=acksFor(e.id);return(e.participants||[]).map(p=>p===e.payer?`<span class="lm-chip ok">${esc(name(p))} · 付款人</span>`:`<span class="lm-chip ${a.has(p)?'ok':'wait'}">${esc(name(p))} · ${a.has(p)?'已知晓':'待确认'}</span>`).join('')}
function expenseItem(e){const need=needsAck(e),ps=(e.participants||[]).map(name).join(' / ');return`<div class="lm-item ${need?'pending':''}" data-expense="${e.id}"><div class="lm-row"><div><b>${esc(e.category||'其他')}</b><div class="lm-meta">付款人：${esc(name(e.payer))} · ${when(e.created_at)}<br>${esc(e.note||'无备注')}<br>参与：${esc(ps)}</div></div><b class="lm-amt">${money(e.amount)}</b></div><div class="lm-chips">${ackChips(e)}</div><div class="lm-actions">${need?`<button class="lm-btn primary" data-act="ack-exp" data-id="${e.id}">我已知晓</button>`:''}<button class="lm-btn" data-act="edit-exp" data-id="${e.id}">修改这笔账单</button><button class="lm-btn danger" data-act="del-exp" data-id="${e.id}">删除</button></div></div>`}
function repayItem(r){return`<div class="lm-item" data-repay="${r.id}"><div class="lm-row"><div><b>${esc(name(r.from_person))} → ${esc(name(r.to_person))}</b><div class="lm-meta">${when(r.created_at)}<br>${esc(r.note||'收付款记录')}</div></div><b class="lm-amt">${money(r.amount)}</b></div><div class="lm-actions"><button class="lm-btn" data-act="edit-repay" data-id="${r.id}">修改金额 / 收款人</button><button class="lm-btn danger" data-act="del-repay" data-id="${r.id}">删除</button></div></div>`}
function cardHtml(){const ex=(S?.expenses||[]).filter(e=>view==='all'||relatedExpense(e)),rp=(S?.repayments||[]).filter(r=>view==='all'||relatedRepay(r)),pc=pending().length;return`<div class="lm-top"><div><h3 style="margin:0">账本管理</h3><div class="pro-muted">每一笔账都可以单独修改或删除；共同支出需要参与人逐笔确认“已知晓”。</div></div><div class="lm-tabs"><button class="lm-tab ${view==='related'?'on':''}" data-view="related">与我有关</button><button class="lm-tab ${view==='all'?'on':''}" data-view="all">全部账目</button></div></div>${pc?`<div class="lm-alert">你有 <b>${pc}</b> 笔共同支出待确认。确认只代表“我已知晓这笔账”，不会自动代表已经付款。</div>`:''}<div class="lm-section"><h4>支出账单</h4><div class="lm-list">${ex.length?ex.slice().reverse().map(expenseItem).join(''):'<div class="lm-empty">暂无账单</div>'}</div></div><div class="lm-section"><h4>收付款 / 还款记录</h4><div class="lm-list">${rp.length?rp.slice().reverse().map(repayItem).join(''):'<div class="lm-empty">暂无收付款记录</div>'}</div></div>`}
function render(){if(!S)return;const root=$('#proMe [data-body]');if(root){let c=$('#ledgerManageCard');if(!c){c=document.createElement('div');c.id='ledgerManageCard';c.className='pro-card ledger-manage';root.appendChild(c)}c.innerHTML=cardHtml();wireCard(c)}const trip=$('#proTrip [data-body]');if(trip){const pc=pending().length;let n=$('#ledgerNoticeCard');if(pc){if(!n){n=document.createElement('div');n.id='ledgerNoticeCard';n.className='pro-card lm-alert';trip.prepend(n)}n.innerHTML=`<b>账本提醒</b><br>你有 ${pc} 笔共同支出需要确认知晓。请到「我的 → 账本管理」逐笔查看。`}else n?.remove()}badge();dailyNotice()}
function wireCard(c){c.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});c.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>handle(b.dataset.act,b.dataset.id))}
function badge(){const b=$('.cw-nav button[data-k="trip"]');if(!b)return;let x=b.querySelector('.lm-badge');if(!x){x=document.createElement('i');x.className='lm-badge';b.appendChild(x)}const n=pending().length;x.textContent=n;x.classList.toggle('show',n>0);if(lastPending>=0&&n>lastPending)toast(`新增 ${n-lastPending} 笔共同账单需要你确认`);lastPending=n}
function dailyNotice(){const box=$('.cw-dailybox');if(!box)return;const n=pending().length;let d=box.querySelector('.lm-daily');if(n){if(!d){d=document.createElement('div');d.className='cw-item lm-daily';const ok=box.querySelector('.cw-ok');box.insertBefore(d,ok)}d.innerHTML=`<span>账本提醒</span><b>今天有 ${n} 笔共同支出需要你确认知晓</b>`}else d?.remove()}
function modal(){let m=$('#ledgerEditModal');if(m)return m;m=document.createElement('div');m.id='ledgerEditModal';m.className='lm-modal';m.innerHTML='<div class="lm-box"><h3 id="lmTitle">修改账目</h3><div id="lmBody"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')});return m}
function peopleOptions(sel){return TEAM.map(p=>`<option value="${p}" ${p===sel?'selected':''}>${esc(name(p))}</option>`).join('')}
function openExpense(e){const m=modal(),b=m.querySelector('#lmBody');m.querySelector('#lmTitle').textContent='修改支出账单';b.innerHTML=`<div class="lm-form"><label>分类<input id="lmCat" value="${esc(e.category||'其他')}"></label><label>金额<input id="lmAmount" type="number" min="0.01" step="0.01" value="${Number(e.amount)}"></label><label>付款人<select id="lmPayer">${peopleOptions(e.payer)}</select></label><label>状态<select id="lmStatus"><option value="paid" ${e.status!=='budget'?'selected':''}>已发生支出</option><option value="budget" ${e.status==='budget'?'selected':''}>预算 / 待定</option></select></label><label class="wide">备注<input id="lmNote" value="${esc(e.note||'')}"></label><label class="wide">参与分摊<div class="lm-part">${TEAM.map(p=>`<label><input type="checkbox" value="${p}" ${(e.participants||[]).includes(p)?'checked':''}>${esc(name(p))}</label>`).join('')}</div></label></div><div class="lm-foot"><button class="lm-cancel" id="lmCancel">取消</button><button class="lm-save" id="lmSave">保存修改</button></div>`;m.classList.add('show');b.querySelector('#lmCancel').onclick=()=>m.classList.remove('show');b.querySelector('#lmSave').onclick=async()=>{const amount=Number(b.querySelector('#lmAmount').value),parts=[...b.querySelectorAll('.lm-part input:checked')].map(x=>x.value);if(!(amount>0)||!parts.length)return alert('金额必须大于0，并至少选择1位参与人');try{await api('update_expense',{id:e.id,actor:ME,category:b.querySelector('#lmCat').value.trim()||'其他',amount,payer:b.querySelector('#lmPayer').value,participants:parts,note:b.querySelector('#lmNote').value.trim(),status:b.querySelector('#lmStatus').value});m.classList.remove('show');toast('账单已修改，参与人的知晓状态已重新确认');await refresh()}catch(err){alert(err.message)}}}
function openRepay(r){const m=modal(),b=m.querySelector('#lmBody');m.querySelector('#lmTitle').textContent='修改收付款记录';b.innerHTML=`<div class="lm-form"><label>付款人<select id="lmFrom">${peopleOptions(r.from_person)}</select></label><label>收款人<select id="lmTo">${peopleOptions(r.to_person)}</select></label><label class="wide">金额<input id="lmAmount" type="number" min="0.01" step="0.01" value="${Number(r.amount)}"></label><label class="wide">备注<input id="lmNote" value="${esc(r.note||'')}"></label></div><div class="lm-foot"><button class="lm-cancel" id="lmCancel">取消</button><button class="lm-save" id="lmSave">保存修改</button></div>`;m.classList.add('show');b.querySelector('#lmCancel').onclick=()=>m.classList.remove('show');b.querySelector('#lmSave').onclick=async()=>{const amount=Number(b.querySelector('#lmAmount').value),from=b.querySelector('#lmFrom').value,to=b.querySelector('#lmTo').value;if(!(amount>0))return alert('金额必须大于0');if(from===to)return alert('付款人和收款人不能是同一个人');try{await api('update_repayment',{id:r.id,actor:ME,from_person:from,to_person:to,amount,note:b.querySelector('#lmNote').value.trim()});m.classList.remove('show');toast('收付款记录已修改');await refresh()}catch(err){alert(err.message)}}}
async function handle(act,id){if(act==='edit-exp'){const e=(S.expenses||[]).find(x=>x.id===id);if(e)openExpense(e);return}if(act==='edit-repay'){const r=(S.repayments||[]).find(x=>x.id===id);if(r)openRepay(r);return}if(act==='ack-exp'){try{await api('acknowledge_expense',{expense_id:id,person:ME});toast('已确认知晓这笔共同支出');await refresh()}catch(e){alert(e.message)}return}if(act==='del-exp'){const e=(S.expenses||[]).find(x=>x.id===id);if(!e)return;if(!confirm(`确认删除这笔账单？\n${e.category} ${money(e.amount)}\n付款人：${name(e.payer)}\n删除后会重新计算所有人的AA结果。`))return;try{await api('delete_expense',{id,actor:ME});toast('该笔账单已删除');await refresh()}catch(err){alert(err.message)}return}if(act==='del-repay'){const r=(S.repayments||[]).find(x=>x.id===id);if(!r)return;if(!confirm(`确认删除这条收付款记录？\n${name(r.from_person)} → ${name(r.to_person)} ${money(r.amount)}\n删除后会重新计算结算结果。`))return;try{await api('delete_repayment',{id,actor:ME});toast('该条收付款记录已删除');await refresh()}catch(err){alert(err.message)}}}
async function refresh(){try{S=await api('get_state');render()}catch(e){console.warn('账本同步失败',e)}}
function observe(){const o=new MutationObserver(()=>{clearTimeout(renderTimer);renderTimer=setTimeout(render,120)});o.observe(document.body,{childList:true,subtree:true})}
function init(){css();modal();refresh();observe();setInterval(refresh,9000)}
setTimeout(init,900);
})();