(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const FN='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync';
const TRIP='chuanxi2026';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const mapState={zoom:16,center:null,tiles:new Map(),profiles:[],positions:[],route:null,routeVisible:false,drag:null,raf:0,loaded:0,failed:0,lastStateAt:0,open:false,previousNav:null};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function localPos(){try{return JSON.parse(localStorage.getItem('cw-lastpos-v4')||'null')}catch(e){return null}}
function wgsToGcj(lat,lon){const PI=Math.PI,a=6378245,ee=.00669342162296594323;if(lon<72.004||lon>137.8347||lat<.8293||lat>55.8271)return[lat,lon];const tf=(x,y)=>-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x))+(20*Math.sin(6*x*PI)+20*Math.sin(2*x*PI))*2/3+(20*Math.sin(y*PI)+40*Math.sin(y/3*PI))*2/3+(160*Math.sin(y/12*PI)+320*Math.sin(y*PI/30))*2/3,tg=(x,y)=>300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x))+(20*Math.sin(6*x*PI)+20*Math.sin(2*x*PI))*2/3+(20*Math.sin(x*PI)+40*Math.sin(x/3*PI))*2/3+(150*Math.sin(x/12*PI)+300*Math.sin(x/30*PI))*2/3;let dLat=tf(lon-105,lat-35),dLon=tg(lon-105,lat-35),r=lat/180*PI,m=1-ee*Math.sin(r)**2,s=Math.sqrt(m);dLat=dLat*180/((a*(1-ee))/(m*s)*PI);dLon=dLon*180/(a/s*Math.cos(r)*PI);return[lat+dLat,lon+dLon]}
function world(lat,lon,z){const scale=256*Math.pow(2,z),x=(lon+180)/360*scale,s=Math.sin(lat*Math.PI/180),y=(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*scale;return{x,y}}
function ll(x,y,z){const scale=256*Math.pow(2,z),lon=x/scale*360-180,n=Math.PI-2*Math.PI*y/scale,lat=180/Math.PI*Math.atan(Math.sinh(n));return{lat,lon}}
function tilePrimary(z,x,y){const s=((x+y)%4+4)%4+1;return`https://webrd0${s}.is.autonavi.com/appmaptile?style=7&lang=zh_cn&size=1&scale=1&x=${x}&y=${y}&z=${z}`}
function tileFallback(z,x,y){return`https://map.geoq.cn/ArcGIS/rest/services/ChinaOnlineCommunity/MapServer/tile/${z}/${y}/${x}`}
function age(ts){if(!ts)return'暂无';const d=Date.now()-new Date(ts).getTime();if(d<20000)return'刚刚';if(d<60000)return`${Math.max(1,Math.round(d/1000))}秒前`;if(d<3600000)return`${Math.round(d/60000)}分钟前`;return`${Math.round(d/3600000)}小时前`}
function avatarFromDom(p){const el=$(`.avatar[data-person="${p}"]`)||[...document.querySelectorAll('.avatar')].find(x=>(x.textContent||'').trim().startsWith(p[0]));if(!el)return'';const bg=getComputedStyle(el).backgroundImage||el.style.backgroundImage||'',m=bg.match(/url\(["']?(.*?)["']?\)/);return m?m[1]:''}
function profile(p){return mapState.profiles.find(x=>x.person===p)||{person:p,nickname:p,last_seen:null,avatar_url:null}}
function avatar(p){return profile(p).avatar_url||avatarFromDom(p)}
function apiState(){const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);return fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action:'get_state',payload:{}}),signal:c.signal}).then(async r=>{clearTimeout(t);if(!r.ok)throw new Error('state');return r.json()}).catch(e=>{clearTimeout(t);return null})}
async function refreshTeam(force=false){if(!force&&Date.now()-mapState.lastStateAt<20000)return;const j=await apiState();if(!j)return;mapState.profiles=j.profiles||[];mapState.positions=j.person_positions||[];mapState.lastStateAt=Date.now();if(mapState.open)renderOverlays()}
function bestOwnPosition(){const local=localPos(),remote=mapState.positions.find(x=>x.person===ME);if(local&&local.lat&&local.lon){const localAge=Date.now()-(local.time||0),remoteAge=remote?.updated_at?Date.now()-new Date(remote.updated_at).getTime():Infinity;if(localAge<10*60000||localAge<=remoteAge)return{lat:+local.lat,lon:+local.lon,accuracy:local.accuracy,updated_at:new Date(local.time||Date.now()).toISOString(),local:true}}if(remote)return{...remote,lat:+remote.lat,lon:+remote.lon};return null}
function initialCenter(){const own=bestOwnPosition();if(own){const g=wgsToGcj(own.lat,own.lon);return{lat:g[0],lon:g[1]}}const pts=mapState.positions.filter(x=>Number.isFinite(+x.lat)&&Number.isFinite(+x.lon));if(pts.length){const a=pts.reduce((s,x)=>s+(+x.lat),0)/pts.length,b=pts.reduce((s,x)=>s+(+x.lon),0)/pts.length,g=wgsToGcj(a,b);return{lat:g[0],lon:g[1]}}return{lat:39.9042,lon:116.4074}}
function ensureMapDom(){const root=$('#fullMap');if(!root)return null;if(!root.querySelector('.cw-map-canvas')){root.innerHTML='<div class="cw-map-canvas" id="cwMapCanvas" tabindex="0"><div class="cw-map-tiles" id="cwMapTiles"></div><svg class="cw-map-route" id="cwMapRoute" aria-hidden="true"></svg><div class="cw-map-markers" id="cwMapMarkers"></div><div class="cw-map-center" aria-hidden="true"></div><div class="cw-map-zoom"><button data-native-zoom="in" aria-label="放大">＋</button><button data-native-zoom="out" aria-label="缩小">−</button></div><div class="cw-map-quick"><button data-map-search="餐厅">🍜 餐饮</button><button data-map-search="公共厕所">🚻 厕所</button><button data-map-search="加油站">⛽ 加油</button><button data-map-search="停车场">🅿️ 停车</button><button data-map-search="医院">🏥 医院</button></div><div class="cw-map-source">高德中文道路底图 · 街道/地名/周边信息以地图实时显示</div><div class="cw-map-fallback" id="cwMapFallback"><b>地图网络暂不可用</b><span>位置和路线功能仍可使用，可直接打开高德地图。</span><button data-mapact="amap">用高德地图打开</button></div></div>';bindCanvas()}return root}
function canvas(){return $('#cwMapCanvas')}
function bindCanvas(){const c=canvas();if(!c||c.dataset.bound)return;c.dataset.bound='1';c.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;c.setPointerCapture?.(e.pointerId);const cp=world(mapState.center.lat,mapState.center.lon,mapState.zoom);mapState.drag={x:e.clientX,y:e.clientY,cx:cp.x,cy:cp.y};c.classList.add('dragging')});c.addEventListener('pointermove',e=>{if(!mapState.drag)return;const d=mapState.drag,n=ll(d.cx-(e.clientX-d.x),d.cy-(e.clientY-d.y),mapState.zoom);mapState.center={lat:n.lat,lon:n.lon};scheduleRender()});const end=()=>{mapState.drag=null;c.classList.remove('dragging')};c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);c.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1:-1)},{passive:false});c.addEventListener('dblclick',e=>{e.preventDefault();zoom(1)})}
function zoom(delta){mapState.zoom=Math.max(4,Math.min(19,mapState.zoom+delta));scheduleRender(true)}
function scheduleRender(force=false){if(force){mapState.tiles.forEach(img=>{clearTimeout(img._cwTimer);img.remove()});mapState.tiles.clear()}if(mapState.raf)return;mapState.raf=requestAnimationFrame(()=>{mapState.raf=0;renderTiles();renderOverlays()})}
function switchTileToFallback(img,z,x,y){if(img.dataset.fallback==='1')return;img.dataset.fallback='1';img.style.visibility='visible';clearTimeout(img._cwTimer);img._cwTimer=setTimeout(()=>{if(!img.complete||!img.naturalWidth){mapState.failed++;img.style.visibility='hidden'}},3500);img.src=tileFallback(z,x,y)}
function renderTiles(){const c=canvas(),pane=$('#cwMapTiles');if(!c||!pane||!mapState.center)return;const w=c.clientWidth||innerWidth,h=c.clientHeight||innerHeight,cp=world(mapState.center.lat,mapState.center.lon,mapState.zoom),size=256,x0=Math.floor((cp.x-w/2)/size)-1,x1=Math.floor((cp.x+w/2)/size)+1,y0=Math.floor((cp.y-h/2)/size)-1,y1=Math.floor((cp.y+h/2)/size)+1,needed=new Set();for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const key=`${mapState.zoom}/${x}/${y}`;needed.add(key);let img=mapState.tiles.get(key);if(!img){img=new Image();img.className='cw-map-tile';img.alt='';img.decoding='async';img.referrerPolicy='no-referrer';img.dataset.z=mapState.zoom;img.dataset.x=x;img.dataset.y=y;img.dataset.fallback='0';img.onload=()=>{clearTimeout(img._cwTimer);img.style.visibility='visible';mapState.loaded++;$('#fullMap').dataset.mapState='ready';$('#cwMapFallback')?.classList.remove('show')};img.onerror=()=>{const z=+img.dataset.z,tx=+img.dataset.x,ty=+img.dataset.y;if(img.dataset.fallback==='0')switchTileToFallback(img,z,tx,ty);else{clearTimeout(img._cwTimer);mapState.failed++;img.style.visibility='hidden'}};img.src=tilePrimary(mapState.zoom,x,y);img._cwTimer=setTimeout(()=>{if(!img.complete||!img.naturalWidth)switchTileToFallback(img,mapState.zoom,x,y)},1800);pane.appendChild(img);mapState.tiles.set(key,img)}img.style.left=`${Math.round(x*size-cp.x+w/2)}px`;img.style.top=`${Math.round(y*size-cp.y+h/2)}px`}for(const[key,img]of mapState.tiles){if(!needed.has(key)){clearTimeout(img._cwTimer);img.remove();mapState.tiles.delete(key)}}}
function pointOnMap(lat,lon){const c=canvas();if(!c||!mapState.center)return null;const w=c.clientWidth,h=c.clientHeight,cp=world(mapState.center.lat,mapState.center.lon,mapState.zoom),p=world(lat,lon,mapState.zoom);return{x:p.x-cp.x+w/2,y:p.y-cp.y+h/2}}
function renderOverlays(){const marks=$('#cwMapMarkers'),svg=$('#cwMapRoute');if(!marks||!svg)return;const own=bestOwnPosition(),rows=[];for(const p of TEAM){let q=mapState.positions.find(x=>x.person===p);if(p===ME&&own)q=own;if(!q||!Number.isFinite(+q.lat)||!Number.isFinite(+q.lon))continue;const g=wgsToGcj(+q.lat,+q.lon),pt=pointOnMap(g[0],g[1]);if(!pt)continue;const pr=profile(p),on=pr.last_seen&&Date.now()-new Date(pr.last_seen).getTime()<120000,u=avatar(p),stale=q.updated_at&&Date.now()-new Date(q.updated_at).getTime()>5*60000;rows.push(`<div class="cw-person-marker ${p===ME?'me':''} ${stale?'stale':''}" style="left:${pt.x}px;top:${pt.y}px"><div class="cw-direction"></div><div class="cw-person-face"${u?` style="background-image:url('${u.replace(/'/g,'%27')}')"`:''}>${u?'':esc(p[0])}<i class="${on||p===ME?'on':''}"></i></div><span>${esc(pr.nickname||p)}${p===ME?' · 我':''}</span></div>`)}marks.innerHTML=rows.join('');if(mapState.routeVisible&&mapState.route?.length){const c=canvas(),w=c.clientWidth,h=c.clientHeight,step=Math.max(1,Math.ceil(mapState.route.length/700)),pts=[];for(let i=0;i<mapState.route.length;i+=step){const r=mapState.route[i],p=pointOnMap(r[0],r[1]);if(p&&p.x>-200&&p.x<w+200&&p.y>-200&&p.y<h+200)pts.push(`${p.x.toFixed(1)},${p.y.toFixed(1)}`)}svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=pts.length>1?`<polyline points="${pts.join(' ')}" fill="none" stroke="#0b6078" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" opacity=".86"/><polyline points="${pts.join(' ')}" fill="none" stroke="#7fe3cb" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>`:''}else svg.innerHTML='';const status=$('#fullMapStatus');if(status){const q=own;status.textContent=q?`高德中文地图 · ${esc(profile(ME).nickname||ME)}位置 ${age(q.updated_at||q.time)}`:'高德中文地图 · 等待定位'}}
function fit(points){const c=canvas();if(!c||!points.length)return;if(points.length===1){mapState.center={lat:points[0][0],lon:points[0][1]};mapState.zoom=17;return scheduleRender(true)}let best=5;for(let z=19;z>=5;z--){const ps=points.map(p=>world(p[0],p[1],z)),xs=ps.map(p=>p.x),ys=ps.map(p=>p.y),ww=Math.max(...xs)-Math.min(...xs),hh=Math.max(...ys)-Math.min(...ys);if(ww<Math.max(120,c.clientWidth-100)&&hh<Math.max(120,c.clientHeight-180)){best=z;break}}const lat=(Math.min(...points.map(p=>p[0]))+Math.max(...points.map(p=>p[0])))/2,lon=(Math.min(...points.map(p=>p[1]))+Math.max(...points.map(p=>p[1])))/2;mapState.center={lat,lon};mapState.zoom=best;scheduleRender(true)}
function centerMe(){const q=bestOwnPosition();if(!q)return;const g=wgsToGcj(q.lat,q.lon);mapState.center={lat:g[0],lon:g[1]};mapState.zoom=17;scheduleRender(true)}
function fitTeam(){const pts=[];for(const q of mapState.positions){if(!Number.isFinite(+q.lat)||!Number.isFinite(+q.lon))continue;pts.push(wgsToGcj(+q.lat,+q.lon))}const q=bestOwnPosition();if(q)pts.push(wgsToGcj(q.lat,q.lon));if(pts.length)fit(pts)}
function tripDay(){const dates=['2026-10-02','2026-10-03','2026-10-04','2026-10-05','2026-10-06','2026-10-07'],d=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),i=dates.indexOf(d);if(i>=0)return i;return new Date()<new Date('2026-10-02T00:00:00+08:00')?0:5}
async function showRoute(){try{if(!mapState.route){const j=await fetch('./road-routes.json',{cache:'force-cache'}).then(r=>r.json()),raw=j?.[String(tripDay())]?.coordinates||[];mapState.route=raw.map(([lon,lat])=>wgsToGcj(lat,lon))}mapState.routeVisible=true;if(mapState.route.length)fit(mapState.route);$('#fullMapStatus').textContent='今日真实道路已显示'}catch(e){$('#fullMapStatus').textContent='今日道路数据暂不可用'}}
function amapSearch(keyword){const q=bestOwnPosition();if(!q)return`https://uri.amap.com/search?keyword=${encodeURIComponent(keyword)}&callnative=1`;const g=wgsToGcj(q.lat,q.lon);return`https://uri.amap.com/search?keyword=${encodeURIComponent(keyword)}&center=${g[1].toFixed(6)},${g[0].toFixed(6)}&callnative=1`}
function amapMe(){const q=bestOwnPosition();if(!q)return'https://uri.amap.com/';const g=wgsToGcj(q.lat,q.lon);return`https://uri.amap.com/marker?position=${g[1].toFixed(6)},${g[0].toFixed(6)}&name=${encodeURIComponent((profile(ME).nickname||ME)+'的位置')}&coordinate=gaode&callnative=1`}
function markFallbackTimer(){const root=$('#fullMap');root.dataset.mapState='loading';mapState.loaded=0;mapState.failed=0;setTimeout(()=>{if(!mapState.open)return;if(mapState.loaded===0){root.dataset.mapState='fallback';$('#cwMapFallback')?.classList.add('show');$('#fullMapStatus').textContent='地图瓦片暂未返回，可直接打开高德地图'}},5000)}
function openNative(){const ov=$('#mapOverlay');if(!ov)return;mapState.previousNav=$('#bottomNav button.on')?.dataset.view||'now';ov.classList.add('show');ov.setAttribute('aria-hidden','false');mapState.open=true;$$('#bottomNav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='map'));ensureMapDom();const hadOwn=!!bestOwnPosition();mapState.center=initialCenter();scheduleRender(true);markFallbackTimer();refreshTeam(true).then(()=>{if(!mapState.open)return;if(!hadOwn&&bestOwnPosition())centerMe();else renderOverlays()});setTimeout(()=>{if(mapState.open)refreshTeam(true)},12000)}
function closeNative(){mapState.open=false;const ov=$('#mapOverlay');ov?.classList.remove('show');ov?.setAttribute('aria-hidden','true');$$('#bottomNav button').forEach(b=>b.classList.toggle('on',b.dataset.view===mapState.previousNav));}
function repairMini(){const grid=$('#tileGrid'),shade=$('#miniMapShade');if(!grid||!shade)return;const imgs=[...grid.querySelectorAll('img')];if(!imgs.length)return;let ok=0,done=0;shade.classList.remove('hide');const finish=()=>{done++;if(ok>0)shade.classList.add('hide');else if(done>=imgs.length){shade.innerHTML='<b>地图网络暂不可用</b><span>点地图可打开完整中文地图</span>';shade.classList.remove('hide')}};for(const img of imgs){if(img.dataset.cwFallback)return;img.dataset.cwFallback='1';let z,x,y;try{const u=new URL(img.src);z=+(u.searchParams.get('z'));x=+(u.searchParams.get('x'));y=+(u.searchParams.get('y'))}catch(e){}const fallback=()=>{if(img.dataset.cwTried==='1'||!Number.isFinite(z)||!Number.isFinite(x)||!Number.isFinite(y))return;img.dataset.cwTried='1';img.style.visibility='visible';clearTimeout(img._cwMiniTimer);img._cwMiniTimer=setTimeout(()=>{if(!img.complete||!img.naturalWidth)finish()},3200);img.src=tileFallback(z,x,y)};img.addEventListener('load',()=>{clearTimeout(img._cwMiniTimer);img.style.visibility='visible';ok++;finish()},{once:true});img.addEventListener('error',()=>{if(img.dataset.cwTried!=='1')fallback();else{clearTimeout(img._cwMiniTimer);finish()}});img._cwMiniTimer=setTimeout(()=>{if(!img.complete||!img.naturalWidth)fallback()},1600)}}
function installMiniObserver(){const grid=$('#tileGrid');if(!grid)return;new MutationObserver(()=>setTimeout(repairMini,0)).observe(grid,{childList:true});repairMini()}
document.addEventListener('click',e=>{const open=e.target.closest('#openMapBtn,#miniMap,#bottomNav button[data-view="map"]');if(open){e.preventDefault();e.stopImmediatePropagation();openNative();return}const z=e.target.closest('[data-native-zoom]');if(z){e.preventDefault();e.stopImmediatePropagation();zoom(z.dataset.nativeZoom==='in'?1:-1);return}const search=e.target.closest('[data-map-search]');if(search){e.preventDefault();e.stopImmediatePropagation();window.open(amapSearch(search.dataset.mapSearch),'_blank');return}const act=e.target.closest('#mapOverlay [data-mapact]');if(act){e.preventDefault();e.stopImmediatePropagation();const a=act.dataset.mapact;if(a==='me')centerMe();else if(a==='team')fitTeam();else if(a==='route')showRoute();else if(a==='amap')window.open(amapMe(),'_blank');return}if(e.target.closest('#closeMapBtn')){e.preventDefault();e.stopImmediatePropagation();closeNative()}},true);
window.addEventListener('resize',()=>{if(mapState.open)scheduleRender(true)});
installMiniObserver();
window.__CW_NATIVE_MAP={open:openNative,close:closeNative,refresh:()=>refreshTeam(true),state:mapState};
})();