(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const TRIP='chuanxi2026';
const SYNC='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync';
const TRASH='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-trash';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const DAYS=[
{date:'2026-10-02',label:'10/2',route:'天府机场 → 雅安',km:'185–195km',drive:'3.5–4小时',hotel:'雅安空山云宿城市民宿',points:[['16:00','天府国际机场','落地 / 取行李'],['17:15','天府国际机场','取车完成 / 出发'],['19:00','服务区','休息 10–15 分钟'],['21:00','雅安','晚餐 / 补给 / 入住']]},
{date:'2026-10-03',label:'10/3',route:'雅安 → 泸定 → 康定 → 折多山 → 新都桥',km:'270–290km',drive:'6.5–8小时',hotel:'上喜民宿（新都桥店）',points:[['06:00','雅安','出发'],['08:30','泸定','短停'],['10:30','康定','午饭 / 补给'],['13:00','折多山','高海拔短停'],['15:00','新都桥','外围拍摄'],['18:00','新都桥','入住']]},
{date:'2026-10-04',label:'10/4',route:'新都桥 → 塔公 → 八美 → 丹巴中路藏寨',km:'150–170km',drive:'4–5小时',hotel:'谷道山居（中路藏寨店）',points:[['07:00','新都桥','晨景'],['09:30','塔公','草原 / 人文'],['11:45','八美','午饭 / 补给'],['16:00','丹巴','抵达'],['17:00','中路藏寨','入住']]},
{date:'2026-10-05',label:'10/5',route:'丹巴 → 小金 → 四姑娘山双桥沟',km:'110–130km',drive:'3–4小时',hotel:'四姑娘山景区住宿（待定）',points:[['06:30','丹巴','出发'],['07:45','小金','早餐 / 加油'],['09:45','双桥沟','进入景区'],['13:30','双桥沟','午餐 / 拍照'],['16:30','双桥沟','出景区'],['17:00','四姑娘山镇','入住']]},
{date:'2026-10-06',label:'10/6',route:'四姑娘山 → 卧龙 → 映秀 → 都江堰 → 天府机场',km:'270–300km',drive:'8–10小时',hotel:'天府云朵酒店（天府国际机场店）',points:[['05:30','四姑娘山镇','出发'],['08:30','卧龙','休息'],['10:00','映秀','经过'],['11:00','都江堰','午饭 / 加油'],['16:00','天府国际机场','机场附近入住']]},
{date:'2026-10-07',label:'10/7',route:'机场酒店 → 还车 → 航站楼',km:'5–20km',drive:'20–40分钟',hotel:'返程',points:[['05:15','机场酒店','起床'],['05:40','机场酒店','退房'],['06:10','还车点','补油 / 还车'],['06:40','天府国际机场','进入航站楼']]}
];
let profiles=[];
function post(url,action,payload={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);return fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action,payload}),signal:c.signal}).then(async r=>{clearTimeout(t);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'操作失败');return j}).catch(e=>{clearTimeout(t);throw e})}
function chinaDate(){return new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})}
function chinaHM(){return new Date().toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false})}
function tripIndex(){const d=chinaDate(),i=DAYS.findIndex(x=>x.date===d);if(i>=0)return i;if(d<'2026-10-02')return 0;return DAYS.length-1}
function suppressDailyPopup(){localStorage.setItem(`cw-daily-${ME}-${chinaDate()}`,'1')}
function setNav(){const labels={now:['⌂','现在'],map:['⌖','地图'],today:['▣','行程'],trip:['¥','记账'],me:['●','我的']};$$('#bottomNav button[data-view]').forEach(b=>{const v=b.dataset.view,[icon,label]=labels[v]||['•',v];const badge=v==='me'?b.querySelector('#navBadge'):null;b.innerHTML=`<span>${icon}</span>${label}`;if(badge)b.appendChild(badge)});}
function hideCardBy(sel){const el=$(sel);const card=el?.closest('.card');if(card)card.classList.add('minimal-hidden')}
function simplifyNow(){
  $('#view-now')?.classList.add('minimal-now');
  const hm=$('#homeMoney');if(hm)hm.classList.add('minimal-hidden');
  hideCardBy('#personalTips');
  const map=$('#mapCard');if(map)map.classList.add('minimal-hidden');
  const grid=$('.now-grid');if(grid)[...grid.children].forEach((x,i)=>{if(i>1)x.classList.add('minimal-hidden')});
  const nowCard=$('.now-card');if(!nowCard||$('#nextTripCard'))return;
  const card=document.createElement('section');card.id='nextTripCard';card.className='card next-trip-card';nowCard.insertAdjacentElement('afterend',card);renderNextTrip();
}
function renderNextTrip(){const el=$('#nextTripCard');if(!el)return;const i=tripIndex(),d=DAYS[i],today=chinaDate(),hm=chinaHM();let next=null,tag=today<'2026-10-02'?'下一程':'下一站';if(today===d.date){next=d.points.find(p=>p[0]>hm)||d.points[d.points.length-1]}else next=d.points[0];el.innerHTML=`<div class="minimal-head"><div><span>${tag}</span><h2>${esc(d.label)} · ${esc(next[1])}</h2></div><button type="button" data-go-itinerary>看全部行程</button></div><p class="next-route">${esc(d.route)}</p><div class="next-meta"><b>${esc(next[0])}</b><span>${esc(next[2])}</span><span>${esc(d.km)} · ${esc(d.drive)}</span></div>`}
function simplifyItinerary(){const view=$('#view-today');if(!view||$('#simpleItinerary'))return;view.querySelector('.page-title h1').textContent='行程';view.querySelector('.page-title p').textContent='10月2日—10月7日 · 左右滑动查看每天';for(const id of ['riskGrid','altChart','routeWeather','timeline'])hideCardBy('#'+id);const box=document.createElement('section');box.id='simpleItinerary';box.className='simple-itinerary';view.querySelector('.page-title').insertAdjacentElement('afterend',box);renderItinerary(tripIndex())}
function renderItinerary(selected){const box=$('#simpleItinerary');if(!box)return;const d=DAYS[selected];box.innerHTML=`<div class="day-strip">${DAYS.map((x,i)=>`<button class="day-chip ${i===selected?'on':''}" data-day="${i}"><b>${x.label}</b><span>Day ${i+1}</span></button>`).join('')}</div><section class="card itinerary-card"><div class="minimal-head"><div><span>Day ${selected+1}</span><h2>${esc(d.route)}</h2></div><b>${esc(d.drive)}</b></div><div class="itinerary-meta"><span>${esc(d.km)}</span><span>住宿：${esc(d.hotel)}</span></div><div class="simple-timeline">${d.points.map((p,i)=>`<div class="simple-stop"><time>${esc(p[0])}</time><i></i><div><b>${esc(p[1])}</b><span>${esc(p[2])}</span></div></div>`).join('')}</div></section>`;box.querySelector(`[data-day="${selected}"]`)?.scrollIntoView({inline:'center',block:'nearest'})}
function simplifyLedger(){const trip=$('#view-trip'),me=$('#view-me');if(!trip||!me)return;const title=trip.querySelector('.page-title');if(title){title.querySelector('h1').textContent='记账';title.querySelector('p').textContent='记一笔、看我该收/该付、修改账单或找回误删记录'}
  hideCardBy('#logs');hideCardBy('#gallery');hideCardBy('#bookings');
  const expense=$('#expenseForm')?.closest('.card');const money=$('#meMoney')?.closest('.card');const ledger=$('#ledgerList')?.closest('.card');
  if(expense)title.insertAdjacentElement('afterend',expense);
  if(money){money.querySelector('h2').textContent='我的账本';expense?.insertAdjacentElement('afterend',money)}
  if(ledger){ledger.querySelector('h2').textContent='账单明细';money?.insertAdjacentElement('afterend',ledger)}
  if(!$('#trashCard')){const t=document.createElement('section');t.id='trashCard';t.className='card trash-card';t.innerHTML='<div class="minimal-head"><div><span>误删可找回</span><h2>已删除</h2></div><button type="button" id="trashToggle">查看</button></div><div id="trashList" hidden></div>';ledger?.insertAdjacentElement('afterend',t)}
}
function simplifyMe(){const view=$('#view-me');if(!view||$('#identitySwitcher'))return;const title=view.querySelector('.page-title');if(title){title.querySelector('h1').textContent='我的';title.querySelector('p').textContent='头像、昵称、职责和身份切换'}const old=$('#switchIdentity')?.closest('.card');if(old)old.classList.add('minimal-hidden');const s=document.createElement('section');s.id='identitySwitcher';s.className='card identity-switcher';s.innerHTML='<div class="minimal-head"><div><span>当前身份</span><h2>切换账号</h2></div></div><div id="identityGrid" class="identity-grid"></div>';view.querySelector('.profile-card')?.insertAdjacentElement('afterend',s);renderIdentityGrid()}
function profile(p){return profiles.find(x=>x.person===p)||{person:p,nickname:p,role:''}}
function renderIdentityGrid(){const el=$('#identityGrid');if(!el)return;el.innerHTML=TEAM.map(p=>{const x=profile(p),u=x.avatar_url||'';return`<button type="button" class="identity-item ${p===ME?'on':''}" data-switch-person="${p}"><span class="identity-avatar"${u?` style="background-image:url('${u.replace(/'/g,'%27')}')"`:''}>${u?'':p[0]}</span><span><b>${esc(x.nickname||p)}</b><small>${esc(x.role||'')}</small></span>${p===ME?'<em>当前</em>':''}</button>`}).join('')}
async function loadProfiles(){try{const j=await post(SYNC,'get_state');profiles=j.profiles||[];renderIdentityGrid()}catch(e){renderIdentityGrid()}}
async function loadTrash(){const list=$('#trashList');if(!list)return;list.innerHTML='<div class="empty">正在读取已删除记录…</div>';try{const j=await post(TRASH,'list_trash');const rows=[...(j.expenses||[]).map(x=>({...x,type:'expense',title:`${x.category} · ${money(x.amount)}`})),...(j.repayments||[]).map(x=>({...x,type:'repayment',title:`${x.from_person} → ${x.to_person} · ${money(x.amount)}`}))].sort((a,b)=>new Date(b.deleted_at)-new Date(a.deleted_at));$('#trashToggle').textContent=rows.length?`查看（${rows.length}）`:'暂无';list.innerHTML=rows.length?rows.map(x=>`<div class="trash-row"><div><b>${esc(x.title)}</b><span>${new Date(x.deleted_at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}</span></div><button type="button" data-restore="${x.type}" data-archive="${x.archive_id}">恢复</button></div>`).join(''):'<div class="empty">没有已删除记录</div>'}catch(e){list.innerHTML='<div class="empty">暂时无法读取已删除记录</div>'}}
function safeDialog(text,onConfirm){let ov=$('#safeDeleteDialog');if(!ov){ov=document.createElement('div');ov.id='safeDeleteDialog';ov.className='minimal-dialog';document.body.appendChild(ov)}ov.innerHTML=`<div class="minimal-dialog-card"><h3>确认删除？</h3><p>${esc(text)}</p><div><button type="button" data-cancel-delete>取消</button><button type="button" class="danger" data-confirm-delete>确认删除</button></div></div>`;ov.classList.add('show');const close=()=>ov.classList.remove('show');ov.onclick=e=>{if(e.target===ov||e.target.closest('[data-cancel-delete]'))close();if(e.target.closest('[data-confirm-delete]')){close();onConfirm()}}}
function undoBar(type,archiveId){let b=$('#undoBar');if(!b){b=document.createElement('div');b.id='undoBar';b.className='undo-bar';document.body.appendChild(b)}b.innerHTML='<span>已删除</span><button type="button">撤回</button>';b.classList.add('show');clearTimeout(b._t);b.querySelector('button').onclick=async()=>{try{await post(TRASH,type==='expense'?'restore_expense':'restore_repayment',{archive_id:archiveId,actor:ME});b.classList.remove('show');document.dispatchEvent(new Event('visibilitychange'));await loadTrash()}catch(e){alert(e.message)}};b._t=setTimeout(()=>b.classList.remove('show'),8000)}
async function deleteAndArchive(type,id,node){try{await post(SYNC,type==='expense'?'delete_expense':'delete_repayment',{id,actor:ME});node?.remove();const j=await post(TRASH,'list_trash');const arr=type==='expense'?j.expenses:j.repayments;const hit=(arr||[]).find(x=>x.original_id===id);if(hit)undoBar(type,hit.archive_id);document.dispatchEvent(new Event('visibilitychange'));await loadTrash()}catch(e){alert(e.message)}}
function bind(){document.addEventListener('click',e=>{const day=e.target.closest('[data-day]');if(day){renderItinerary(Number(day.dataset.day));return}if(e.target.closest('[data-go-itinerary]')){$('#bottomNav button[data-view="today"]')?.click();setTimeout(()=>$('#simpleItinerary')?.scrollIntoView({behavior:'smooth'}),80);return}const sw=e.target.closest('[data-switch-person]');if(sw){const p=sw.dataset.switchPerson;if(TEAM.includes(p)&&p!==ME){localStorage.setItem('cw-person',p);location.replace(`./app-v4.html?person=${encodeURIComponent(p)}`)}return}if(e.target.closest('#trashToggle')){const l=$('#trashList');if(l){l.hidden=!l.hidden;if(!l.hidden)loadTrash()}return}const r=e.target.closest('[data-restore]');if(r){post(TRASH,r.dataset.restore==='expense'?'restore_expense':'restore_repayment',{archive_id:r.dataset.archive,actor:ME}).then(()=>{document.dispatchEvent(new Event('visibilitychange'));loadTrash()}).catch(x=>alert(x.message));return}},false);
  document.addEventListener('click',e=>{const del=e.target.closest('[data-ledger="del-exp"],[data-ledger="del-repay"]');if(!del)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const type=del.dataset.ledger==='del-exp'?'expense':'repayment',id=del.dataset.id,node=del.closest('.ledger-item');safeDialog('只有点击“确认删除”才会删除。取消或关闭不会做任何修改。',()=>deleteAndArchive(type,id,node))},true)}
function init(){suppressDailyPopup();setNav();simplifyNow();simplifyItinerary();simplifyLedger();simplifyMe();bind();loadProfiles();loadTrash();document.documentElement.classList.add('minimal-ready');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
})();