(()=>{
'use strict';
const TEAM=['瑞子','普子','航子','辉子'];
const DEFAULT_ROLE={瑞子:'酒店 / 账本',普子:'攻略 / 路况',航子:'机票 / 航班',辉子:'租车 / 车务'};
const TRIP='chuanxi2026';
const ENDPOINT='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-profile';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const ADMIN=sessionStorage.getItem('cw-admin')==='1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let profiles=[],busy=false,cropState=null;
const channel='BroadcastChannel' in window?new BroadcastChannel('cw-profile-sync'):null;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const el=$('#toast');if(el){el.textContent=msg;el.classList.add('show');clearTimeout(el._pt);el._pt=setTimeout(()=>el.classList.remove('show'),2400)}else console.log(msg)}
function api(action,payload={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);return fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_slug:TRIP,action,payload}),signal:c.signal}).then(async r=>{clearTimeout(t);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'同步失败');return j}).catch(e=>{clearTimeout(t);throw e})}
function profile(p){return profiles.find(x=>x.person===p)||{person:p,nickname:p,role:DEFAULT_ROLE[p]||'',avatar_url:null}}
function mergeProfile(x){if(!x?.person)return;const i=profiles.findIndex(p=>p.person===x.person);if(i>=0)profiles[i]={...profiles[i],...x};else profiles.push(x)}
function cssUrl(bg){const m=String(bg||'').match(/url\(["']?(.*?)["']?\)/);return m?m[1]:''}
function fallbackUrl(p){const direct=window.CHUANXI_AVATARS?.[p[0]]||window.CW_AVATARS?.[p[0]]||'';if(direct)return direct;const seed=$(`#avatarSeeds .avatar[data-person="${p}"]`);if(!seed)return'';return cssUrl(getComputedStyle(seed).backgroundImage||seed.style.backgroundImage)}
function avatarUrl(p){return profile(p).avatar_url||fallbackUrl(p)||''}
function paintAvatar(el,p){if(!el)return;const u=avatarUrl(p);el.dataset.person=p;el.textContent=u?'':p[0];if(u){el.style.backgroundImage=`url("${u.replace(/"/g,'%22')}")`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.style.color='transparent'}else{el.style.backgroundImage='';el.style.color=''}}
function renderIdentityGrid(){const el=$('#identityGrid');if(!el)return;if(!ADMIN){el.closest('#identitySwitcher')?.remove();return}el.innerHTML=TEAM.map(p=>{const x=profile(p);return`<button type="button" class="identity-item ${p===ME?'on':''}" data-switch-person="${p}"><span class="identity-avatar" data-profile-avatar="${p}">${p[0]}</span><span><b>${esc(x.nickname||p)}</b><small>${esc(x.role||DEFAULT_ROLE[p]||'')}</small></span>${p===ME?'<em>当前</em>':''}</button>`}).join('');TEAM.forEach(p=>paintAvatar(el.querySelector(`[data-profile-avatar="${p}"]`),p))}
function paintAll(){TEAM.forEach(p=>$$(`.avatar[data-person="${p}"]`).forEach(el=>paintAvatar(el,p)));paintAvatar($('#homeAvatar'),ME);paintAvatar($('#profileAvatar'),ME);paintAvatar($('#miniAvatar'),ME);const me=profile(ME);const hello=$('#helloName');if(hello)hello.textContent=`${me.nickname||ME}，今天先看这些`;const role=$('#helloRole');if(role)role.textContent=me.role||DEFAULT_ROLE[ME]||'';const nick=$('#nicknameInput');if(nick&&document.activeElement!==nick)nick.value=me.nickname||ME;const roleInput=$('#roleInput');if(roleInput&&document.activeElement!==roleInput)roleInput.value=me.role||DEFAULT_ROLE[ME]||'';renderIdentityGrid();$$('#teamStrip .team-one').forEach(card=>{const av=card.querySelector('.avatar[data-person]');if(!av)return;const p=av.dataset.person;paintAvatar(av,p);const b=card.querySelector('b');if(b)b.textContent=profile(p).nickname||p;const small=card.querySelector('small');if(small){const dot=small.querySelector('.dot');const onlineText=dot?.classList.contains('on')?'在线':'离线';small.innerHTML='';if(dot)small.appendChild(dot);small.append(`${onlineText} · ${profile(p).role||DEFAULT_ROLE[p]||''}`)}});window.dispatchEvent(new CustomEvent('cw:profiles',{detail:{profiles:[...profiles]}}))}
function applyAdminUi(){const old=$('#switchIdentity');old?.closest('.card')?.remove();const box=$('#identitySwitcher');if(!ADMIN)box?.remove();else if(box){box.querySelector('.minimal-head span').textContent='管理员';box.querySelector('.minimal-head h2').textContent='切换查看成员'} }
function ensureCrop(){if($('#avatarCropOverlay'))return;const ov=document.createElement('div');ov.id='avatarCropOverlay';ov.className='avatar-crop-overlay';ov.innerHTML=`<div class="avatar-crop-card"><div class="crop-head"><div><b>调整头像</b><span>拖动照片选择位置</span></div><button type="button" data-crop-close>×</button></div><div class="crop-stage" id="cropStage"><img id="cropImage" alt="头像裁剪"><div class="crop-mask"></div></div><label class="crop-zoom"><span>缩放</span><input id="cropZoom" type="range" min="1" max="3" step="0.01" value="1"></label><div class="crop-actions"><button type="button" data-crop-close>取消</button><button type="button" class="primary" id="cropConfirm">使用这个位置</button></div></div>`;document.body.appendChild(ov);const stage=$('#cropStage'),img=$('#cropImage'),zoom=$('#cropZoom');let drag=null;const clamp=()=>{if(!cropState)return;const w=cropState.nw*cropState.scale*cropState.zoom,h=cropState.nh*cropState.scale*cropState.zoom,maxX=Math.max(0,(w-300)/2),maxY=Math.max(0,(h-300)/2);cropState.dx=Math.max(-maxX,Math.min(maxX,cropState.dx));cropState.dy=Math.max(-maxY,Math.min(maxY,cropState.dy));img.style.width=`${w}px`;img.style.height=`${h}px`;img.style.left=`${150+cropState.dx-w/2}px`;img.style.top=`${150+cropState.dy-h/2}px`};stage.addEventListener('pointerdown',e=>{if(!cropState)return;drag={x:e.clientX,y:e.clientY,dx:cropState.dx,dy:cropState.dy};stage.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag||!cropState)return;cropState.dx=drag.dx+(e.clientX-drag.x);cropState.dy=drag.dy+(e.clientY-drag.y);clamp()});const end=()=>drag=null;stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);zoom.oninput=()=>{if(!cropState)return;cropState.zoom=Number(zoom.value);clamp()};ov.addEventListener('click',e=>{if(e.target===ov||e.target.closest('[data-crop-close]'))closeCrop()});$('#cropConfirm').onclick=confirmCrop;window.__cwCropClamp=clamp}
function closeCrop(){const ov=$('#avatarCropOverlay');ov?.classList.remove('show');if(cropState?.url)URL.revokeObjectURL(cropState.url);if(cropState?.reject)cropState.reject(new Error('cancelled'));cropState=null}
function cropFile(file){ensureCrop();return new Promise((resolve,reject)=>{if(!file||!/^image\//.test(file.type||''))return reject(new Error('请选择图片文件'));const url=URL.createObjectURL(file),img=$('#cropImage');img.onload=()=>{const nw=img.naturalWidth,nh=img.naturalHeight,scale=Math.max(300/nw,300/nh);cropState={url,nw,nh,scale,zoom:1,dx:0,dy:0,resolve,reject};$('#cropZoom').value='1';window.__cwCropClamp?.();$('#avatarCropOverlay').classList.add('show')};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('图片读取失败'))};img.src=url})}
function confirmCrop(){if(!cropState)return;const st=cropState,scale=st.scale*st.zoom,displayW=st.nw*scale,displayH=st.nh*scale,sx=((displayW-300)/2-st.dx)/scale,sy=((displayH-300)/2-st.dy)/scale,ss=300/scale,c=document.createElement('canvas');c.width=c.height=420;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage($('#cropImage'),Math.max(0,sx),Math.max(0,sy),Math.min(ss,st.nw),Math.min(ss,st.nh),0,0,420,420);let data=c.toDataURL('image/jpeg',.84);if(data.length>760000)data=c.toDataURL('image/jpeg',.72);const resolve=st.resolve;if(st.url)URL.revokeObjectURL(st.url);cropState=null;$('#avatarCropOverlay')?.classList.remove('show');resolve(data)}
async function refresh(showError=false){try{const j=await api('list_profiles');profiles=j.profiles||[];paintAll();applyAdminUi()}catch(e){if(showError)toast('资料同步失败：'+e.message)}}
function bindProfileActions(){const save=$('#saveProfile');if(save)save.onclick=async()=>{if(busy)return;const nickname=$('#nicknameInput')?.value.trim(),role=$('#roleInput')?.value.trim()||'';if(!nickname)return toast('昵称不能为空');busy=true;save.disabled=true;const state=$('#avatarState');if(state)state.textContent='正在同步资料…';try{const j=await api('update_profile',{person:ME,nickname,role});mergeProfile(j.profile);paintAll();channel?.postMessage({type:'profile',profile:j.profile});if(state)state.textContent='昵称和职责已同步给所有人';toast('个人资料已同步')}catch(e){if(state)state.textContent='同步失败：'+e.message;toast('同步失败：'+e.message)}finally{busy=false;save.disabled=false}};const change=$('#changeAvatar'),input=$('#avatarInput');if(change&&input){change.onclick=()=>{input.value='';input.click()};input.onchange=async e=>{const file=e.target.files?.[0];if(!file||busy)return;const old={...profile(ME)},state=$('#avatarState');try{const data=await cropFile(file);busy=true;change.disabled=true;if(state)state.textContent='正在上传头像…';mergeProfile({...old,avatar_url:data});paintAll();const j=await api('upload_avatar',{person:ME,data_url:data});mergeProfile(j.profile);paintAll();channel?.postMessage({type:'profile',profile:j.profile});if(state)state.textContent='头像已同步给所有人';toast('头像更换成功')}catch(err){if(err?.message!=='cancelled'){mergeProfile(old);paintAll();if(state)state.textContent='头像上传失败：'+err.message;toast('头像上传失败')}}finally{busy=false;change.disabled=false;input.value=''}}}}
function bind(){document.addEventListener('click',e=>{const sw=e.target.closest('[data-switch-person]');if(!sw)return;if(!ADMIN){e.preventDefault();e.stopPropagation();return}const p=sw.dataset.switchPerson;if(!TEAM.includes(p)||p===ME)return;e.preventDefault();e.stopPropagation();localStorage.setItem('cw-person',p);location.replace(`./app-v4.html?person=${encodeURIComponent(p)}`)},true);channel?.addEventListener('message',e=>{if(e.data?.type==='profile'&&e.data.profile){mergeProfile(e.data.profile);paintAll()}});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(false)});window.addEventListener('focus',()=>refresh(false))}
async function init(){ensureCrop();bindProfileActions();bind();applyAdminUi();await refresh(false);paintAll();setInterval(()=>{if(!document.hidden)refresh(false)},12000);document.documentElement.classList.add('profile-sync-ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80),{once:true});else setTimeout(init,80);
})();