(()=>{
'use strict';
const qs=new URLSearchParams(location.search),ME=qs.get('person')||localStorage.getItem('cw-person')||'瑞子',ADMIN=ME==='瑞子';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const sleep=ms=>new Promise(r=>setTimeout(r,ms));const results=[];const ok=(n,p,d='')=>results.push({name:n,pass:!!p,detail:d});const waitFor=async(fn,ms=9000)=>{const st=Date.now();while(Date.now()-st<ms){try{const v=fn();if(v)return v}catch(e){}await sleep(80)}return null};const click=el=>{if(!el)return false;el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));return true};
async function run(){const d=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});localStorage.setItem(`cw-daily-${ME}-${d}`,'1');localStorage.setItem(`cw-daily-brief-${ME}-${d}`,'1');localStorage.setItem('cw-lastpos-v4',JSON.stringify({lat:39.814313,lon:116.577886,accuracy:8,altitude:42,time:Date.now()}));await waitFor(()=>!$('#app')?.hidden,5000);await waitFor(()=>$('#nextTripCard')&&$('#simpleItinerary'),9000);await waitFor(()=>document.documentElement.classList.contains('profile-sync-ready'),9000);await waitFor(()=>document.documentElement.classList.contains('profile-upload-v3-ready'),9000);await waitFor(()=>typeof window.__cwDailyTestOpen==='function',9000);await waitFor(()=>$('#cwAckAll'),9000);await waitFor(()=>document.documentElement.classList.contains('travel-assist-ready'),9000);await waitFor(()=>document.documentElement.classList.contains('cw-social-ready'),9000);
  ok('页面启动',!!$('#app')&&!$('#app').hidden);ok('密码守卫已放行',document.documentElement.classList.contains('cw-auth-ready'));ok('身份标题',document.title.includes(ME),document.title);ok('底部只显示4项',$$('#bottomNav button[data-view]:not([hidden])').length===4,String($$('#bottomNav button[data-view]:not([hidden])').length));ok('没有地图Tab',!$('#bottomNav button[data-view="map"]')||$('#bottomNav button[data-view="map"]')?.hidden===true);ok('现在页有地图入口',!!$('#quickMapBtn'));ok('Tab行程',$('#bottomNav button[data-view="today"]')?.innerText.includes('行程'));ok('Tab记账',$('#bottomNav button[data-view="trip"]')?.innerText.includes('记账'));ok('下一站行动卡',!!$('#nextTripCard .cw-next-actions')&&/一键导航/.test($('#nextTripCard')?.innerText||''));ok('今日待办卡',!!$('#cwTaskCard')&&$$('#cwTaskCard [data-assist-task]').length>=1);ok('弱网/实时状态',!!$('#cwNetBadge'));
  ok('四人实时状态卡',!!$('#cwSocialCard')&&$$('#cwMemberRow [data-social-person]').length===4,String($$('#cwMemberRow [data-social-person]').length));ok('当前驾驶员状态',/开车|驾驶/.test($('#cwDriverBox')?.innerText||''));ok('四人准备卡',!!$('#cwReadyBox')&&/4/.test($('#cwReadyBox')?.innerText||''));
  const meMember=$(`#cwMemberRow [data-social-person="${ME}"]`);if(meMember){click(meMember);await waitFor(()=>$('#cwSocialSheet')?.classList.contains('show'),1000);ok('个人状态菜单可打开',!!$('[data-set-status]'));const st=$('[data-set-status="📸"]');if(st){click(st);await waitFor(()=>!$('#cwSocialSheet')?.classList.contains('show'),1600);await waitFor(()=>$(`#cwMemberRow [data-social-person="${ME}"] .cw-member-emoji`),1600);ok('头像临时状态同步',!!$(`#cwMemberRow [data-social-person="${ME}"] .cw-member-emoji`))}}
  const other=TEAM.find(x=>x!==ME),otherEl=$(`#cwMemberRow [data-social-person="${other}"]`);if(otherEl){click(otherEl);await waitFor(()=>$('#cwSocialSheet')?.classList.contains('show'),1000);ok('戳一下菜单',$$('[data-nudge-to]').length===4,String($$('[data-nudge-to]').length));const n=$('[data-nudge-to]');if(n){click(n);await waitFor(()=>!$('#cwSocialSheet')?.classList.contains('show'),1600);ok('轻提醒可发送',!$('#cwSocialSheet')?.classList.contains('show'))}}
  const ready=$('#cwReadyToggle');if(ready){const before=$('#cwReadyBox')?.innerText||'';click(ready);await sleep(320);ok('我好了可同步',($('#cwReadyBox')?.innerText||'')!==before,$('#cwReadyBox')?.innerText||'')}
  const task=$('#cwTaskCard [data-assist-task]');if(task){click(task);await sleep(250);ok('今日任务可完成',task.checked===true)}
  const payer=$('#expPayer');ok('默认付款人正确',payer?.value===ME,payer?.value||'');click($('#bottomNav button[data-view="today"]'));await sleep(250);ok('6天滑动行程',$$('#simpleItinerary [data-day]').length===6,String($$('#simpleItinerary [data-day]').length));click($('#simpleItinerary [data-day="2"]'));await waitFor(()=>$('#cwRoutePanel'),1800);ok('可切换每日行程',$('#simpleItinerary')?.innerText.includes('塔公'));ok('行程路线图存在',!!$('#cwRoutePanel'));ok('分段距离时间存在',/km/.test($('#simpleItinerary')?.innerText||'')&&/约/.test($('#simpleItinerary')?.innerText||''));await waitFor(()=>$('#cwDailySummary'),1500);ok('每日小结入口',!!$('#cwDailySummary'));await waitFor(()=>$('#cwInspiration .cw-insp-card'),2500);ok('景区拍照灵感图库',!!$('#cwInspiration .cw-insp-card'));ok('左右滑动投票入口',!!$('[data-swipe-vote="-1"]')&&!!$('[data-swipe-vote="1"]'));const like=$('[data-swipe-vote="1"]');if(like){click(like);await sleep(400);ok('拍照灵感喜欢可同步',/喜欢|值得|滑动|必拍/.test($('#cwInspiration')?.innerText||''))}ok('小红书灵感入口',!!$('#cwInspiration .cw-insp-search'));
  click($('#bottomNav button[data-view="trip"]'));await sleep(220);ok('快速记账',!!$('#view-trip #expenseForm'));ok('快捷记账模板',$$('.cw-quick-chip').length===6,String($$('.cw-quick-chip').length));const oil=$('.cw-quick-chip[data-exp-cat="油费"]');if(oil){click(oil);await sleep(50);ok('快捷模板自动填分类',$('#expCategory')?.value==='油费',$('#expCategory')?.value||'');ok('快捷模板默认本人付款',$('#expPayer')?.value===ME,$('#expPayer')?.value||'')}ok('我的账本',!!$('#view-trip #meMoney'));ok('账单明细',!!$('#view-trip #ledgerList'));await waitFor(()=>$defaultReaction(),1600);function $defaultReaction(){return $('#ledgerList [data-exp-react]')}ok('账单轻反馈',!!$defaultReaction());if($defaultReaction()){click($defaultReaction());await sleep(220);ok('账单反馈同步',!!$('#ledgerList [data-exp-react].on'))}ok('已删除入口',!!$('#view-trip #trashCard'));const before=$$('#ledgerList .ledger-item').length,del=$('#ledgerList [data-ledger="del-exp"]');if(del){click(del);await sleep(50);ok('删除先确认',$('#safeDeleteDialog')?.classList.contains('show'));click($('#safeDeleteDialog [data-cancel-delete]'));await sleep(40);ok('取消不删除',$$('#ledgerList .ledger-item').length===before)}
  click($('#bottomNav button[data-view="me"]'));await sleep(180);ok('个人资料可编辑',!!$('#profileAvatar')&&!!$('#nicknameInput')&&!!$('#roleInput')&&!!$('#changeAvatar'));const switchCount=$$('#identityGrid [data-switch-person]').length;ok('账号切换权限正确',ADMIN?switchCount===4:switchCount===0,`switch=${switchCount}`);ok('昵称职责属于当前账号',$('#nicknameInput')?.value===ME+'昵称'&&$('#roleInput')?.value.length>0,`${$('#nicknameInput')?.value}|${$('#roleInput')?.value}`);
  const unreadBefore=Number(($('#pendingBadge')?.textContent.match(/\d+/)||['0'])[0]);ok('与我有关未读可见',unreadBefore>0,String(unreadBefore));ok('一键已读入口',!!$('#cwAckAllBtn')&&!$('#cwAckAll')?.hidden);if($('#cwAckAllBtn')){click($('#cwAckAllBtn'));await waitFor(()=>/^0/.test($('#pendingBadge')?.textContent||''),3000);ok('一键已读同步',/^0/.test($('#pendingBadge')?.textContent||''),$('#pendingBadge')?.textContent||'')}
  $('#nicknameInput').value=ME+'测试昵称';$('#roleInput').value='测试职责';click($('#saveProfile'));await waitFor(()=>$('#helloName')?.textContent.includes('测试昵称'),2500);ok('昵称即时同步',$('#helloName')?.textContent.includes('测试昵称'));ok('职责即时同步',$('#helloRole')?.textContent==='测试职责');
  const input=$('#avatarInput');if(input){const b64='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),f=new File([bytes],'qa-avatar.png',{type:'image/png'}),dt=new DataTransfer();dt.items.add(f);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));await waitFor(()=>$('#avatarCropOverlay')?.classList.contains('show'),1800);ok('头像自定义裁剪弹出',$('#avatarCropOverlay')?.classList.contains('show'));click($('#cropConfirm'));await waitFor(()=>/同步给所有人|上传失败/.test($('#avatarState')?.textContent||''),6000);ok('裁剪头像可上传同步',/同步给所有人/.test($('#avatarState')?.textContent||''),$('#avatarState')?.textContent||'')}
  if(ME==='瑞子'){localStorage.removeItem(`cw-daily-brief-${ME}-${d}`);window.__cwDailyTestOpen();await waitFor(()=>$('#cwDailyCard')?.classList.contains('show'),1000);ok('每日弹窗居中出现',$('#cwDailyCard')?.classList.contains('show'));ok('每日弹窗3秒内不可关闭',$('.cw-daily-close')?.disabled&&$('.cw-daily-ok')?.disabled);await sleep(3200);ok('每日弹窗3秒后可关闭',!$('.cw-daily-close')?.disabled&&!$('.cw-daily-ok')?.disabled);click($('.cw-daily-ok'));await sleep(60);ok('每日弹窗确认后关闭',!$('#cwDailyCard')?.classList.contains('show'))}else ok('每日弹窗模块可用',typeof window.__cwDailyTestOpen==='function');
  click($('#bottomNav button[data-view="now"]'));await sleep(80);click($('#quickMapBtn'));await waitFor(()=>$('#cwMapCanvas'),3000);ok('地图容器',!!$('#cwMapCanvas'));const mapReady=await waitFor(()=>['ready','fallback'].includes($('#fullMap')?.dataset.mapState),7000);ok('地图不会空白卡死',!!mapReady,$('#fullMap')?.dataset.mapState||'');ok('地图标题只显示我的位置',$('.map-top b')?.textContent==='我的当前位置',$('.map-top b')?.textContent||'');ok('地图只有本人标记',$$('.cw-person-marker').length<=1,String($$('.cw-person-marker').length));ok('地图无路线/四人/导航按钮',!$('.map-actions')&&!$('[data-mapact="route"]')&&!$('[data-mapact="team"]'));ok('地图支持缩放按钮',!!$('[data-native-zoom="in"]')&&!!$('[data-native-zoom="out"]'));click($('#closeMapBtn'));await sleep(50);
  ok('无旧PIN报错',!/PIN不正确|pin不正确/i.test(document.body.innerText));const ids=$$('[id]').map(x=>x.id),dup=[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))];ok('无重复DOM ID',dup.length===0,dup.join(','));const errs=(window.__cwErrors||[]).filter(x=>x&&!/ResizeObserver loop/i.test(x));ok('无未捕获脚本错误',errs.length===0,errs.join(' | '));const fail=results.filter(x=>!x.pass),pre=document.createElement('pre');pre.id='qaResult';pre.dataset.status=fail.length?'fail':'pass';pre.style.cssText='position:fixed;left:-9999px;top:0';pre.textContent=(fail.length?'QA_FAIL':'QA_PASS')+'|'+ME+'|'+results.map(x=>`${x.pass?'✓':'✗'}${x.name}${x.detail?'('+x.detail+')':''}`).join('|');document.body.appendChild(pre);if(fail.length)console.error(pre.textContent);else console.log(pre.textContent)}
run().catch(e=>{const pre=document.createElement('pre');pre.id='qaResult';pre.dataset.status='fail';pre.textContent='QA_FAIL|'+ME+'|'+String(e?.stack||e);document.body.appendChild(pre);console.error(e)});
})();