(()=>{
'use strict';
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const TEAM=['瑞子','普子','航子','辉子'];
const PIN='735251';
const FN='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync';
const TRIP='chuanxi2026';
let latest=null,live=null,autoWatch=null,localWx=null,avatarMap={},mapCentered=false,esriAdded=false;
sessionStorage.setItem('cw-cloud-pin',PIN);sessionStorage.setItem('cw-private','1');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const chinaDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const DAYINFO={
 '2026-10-02':{route:'天府机场 → 雅安',max:600,wear:'成都/雅安温差不大，长袖或薄外套即可；车内备一件保暖层。',risk:'落地取车后直接去雅安，国庆晚高峰与高速拥堵优先考虑，不安排额外景点。'},
 '2026-10-03':{route:'雅安 → 泸定 → 康定 → 折多山 → 新都桥',max:4298,wear:'三层穿衣：速干底层 + 抓绒/薄羽绒 + 防风防水外层；折多山带帽子、手套。',risk:'当天第一次快速升到4000m以上。折多山不要跑跳久留；头痛恶心明显就下撤。康定/新都桥建议加满油。'},
 '2026-10-04':{route:'新都桥 → 塔公 → 八美 → 丹巴中路',max:3730,wear:'早晚薄羽绒或抓绒，外层防风；白天日照强，墨镜、防晒必须带。',risk:'塔公、八美海拔仍高，上午节奏放慢；丹巴下降明显，注意连续山路驾驶疲劳。'},
 '2026-10-05':{route:'丹巴 → 小金 → 四姑娘山双桥沟',max:3800,wear:'速干底层 + 抓绒/薄羽绒 + 冲锋衣；景区停留久，保暖优先，备帽子手套。',risk:'双桥沟游览6–7小时，控制步速，多喝水；门票/观光车预约提前确认。'},
 '2026-10-06':{route:'四姑娘山 → 卧龙 → 映秀 → 都江堰 → 天府机场',max:3200,wear:'清晨四姑娘山保暖层+外套，下降到成都平原后可逐层脱掉。',risk:'返机场是最高优先级。05:30出发，遇堵立即取消沿途停留，导航4小时按5–6小时准备。'},
 '2026-10-07':{route:'机场酒店 → 还车 → 航站楼',max:500,wear:'普通城市穿着即可，外套放在随身行李里。',risk:'05:40前退房，确认油量、还车手续、随身证件和行李，07:00前进入机场流程。'}
};
const ROLE={
 '瑞子':{title:'酒店 / 账本负责人',pre:'确认四姑娘山住宿、所有酒店订单和入住联系人；关注AA待收款，不要重复记账。'},
 '普子':{title:'攻略负责人',pre:'每天出发前确认折多山、G318、G350、巴朗山—卧龙最新路况、景区预约与临时管制。'},
 '航子':{title:'机票负责人',pre:'机票费用已经结清。出发前核对航班、值机、证件和行李额度；返程前一晚再确认航班动态。'},
 '辉子':{title:'租车 / 车务负责人',pre:'租车还没最终确定：优先高底盘/SUV，确认保险、救援电话、取还车规则；取车时拍车身、轮胎和油表。'}
};
async function api(action,payload={}){const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,trip_slug:TRIP,action,payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'同步失败');return j}
function injectStyle(){const s=document.createElement('style');s.textContent=`
#privacyBtn,#privacyModal,#cloudBtn,.privacyBadge,#driveLocate{display:none!important}#privateArea.locked{filter:none!important;pointer-events:auto!important;user-select:auto!important}
.pro-nav,.pro-fab{display:none!important}.hot-nav{position:fixed;z-index:8900;left:50%;transform:translateX(-50%);bottom:max(8px,env(safe-area-inset-bottom));width:min(620px,calc(100% - 14px));display:grid;grid-template-columns:repeat(5,1fr);gap:3px;background:#062f45f5;border:1px solid #ffffff25;border-radius:18px;padding:6px;box-shadow:0 16px 42px #001d2c66;backdrop-filter:blur(16px)}.hot-nav button{border:0;background:transparent;color:#c8dce3;border-radius:12px;padding:8px 2px;font-size:10px;font-weight:900}.hot-nav button b{display:block;font-size:19px;line-height:1;margin-bottom:4px}.hot-nav button.on{background:#a5f1d4;color:#06485f}
.hot-sos{position:fixed;z-index:9000;right:13px;bottom:84px;border:0;border-radius:999px;background:#b83932;color:white;padding:12px 15px;font-weight:900;box-shadow:0 10px 28px #7f231f66}.hot-overlay{position:fixed;z-index:9500;inset:0;background:#f3f8f8;display:none;overflow:auto;padding-bottom:30px}.hot-overlay.show{display:block}.hot-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;background:#073b55;color:#fff;padding:14px 16px}.hot-head h2{margin:0;font-size:19px}.hot-close{border:0;border-radius:999px;background:#ffffff20;color:white;padding:8px 12px;font-weight:900}.hot-wrap{width:min(760px,calc(100% - 18px));margin:14px auto}.hot-card{background:#fff;border:1px solid #d7e6e9;border-radius:18px;padding:15px;margin-bottom:11px;box-shadow:0 12px 30px #0a394d12}.hot-card h3{margin:0 0 9px}.hot-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hot-kpi{border:1px solid #dce9eb;border-radius:13px;padding:11px;background:#fbfdfd}.hot-kpi span{display:block;color:#78909a;font-size:9px}.hot-kpi b{display:block;font-size:15px;margin-top:4px}.hot-call{display:block;text-decoration:none;text-align:center;border:0;border-radius:15px;padding:16px;margin:8px 0;font-weight:900;font-size:17px}.hot-red{background:#b83932;color:#fff}.hot-blue{background:#0b6078;color:#fff}.hot-gray{background:#eaf2f3;color:#16495c}.gps-toast{position:fixed;z-index:8800;left:50%;transform:translateX(-50%);top:max(10px,env(safe-area-inset-top));background:#073b55ee;color:#fff;border:1px solid #ffffff2b;border-radius:999px;padding:9px 13px;font-size:11px;box-shadow:0 8px 24px #001b2a44;max-width:calc(100% - 20px);text-align:center}.daily-brief{position:fixed;z-index:10000;inset:0;background:#062f45dd;display:grid;place-items:center;padding:16px;backdrop-filter:blur(8px)}.daily-box{width:min(560px,100%);max-height:90vh;overflow:auto;background:#f7fbfb;border-radius:24px;padding:18px;box-shadow:0 30px 90px #00152288}.daily-top{display:flex;gap:12px;align-items:center}.daily-face{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#0b6078;color:#fff;font-size:22px;font-weight:900;background-size:cover;background-position:center;flex:none}.daily-box h2{margin:0;font-size:22px}.daily-sub{font-size:10px;color:#78909a;margin-top:3px}.daily-item{border:1px solid #dce9eb;border-radius:14px;padding:11px 12px;margin-top:9px;background:#fff}.daily-item span{display:block;font-size:9px;color:#78909a;margin-bottom:4px}.daily-item b{font-size:13px;line-height:1.55}.daily-ok{width:100%;border:0;background:#0b6078;color:#fff;border-radius:14px;padding:13px;font-weight:900;margin-top:12px}.member-pin i,.profile-hero .face{background-size:cover!important;background-position:center!important;color:transparent!important}.mapfallback{display:none!important}
@media(max-width:680px){body{padding-bottom:82px!important}.mapwrap{height:58vh!important;min-height:410px!important}.mapcard{overflow:visible!important}.hot-nav{bottom:max(6px,env(safe-area-inset-bottom));border-radius:15px}.hot-sos{bottom:82px}.hot-grid{grid-template-columns:1fr 1fr}.stats{grid-template-columns:repeat(2,1fr)!important}}
`;document.head.appendChild(s)}
function toast(t,ms=3500){let x=$('.gps-toast');if(!x){x=document.createElement('div');x.className='gps-toast';document.body.appendChild(x)}x.textContent=t;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),ms)}
async function loadAvatars(){try{const txt=await fetch('./avatars.js',{cache:'force-cache'}).then(r=>r.text());for(const m of txt.matchAll(/'(瑞|航|普|辉)':'(data:image\/jpeg;base64,[^']+)'/g))avatarMap[m[1]]=m[2];applyAvatars();}catch(e){}}
function applyAvatars(){const targets=$$('.avatar,.bigavatar,.profile-hero .face,.member-pin i');targets.forEach(el=>{const k=(el.textContent||el.getAttribute('aria-label')||'').trim().charAt(0);if(!avatarMap[k])return;el.style.backgroundImage=`url(${avatarMap[k]})`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.style.color='transparent';el.style.overflow='hidden'});}
function cleanupUI(){try{privateUnlocked=true;if(typeof applyPrivacy==='function')applyPrivacy()}catch(e){}const pa=$('#privateArea');if(pa)pa.classList.remove('locked');const vs=$('#vehicleState');if(vs){const stat=vs.closest('.stat');if(stat)stat.style.display='none'}const dl=$('#driveLocate');if(dl)dl.style.display='none';const lb=$('#locateBtn');if(lb){lb.style.display='inline-flex';lb.textContent='⌖ 回到我的位置';lb.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();centerMe()}}const badge=$('#privacyBadge');if(badge)badge.style.display='none';const n=$('.notice');if(n)n.textContent='行车安全优先：页面会自动获取本人实时位置并同步四人位置；真正驾驶导航始终以高德、官方道路管制和现场情况为准。';const ds=$('#driveState');if(ds)ds.textContent=live?'已自动获取你的实时位置并同步给同行':'正在自动获取你的实时位置…';const gs=$('#gpsText');if(gs)gs.textContent=live?`自动定位 · ${ME} · ±${Math.round(live.accuracy||0)}m`:'正在请求定位权限…';const ot=$('#overlayTitle');if(ot&&live)ot.textContent=`📍 ${ME}实时位置`;const od=$('#overlayDetail');if(od&&live)od.textContent=`${guessPlace(live.lat,live.lon)} · ${live.lat.toFixed(5)}, ${live.lon.toFixed(5)}`;const sp=$('#statusPlace');if(sp&&live)sp.textContent=`${ME} · ${guessPlace(live.lat,live.lon)}`;const cs=$('#currentState');if(cs&&live)cs.textContent='本人实时位置';$$('*').forEach(el=>{if(el.children.length)return;const t=(el.textContent||'').trim();if(t==='私密云同步已解锁'||t==='私密云同步未解锁')el.textContent='四人云同步已开启';if(t==='需PIN')el.textContent='已同步';if(t==='未开启'&&el.parentElement?.textContent?.includes('位置共享'))el.textContent='自动开启';if(t.includes('车辆位置将通过云端同步'))el.textContent=t.replace('车辆位置','四人位置')});const sm=$('#shareMe'),mm=$('#myShare');if(sm)sm.style.display='none';if(mm)mm.style.display='none';applyAvatars();hideOldVehicle();}
function hideOldVehicle(){try{if(typeof map!=='undefined'&&typeof carMarker!=='undefined'&&map?.hasLayer(carMarker))map.removeLayer(carMarker)}catch(e){}$$('.metric,.kv div,.syncbar').forEach(el=>{const t=el.textContent||'';if(/车辆状态|车辆定位/.test(t))el.style.display='none'})}
function mountNav(){const old=$('.hot-nav');if(old)return;const nav=document.createElement('nav');nav.className='hot-nav';nav.innerHTML=`<button data-go="now"><b>◉</b>现在</button><button data-go="map"><b>⌖</b>地图</button><button data-go="today"><b>☀</b>今天</button><button data-go="trip"><b>▣</b>旅途</button><button data-go="me"><b>●</b>我的</button>`;document.body.appendChild(nav);nav.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;nav.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));openSection(b.dataset.go)});nav.querySelector('[data-go="now"]').classList.add('on')}
function closePanels(){document.querySelectorAll('.pro-modal').forEach(x=>x.classList.remove('show'))}
function openSection(k){if(k==='now'){closePanels();document.querySelector('.drive')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(k==='map'){closePanels();const c=document.querySelector('.mapcard')||document.querySelector('#map');c?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{try{map.invalidateSize();if(live)map.setView([live.lat,live.lon],13)}catch(e){}},350);return}const id={today:'#proToday',trip:'#proTrip',me:'#proMe'}[k];if(id){closePanels();const p=$(id);if(p){p.classList.add('show');p.scrollTop=0}else toast('模块正在加载，请再点一次',1800)}}
function centerMe(){if(!live)return toast('正在获取当前位置，请允许浏览器定位');try{map.invalidateSize();map.setView([live.lat,live.lon],14)}catch(e){toast('地图正在加载，请稍后再试')}}
function addEsri(){if(esriAdded)return;try{if(typeof map==='undefined'||!map||typeof L==='undefined')return;L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,attribution:'Tiles © Esri'}).addTo(map);esriAdded=true;map.invalidateSize()}catch(e){}}
function guessPlace(lat,lon){if(lat>39&&lat<41.3&&lon>115.3&&lon<117.6)return'北京';if(lat>29&&lat<32&&lon>101&&lon<105)return'川西沿线';return'当前位置'}
function startAutoLocation(){if(!navigator.geolocation||!window.isSecureContext){toast('当前浏览器无法自动定位，请使用 Safari / Chrome 并允许定位',6000);return}if(autoWatch!==null)return;toast('正在自动获取你的实时位置…',2600);autoWatch=navigator.geolocation.watchPosition(async pos=>{const c=pos.coords;live={lat:c.latitude,lon:c.longitude,altitude:c.altitude,accuracy:c.accuracy,speed:c.speed,heading:c.heading,time:Date.now()};localStorage.setItem('cw-pro-lastpos',JSON.stringify(live));try{lastGps={lat:c.latitude,lon:c.longitude,time:Date.now(),acc:c.accuracy,speed:c.speed,heading:c.heading,altitude:c.altitude}}catch(e){}try{await api('update_person_position',{person:ME,lat:c.latitude,lon:c.longitude,altitude:c.altitude,accuracy:c.accuracy,speed:c.speed,heading:c.heading,status:'在线'})}catch(e){}addEsri();if(!mapCentered){centerMe();mapCentered=true}cleanupUI();fetchLocalWeather();},err=>{const msg=err.code===1?'定位权限未开启：请在浏览器设置里允许此网站访问位置':'暂时获取不到定位，正在继续重试';toast(msg,7000)},{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
async function fetchLocalWeather(){if(!live)return;try{const j=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${live.lat}&longitude=${live.lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=Asia%2FShanghai&forecast_days=1`).then(r=>r.json());localWx=j.current||null;updateBriefWeather()}catch(e){}}
function wxName(c){c=+c;if(c<=1)return'晴';if(c<=3)return'多云';if([45,48].includes(c))return'雾';if(c>=51&&c<=67)return'有雨';if(c>=71&&c<=77)return'有雪';if(c>=80&&c<=82)return'阵雨';if(c>=85&&c<=86)return'阵雪';if(c>=95)return'雷暴';return'天气变化'}
function mountSOS(){if($('#hotSos'))return;const b=document.createElement('button');b.id='hotSos';b.className='hot-sos';b.textContent='SOS';b.onclick=showSOS;document.body.appendChild(b);const m=document.createElement('section');m.id='hotSosModal';m.className='hot-overlay';m.innerHTML=`<div class="hot-head"><h2>SOS / 紧急情况</h2><button class="hot-close">关闭</button></div><div class="hot-wrap" id="hotSosBody"></div>`;document.body.appendChild(m);m.querySelector('.hot-close').onclick=()=>m.classList.remove('show')}
function showSOS(){const m=$('#hotSosModal'),p=live||JSON.parse(localStorage.getItem('cw-pro-lastpos')||'null');m.classList.add('show');const coords=p?`${Number(p.lat).toFixed(5)}, ${Number(p.lon).toFixed(5)}`:'尚未取得定位',alt=p?.altitude?Math.round(p.altitude)+' m':'—',center=p?`&center=${p.lon},${p.lat}`:'';$('#hotSosBody').innerHTML=`<div class="hot-card"><h3>当前救援信息</h3><div class="hot-grid"><div class="hot-kpi"><span>当前位置</span><b>${esc(guessPlace(p?.lat||0,p?.lon||0))}</b></div><div class="hot-kpi"><span>经纬度</span><b style="font-size:12px">${coords}</b></div><div class="hot-kpi"><span>海拔</span><b>${alt}</b></div><div class="hot-kpi"><span>时间</span><b>${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</b></div></div></div><a class="hot-call hot-red" href="tel:120">拨打 120 急救</a><a class="hot-call hot-blue" href="tel:110">拨打 110 报警</a><a class="hot-call hot-gray" href="https://uri.amap.com/search?keyword=${encodeURIComponent('医院')}${center}&view=map&callnative=1" target="_blank">附近医院</a><a class="hot-call hot-gray" href="https://uri.amap.com/search?keyword=${encodeURIComponent('汽车维修')}${center}&view=map&callnative=1" target="_blank">附近修理厂</a><div class="hot-card"><h3>救援 / 保险联系人</h3><div id="hotContacts">正在同步…</div></div>`;api('get_state').then(s=>{const cs=s.emergency_contacts||[];const box=$('#hotContacts');if(box)box.innerHTML=cs.length?cs.map(c=>`<a class="hot-call hot-gray" href="tel:${esc(c.phone)}">${esc(c.label)} · ${esc(c.phone)}</a>`).join(''):'<div style="color:#78909a;font-size:12px">租车确定后记得录入租车救援电话与保险电话。</div>'}).catch(()=>{})}
function settlePlan(s){const net=Object.fromEntries(TEAM.map(n=>[n,0]));for(const e of s.expenses||[]){if(e.status==='budget')continue;const a=Number(e.amount||0),ps=e.participants?.length?e.participants:TEAM,sh=a/ps.length;net[e.payer]=(net[e.payer]||0)+a;ps.forEach(n=>net[n]=(net[n]||0)-sh)}for(const r of s.repayments||[]){const a=Number(r.amount||0);net[r.from_person]=(net[r.from_person]||0)+a;net[r.to_person]=(net[r.to_person]||0)-a}const ds=TEAM.filter(n=>net[n]<-.01).map(n=>({n,v:-net[n]})),cs=TEAM.filter(n=>net[n]>.01).map(n=>({n,v:net[n]})),out=[];let i=0,j=0;while(i<ds.length&&j<cs.length){const a=Math.min(ds[i].v,cs[j].v);out.push({from:ds[i].n,to:cs[j].n,amount:Math.round(a*100)/100});ds[i].v-=a;cs[j].v-=a;if(ds[i].v<.01)i++;if(cs[j].v<.01)j++}return out}
function paymentText(s){const p=settlePlan(s),pay=p.filter(x=>x.from===ME),recv=p.filter(x=>x.to===ME);if(pay.length)return'你当前需要支付：'+pay.map(x=>`${x.to} ${money(x.amount)}`).join('；');if(recv.length)return'你当前待收：'+recv.map(x=>`${x.from} ${money(x.amount)}`).join('；');return'你当前没有待结算款项。'}
function briefContext(){const d=chinaDate(),info=DAYINFO[d];if(info)return{tag:`${d.slice(5).replace('-','月')}日 · 行程日`,route:info.route,wear:info.wear,risk:info.risk};const start=new Date('2026-10-02T00:00:00+08:00'),now=new Date(),days=Math.ceil((start-now)/86400000);if(days>0)return{tag:`距离出发 ${days} 天`,route:'出发前准备日',wear:'高海拔日按三层穿衣准备：速干底层 + 抓绒/薄羽绒 + 防风防水外层；帽子、手套、墨镜和防晒单独装好。',risk:'现在重点是租车、四姑娘山住宿、景区预约、道路信息和车辆救援资料。出发前24小时再做一次路况/天气总确认。'};return{tag:'行程已结束',route:'川西反穿回顾',wear:'整理装备和照片，检查是否有遗失物品。',risk:'完成AA结算、票据归档和车辆/酒店遗留事项。'}}
function roleToday(){const d=chinaDate(),base=ROLE[ME]?.pre||'';if(!DAYINFO[d])return base;const map={
 '瑞子':{'2026-10-02':'确认雅安酒店到店时间和两间房订单；晚到提前联系酒店。','2026-10-03':'留意大家高反状态和酒店入住；今天不要催行程，身体优先。','2026-10-04':'确认丹巴中路酒店停车/到店方式；同步今天新增费用。','2026-10-05':'确认四姑娘山住宿最终订单、景区预约和次日05:30出发提醒。','2026-10-06':'返机场优先，酒店入住和费用记录放到安全抵达后处理。','2026-10-07':'核对酒店退房、遗漏物品和最终账本。'},
 '普子':{'2026-10-02':'盯高速拥堵和雅安到达时间，不临时增加景点。','2026-10-03':'重点盯泸定—康定—折多山路况、临时管制和折多山天气。','2026-10-04':'确认塔公—八美—丹巴道路状态与中路藏寨进出条件。','2026-10-05':'确认双桥沟预约、开放情况和最后入园/观光车信息。','2026-10-06':'全程盯导航拥堵，出现延误立即建议取消停留，保证返机场。','2026-10-07':'协助确认还车点到航站楼动线。'},
 '航子':{'2026-10-02':'落地后确认四个人行李齐全；机票账已经结清无需重复记录。','2026-10-03':'今天海拔高，提醒大家控制活动强度、补水保暖。','2026-10-04':'帮忙看天气变化和拍照设备电量，重要证件随身。','2026-10-05':'景区时间长，带充电宝、水和随身小食。','2026-10-06':'随时关注返程航班动态，确保到机场后流程顺畅。','2026-10-07':'负责最终航班/值机信息确认。'},
 '辉子':{'2026-10-02':'取车时拍车身、轮胎、玻璃、油表和里程；确认保险/救援电话。','2026-10-03':'康定或新都桥加满油；山路避免夜驾，折多山注意大风和路面。','2026-10-04':'出发前看油量和胎压；连续山路每2小时主动休息。','2026-10-05':'丹巴/小金择机补油，景区停车位置记清。','2026-10-06':'05:30准时发车；都江堰补油，返机场不做冒险绕行。','2026-10-07':'按租车要求补油、拍还车照片并确认费用结清。'}
};return map[ME]?.[d]||base}
function showDailyBrief(){if($('#dailyBrief'))return;const c=briefContext(),m=document.createElement('div');m.id='dailyBrief';m.className='daily-brief';const pay=latest?paymentText(latest):'账本正在同步…';m.innerHTML=`<div class="daily-box"><div class="daily-top"><div class="daily-face" id="dailyFace">${ME[0]}</div><div><h2>${ME}，今天先看这些</h2><div class="daily-sub">${esc(ROLE[ME]?.title||'同行成员')} · ${esc(c.tag)}</div></div></div><div class="daily-item"><span>💰 今天和你有关的钱</span><b id="dailyMoney">${esc(pay)}</b></div><div class="daily-item"><span>📍 你现在的位置 / 天气</span><b id="dailyLocalWx">正在自动定位并获取天气…</b></div><div class="daily-item"><span>✅ 你今天最重要的事</span><b>${esc(roleToday())}</b></div><div class="daily-item"><span>🧥 今天怎么穿</span><b>${esc(c.wear)}</b></div><div class="daily-item"><span>⚠️ 今日注意事项</span><b>${esc(c.risk)}</b></div><div class="daily-item"><span>🗺 今天路线</span><b>${esc(c.route)}</b></div><button class="daily-ok">知道了，进入今天的行程</button></div>`;document.body.appendChild(m);m.querySelector('.daily-ok').onclick=()=>m.remove();const img=avatarMap[ME[0]];if(img){const f=$('#dailyFace');f.style.backgroundImage=`url(${img})`;f.style.color='transparent'}updateBriefWeather()}
function updateBriefWeather(){const el=$('#dailyLocalWx');if(!el)return;if(!live){el.textContent='正在获取实时位置…';return}const place=guessPlace(live.lat,live.lon);if(!localWx){el.textContent=`${place} · 定位精度约 ±${Math.round(live.accuracy||0)}m · 天气加载中`;return}el.textContent=`${place} · ${Math.round(localWx.temperature_2m)}℃（体感${Math.round(localWx.apparent_temperature)}℃）· ${wxName(localWx.weather_code)} · 风${Math.round(localWx.wind_speed_10m)}km/h`}
async function pullState(){try{latest=await api('get_state');const el=$('#dailyMoney');if(el)el.textContent=paymentText(latest)}catch(e){}}
function observe(){const ob=new MutationObserver(()=>cleanupUI());ob.observe(document.body,{childList:true,subtree:true});setInterval(()=>{cleanupUI();mountNav();mountSOS();addEsri()},1200)}
function init(){injectStyle();cleanupUI();mountNav();mountSOS();loadAvatars();pullState().finally(()=>setTimeout(showDailyBrief,650));startAutoLocation();observe();setTimeout(()=>{addEsri();cleanupUI()},1800)}
setTimeout(init,80);
})();