(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ME=new URLSearchParams(location.search).get('person')||localStorage.getItem('cw-person')||'瑞子';
const FN='https://wpfqcztbxxarsrruuuce.supabase.co/functions/v1/trip-sync',TRIP='chuanxi2026';
const DAYS=[
['10/2','D1','天府机场 → 雅安','185–195km','雅安空山云宿','落地取车，补给后直接去雅安，不赶景点。'],
['10/3','D2','雅安 → 泸定 → 康定 → 折多山 → 新都桥','270–290km','上喜民宿 · 新都桥','当天海拔跨度最大，折多山短停，康定/新都桥及时加油。'],
['10/4','D3','新都桥 → 塔公 → 八美 → 丹巴中路藏寨','150–170km','谷道山居 · 中路藏寨','边走边玩，重点是塔公、八美和丹巴，避免主路临停。'],
['10/5','D4','丹巴 → 小金 → 四姑娘山双桥沟','110–130km','四姑娘山住宿','景区深处海拔高，控制步行量，按身体状态安排下车点。'],
['10/6','D5','四姑娘山 → 卧龙 → 映秀 → 都江堰 → 天府机场','270–300km','天府云朵酒店','返程优先，必须留足拥堵和道路不确定性缓冲。'],
['10/7','D6','机场酒店 → 还车 → 航站楼','5–20km','返程','补油、还车、进航站楼，时间优先。']
];
function clickView(v){$('#bottomNav button[data-view="'+v+'"]')?.click()}
function renameTabs(){const today=$('#bottomNav button[data-view="today"]');if(today)today.innerHTML='<span>▤</span>行程';const trip=$('#bottomNav button[data-view="trip"]');if(trip)trip.innerHTML='<span>◫</span>旅途';const p=$('#view-today .page-title');if(p){p.querySelector('.eyebrow').textContent='行程';p.querySelector('h1').textContent='今天 + 全程预览'}const tp=$('#view-trip .page-title');if(tp){tp.querySelector('.eyebrow').textContent='旅途';tp.querySelector('p').textContent='照片、预订和共同动态；财务统一放在“我的”。'}}
function moveFinance(){const form=$('#expenseForm');if(!form)return;const card=form.closest('.card'),me=$('#view-me'),sum=$('#meMoney')?.closest('.card');if(!card||!me||!sum||card.closest('#view-me'))return;card.classList.add('finance-entry');card.querySelector('h2').textContent='记一笔';card.querySelector('.section-head p').textContent='个人账本操作放在这里，不再混在旅途记录里';const toggle=document.createElement('button');toggle.type='button';toggle.className='ux-entry-toggle';toggle.textContent='＋ 新增一笔花销';card.insertBefore(toggle,form);toggle.onclick=()=>{card.classList.toggle('open');toggle.textContent=card.classList.contains('open')?'收起记账':'＋ 新增一笔花销'};sum.insertAdjacentElement('afterend',card)}
function tripPreview(){const view=$('#view-today'),title=view?.querySelector('.page-title');if(!view||!title||$('#tripPreview'))return;const sec=document.createElement('section');sec.id='tripPreview';sec.className='card itinerary-preview';sec.innerHTML=`<div class="section-head"><div><span class="eyebrow">10月2日–10月7日</span><h2>6天行程一眼看完</h2><p>这里只做预览，今天的详细时间线仍在下面。</p></div></div><div class="itinerary-scroll">${DAYS.map((d,i)=>`<button class="day-mini" data-day-mini="${i}"><strong>${d[0]} · ${d[1]}</strong><span>${d[2]}</span></button>`).join('')}</div><div id="dayMiniDetail" class="day-detail"><b>点某一天</b>，查看当天里程、住宿和最重要提醒。</div>`;title.insertAdjacentElement('afterend',sec);sec.addEventListener('click',e=>{const b=e.target.closest('[data-day-mini]');if(!b)return;const i=+b.dataset.dayMini,d=DAYS[i];$$('.day-mini').forEach(x=>x.classList.toggle('on',x===b));$('#dayMiniDetail').innerHTML=`<b>${d[0]} · ${d[2]}</b><br>${d[3]} · 住宿：${d[4]}<br>${d[5]}`})}
function limitList(container,selector,limit,label){if(!container||container.dataset.uxLimit)return;container.dataset.uxLimit='1';const btn=document.createElement('button');btn.className='ux-more';btn.type='button';btn.hidden=true;container.insertAdjacentElement('afterend',btn);const apply=()=>{const items=[...container.querySelectorAll(selector)],open=container.dataset.expanded==='1';items.forEach((x,i)=>x.classList.toggle('ux-collapsed',!open&&i>=limit));btn.hidden=items.length<=limit;btn.textContent=open?`收起${label}`:`查看全部${label}（${items.length}）`;btn.setAttribute('aria-expanded',String(open))};btn.onclick=()=>{container.dataset.expanded=container.dataset.expanded==='1'?'0':'1';apply()};new MutationObserver(apply).observe(container,{childList:true});apply()}
function foldTripCard(card,summary,defaultOpen=false){if(!card||card.dataset.uxFold)return;card.dataset.uxFold='1';const head=card.querySelector('.section-head');if(!head)return;const info=document.createElement('div');info.className='ux-trip-summary';info.textContent=summary;head.insertAdjacentElement('afterend',info);const btn=document.createElement('button');btn.type='button';btn.className='trip-fold-btn';head.appendChild(btn);let open=defaultOpen;const apply=()=>{card.classList.toggle('trip-card-folded',!open);card.classList.toggle('trip-card-open',open);btn.setAttribute('aria-expanded',String(open))};btn.onclick=()=>{open=!open;apply()};apply()}
function tripHierarchy(){const trip=$('#view-trip');if(!trip)return;limitList($('#logs'),'.log',5,'记录');limitList($('#gallery'),'.photo',4,'照片');limitList($('#bookings'),'.booking',3,'预订');const gallery=$('#gallery')?.closest('.card'),booking=$('#bookings')?.closest('.card');foldTripCard(gallery,'最近照片摘要，需要时再展开上传和全部相册。',false);foldTripCard(booking,'酒店、机票、租车等凭证集中在这里，默认收起。',false)}
function personalCompact(){const tips=$('#personalTips');if(!tips||tips.dataset.compact)return;tips.dataset.compact='1';tips.classList.add('personal-compact');const btn=document.createElement('button');btn.className='personal-more';btn.type='button';btn.textContent='更多今日提醒 →';btn.onclick=()=>clickView('today');tips.insertAdjacentElement('afterend',btn)}
function meLayers(){const v=$('#view-me'),title=v?.querySelector('.page-title');if(!v||!title||$('#meJumps'))return;const profile=$('#profileAvatar')?.closest('.card'),money=$('#meMoney')?.closest('.card'),ledger=$('#ledgerList')?.closest('.card');if(profile)profile.id='meProfileSection';if(money)money.id='meMoneySection';if(ledger)ledger.id='meUnreadSection';[profile,money,ledger].forEach(x=>x?.classList.add('me-section-anchor'));const nav=document.createElement('div');nav.id='meJumps';nav.className='me-jumps';nav.innerHTML='<button data-mejump="meProfileSection">个人资料</button><button data-mejump="meMoneySection">我的账本</button><button id="meUnreadJump" data-mejump="meUnreadSection">未读 / 与我有关</button>';title.insertAdjacentElement('afterend',nav);nav.onclick=e=>{const b=e.target.closest('[data-mejump]');if(!b)return;$('#'+b.dataset.mejump)?.scrollIntoView({behavior:'smooth',block:'start'})};const control=document.createElement('div');control.id='unreadControl';control.className='unread-control';control.innerHTML='<strong id="unreadTitle">没有未读账单</strong><p id="unreadText">涉及你的共同支出会集中显示在这里。</p><div class="unread-actions"><button id="jumpUnread">查看未读</button><button id="readAll" class="primary">一键已读</button></div>';ledger?.insertBefore(control,$('#ledgerList'));$('#jumpUnread').onclick=()=>jumpUnread();$('#readAll').onclick=()=>readAll();syncUnread()}
function pendingButtons(){return $$('#ledgerList [data-ledger="ack"]')}
function syncUnread(){const n=pendingButtons().length,b=$('#navBadge'),j=$('#meUnreadJump'),t=$('#unreadTitle'),p=$('#unreadText'),all=$('#readAll');b?.classList.toggle('show',n>0);j?.classList.toggle('unread',n>0);if(t)t.textContent=n?`${n}笔账单等你确认`:'没有未读账单';if(p)p.textContent=n?'点“查看未读”会直接定位到第一笔；确认只是表示你已经看到。':'涉及你的新共同支出会在这里提醒。';if(all)all.disabled=n===0}
function jumpUnread(){clickView('me');setTimeout(()=>{const b=pendingButtons()[0];if(!b)return toastLocal('当前没有未读账单');const item=b.closest('.ledger-item');item?.scrollIntoView({behavior:'smooth',block:'center'});item?.animate?.([{boxShadow:'0 0 0 0 rgba(201,78,66,0)'},{boxShadow:'0 0 0 4px rgba(201,78,66,.22)'},{boxShadow:'0 0 0 0 rgba(201,78,66,0)'}],{duration:1200})},120)}
async function readAll(){let guard=0;const btn=$('#readAll');if(btn){btn.disabled=true;btn.textContent='正在处理…'}while(pendingButtons().length&&guard<12){const a=pendingButtons()[0];a.click();const old=a;let waited=0;while(document.contains(old)&&waited<2500){await new Promise(r=>setTimeout(r,120));waited+=120}guard++}syncUnread();if(btn){btn.disabled=pendingButtons().length===0;btn.textContent='一键已读'}toastLocal(pendingButtons().length?'还有未读，请稍后再试':'已全部标记为已知晓')}
function toastLocal(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function observeUnread(){const l=$('#ledgerList'),p=$('#pendingBadge');if(l)new MutationObserver(syncUnread).observe(l,{childList:true,subtree:true});if(p)new MutationObserver(syncUnread).observe(p,{childList:true,characterData:true,subtree:true});$('#navBadge')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();jumpUnread()})}
function nowHierarchy(){const map=$('#mapCard');if(map){map.querySelector('h2').textContent='四人位置 · 快速看';map.querySelector('.eyebrow').textContent='地图缩略';}const h=$('#view-now .now-card h2');if(h)h.textContent='5秒关键信息'}
function init(){renameTabs();moveFinance();tripPreview();tripHierarchy();personalCompact();meLayers();observeUnread();nowHierarchy();setTimeout(()=>{syncUnread();tripHierarchy()},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80),{once:true});else setTimeout(init,80);
})();