(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function makeToggle(container,selector,limit,label){if(!container)return;const card=container.closest('.card')||container.parentElement;if(!card)return;let btn=card.querySelector(`[data-ux-toggle="${container.id}"]`);if(!btn){btn=document.createElement('button');btn.type='button';btn.className='ux-more';btn.dataset.uxToggle=container.id;card.appendChild(btn)}const apply=()=>{const items=[...container.querySelectorAll(selector)],expanded=container.dataset.expanded==='1';items.forEach((x,i)=>x.classList.toggle('ux-hidden',!expanded&&i>=limit));btn.hidden=items.length<=limit;btn.textContent=expanded?`收起${label}`:`查看全部${label}（${items.length}）`;btn.setAttribute('aria-expanded',String(expanded))};btn.onclick=()=>{container.dataset.expanded=container.dataset.expanded==='1'?'0':'1';apply();if(container.dataset.expanded==='0')container.scrollIntoView({behavior:'smooth',block:'nearest'})};new MutationObserver(apply).observe(container,{childList:true,subtree:false});apply()}
function initCollapses(){makeToggle($('#logs'),'.log',6,'记录');makeToggle($('#gallery'),'.photo',4,'照片');makeToggle($('#bookings'),'.booking',3,'预订');makeToggle($('#ledgerList'),'.ledger-item',5,'账目')}
function unreadUX(){const badge=$('#navBadge');if(!badge)return;badge.title='有未读，点我查看';badge.setAttribute('role','button');badge.setAttribute('tabindex','0');badge.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();badge.click()}})}
function sectionLabels(){const logs=$('#logs');if(logs){const h=logs.closest('.card')?.querySelector('.tabs');if(h&&!h.previousElementSibling?.classList?.contains('ux-section-note')){const n=document.createElement('div');n.className='ux-section-note';n.innerHTML='<b>最近动态</b><span>默认只展示最近记录，需要时再展开。</span>';h.parentNode.insertBefore(n,h)}}const ledger=$('#ledgerList');if(ledger){const p=ledger.closest('.card')?.querySelector('.section-head p');if(p)p.textContent='默认展示最近5笔；可逐笔修改、删除或展开全部'}}
function compactTrip(){const v=$('#view-trip');if(!v)return;const cards=[...v.querySelectorAll(':scope > .card')];cards.forEach((c,i)=>{if(i===0)return;const head=c.querySelector('.section-head');if(!head||c.dataset.uxFold)return;c.dataset.uxFold='1';const title=head.querySelector('h2')?.textContent?.trim();if(!title)return;const body=[...c.children].filter(x=>x!==head);if(!body.length)return;const toggle=document.createElement('button');toggle.type='button';toggle.className='ux-fold-btn';toggle.textContent=i===1?'展开':'收起';head.appendChild(toggle);let collapsed=i===1;const apply=()=>{body.forEach(x=>x.classList.toggle('ux-section-collapsed',collapsed));toggle.textContent=collapsed?'展开':'收起';toggle.setAttribute('aria-expanded',String(!collapsed))};toggle.onclick=()=>{collapsed=!collapsed;apply()};apply()})}
function init(){initCollapses();unreadUX();sectionLabels();compactTrip()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();