import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const TEAM=["瑞子","普子","航子","辉子"],GUEST="访客",ADMIN="瑞子",TRIP="chuanxi2026",enc=new TextEncoder();
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const b64=(bytes:Uint8Array)=>{let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")};
async function tokenHash(t:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(t));return b64(new Uint8Array(d))}
async function validSession(db:any,trip:string,person:string,token:string){if(![...TEAM,GUEST].includes(person)||!token||token.length<20)return false;const q=await db.from("person_sessions").select("expires_at").eq("trip_slug",trip).eq("person",person).eq("token_hash",await tokenHash(token)).maybeSingle();if(q.error)throw q.error;return !!q.data&&new Date(q.data.expires_at).getTime()>Date.now()}
const clean=(v:any,n=160)=>String(v??"").trim().slice(0,n);
const finite=(v:any)=>Number.isFinite(Number(v));
const sameCoord=(a:any,b:any)=>finite(a?.lat)&&finite(a?.lon)&&finite(b?.lat)&&finite(b?.lon)&&Math.abs(Number(a.lat)-Number(b.lat))<1e-6&&Math.abs(Number(a.lon)-Number(b.lon))<1e-6;
function hav(a:any,b:any){const R=6371,p=Math.PI/180,d1=(Number(b.lat)-Number(a.lat))*p,d2=(Number(b.lon)-Number(a.lon))*p,x=Math.sin(d1/2)**2+Math.cos(Number(a.lat)*p)*Math.cos(Number(b.lat)*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(Math.max(0,Math.min(1,x))))}
function uniqueNames(points:any[]){const a:string[]=[];for(const p of points){const n=clean(p.name,80);if(n&&a.at(-1)!==n)a.push(n)}return a}
async function geocode(name:string){const q=encodeURIComponent(`${name} 四川 中国`),u=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=cn&q=${q}`;const r=await fetch(u,{headers:{"User-Agent":"chuanxi-trip-planner/1.0"},signal:AbortSignal.timeout(7000)});if(!r.ok)return null;const j=await r.json();const x=j?.[0];if(!x)return null;const lat=Number(x.lat),lon=Number(x.lon);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon,display_name:x.display_name||name}:null}
async function routeCalc(points:any[],hotel:any){const routePts=[...points];if(finite(hotel?.lat)&&finite(hotel?.lon)){const last=routePts.at(-1);if(!last||hav(last,hotel)>.25)routePts.push({name:hotel.name||"酒店",lat:Number(hotel.lat),lon:Number(hotel.lon)})}const uniq:any[]=[];for(const p of routePts){if(!finite(p.lat)||!finite(p.lon))continue;if(!uniq.length||hav(uniq.at(-1),p)>.02)uniq.push({lat:Number(p.lat),lon:Number(p.lon)})}if(uniq.length<2)return{distance_km:0,drive_minutes:0,geometry:uniq.map(x=>[x.lon,x.lat]),source:"地点不足"};try{const coords=uniq.map(x=>`${x.lon},${x.lat}`).join(";"),u=`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=false`;const r=await fetch(u,{signal:AbortSignal.timeout(10000)});if(r.ok){const j=await r.json(),rt=j?.routes?.[0];if(rt?.distance>0&&rt?.duration>0&&Array.isArray(rt.geometry?.coordinates))return{distance_km:Math.round(rt.distance/100)/10,drive_minutes:Math.max(1,Math.round(rt.duration/60)),geometry:rt.geometry.coordinates,source:"道路路线自动计算"}}}catch{}let km=0;for(let i=1;i<uniq.length;i++)km+=hav(uniq[i-1],uniq[i]);km*=1.28;return{distance_km:Math.round(km*10)/10,drive_minutes:Math.max(10,Math.round(km/45*60)),geometry:uniq.map(x=>[x.lon,x.lat]),source:"坐标路线估算"}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST only"},405);try{const body=await req.json(),trip=String(body.trip_slug||TRIP),action=String(body.action||""),p=body.payload||{},person=String(p.person||""),token=String(p.token||"");const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});if(!await validSession(db,trip,person,token))return json({error:"登录已失效，请重新进入",code:"session_invalid"},401);
if(action==="state"){const q=await db.from("trip_itinerary_days").select("*").eq("trip_slug",trip).order("day_index");if(q.error)return json({error:q.error.message},500);return json({ok:true,days:q.data||[],admin:person===ADMIN,server_time:new Date().toISOString()})}
if(action==="geocode"){if(person!==ADMIN)return json({error:"仅瑞子管理员可修改行程",code:"admin_only"},403);const name=clean(p.name,100);if(!name)return json({error:"请输入地点名称"},400);const hit=await geocode(name);if(!hit)return json({error:`没有自动找到「${name}」的坐标，请手动填写经纬度`},404);return json({ok:true,...hit})}
if(action==="update_day"){if(person!==ADMIN)return json({error:"仅瑞子管理员可修改行程",code:"admin_only"},403);const date=clean(p.day_date,10);if(!/^2026-10-0[2-7]$/.test(date))return json({error:"日期不在本次行程内"},400);const old=await db.from("trip_itinerary_days").select("*").eq("trip_slug",trip).eq("day_date",date).maybeSingle();if(old.error)return json({error:old.error.message},500);if(!old.data)return json({error:"行程日期不存在"},404);const raw=Array.isArray(p.points)?p.points:[],oldPts=Array.isArray(old.data.points)?old.data.points:[];if(raw.length<2||raw.length>14)return json({error:"每天路线至少2个、最多14个地点"},400);const pts:any[]=[];for(let i=0;i<raw.length;i++){const x=raw[i]||{},name=clean(x.name,80),time=clean(x.time,5),note=clean(x.note,160),prev=oldPts[i]||null;if(!name)return json({error:`第${i+1}个地点名称不能为空`},400);let lat=Number(x.lat),lon=Number(x.lon);const renamed=!!prev&&clean(prev.name,80)!==name,keptOld=renamed&&sameCoord({lat,lon},prev);if(!finite(lat)||!finite(lon)||keptOld){const g=await geocode(name);if(!g)return json({error:`无法自动定位新地点「${name}」，请点“查坐标”或手动填写经纬度`},400);lat=g.lat;lon=g.lon}if(lat<-90||lat>90||lon<-180||lon>180)return json({error:`「${name}」坐标不正确`},400);pts.push({time:/^\d{2}:\d{2}$/.test(time)?time:"",name,lat,lon,note})}
const hotelName=clean(p.hotel_name,120),oldHotel={name:clean(old.data.hotel_name,120),lat:old.data.hotel_lat,lon:old.data.hotel_lon};let hotel:any={name:hotelName,lat:Number(p.hotel_lat),lon:Number(p.hotel_lon)};if(!hotelName){hotel.lat=null;hotel.lon=null}else{const renamedHotel=hotelName!==oldHotel.name,keptOldHotel=renamedHotel&&sameCoord(hotel,oldHotel);if(!finite(hotel.lat)||!finite(hotel.lon)||keptOldHotel){const g=await geocode(hotelName);if(!g)return json({error:`无法自动定位新酒店「${hotelName}」，请点“查酒店坐标”或手动填写经纬度`},400);hotel.lat=g.lat;hotel.lon=g.lon}}
const calc=await routeCalc(pts,hotel),route=uniqueNames(pts).join(" → "),now=new Date().toISOString(),row={hotel_name:hotelName,hotel_lat:hotel.lat,hotel_lon:hotel.lon,route_label:route,distance_km:calc.distance_km,drive_minutes:calc.drive_minutes,points:pts,route_geometry:calc.geometry,risk:clean(p.risk??old.data.risk,300),wear:clean(p.wear??old.data.wear,300),calc_source:calc.source,updated_by:ADMIN,updated_at:now};const up=await db.from("trip_itinerary_days").update(row).eq("trip_slug",trip).eq("day_date",date).select().single();if(up.error)return json({error:up.error.message},500);await db.from("activity_logs").insert({trip_slug:trip,person:ADMIN,category:"行程",action:"修改路线/酒店",detail:`${date} · ${route} · ${hotelName||"无住宿"}`,metadata:{day_date:date,distance_km:calc.distance_km,drive_minutes:calc.drive_minutes,calc_source:calc.source}});return json({ok:true,day:up.data})}
return json({error:"unknown action"},400)}catch(e){return json({error:String((e as any)?.message||e)},500)}});